### ISSUE TITLE
问一下设计图通过什么画的，或者说是什么工具导出的

### ISSUE THREAD

**Issue by smile921** [simplezhli/flutter_deer#1]
我们UI 问一下设计图通过什么画的，或者说是什么工具导出的？

**Comment by simplezhli** [comment]
@smile921  Mac下使用 `Sketch` 作图，`Sketch Measure` 插件导出。

**Comment by freecats** [comment]
Sketch也是你设计的？666啊！
设计的源文件不知道方便开源吗？
看了你的这个设计，真心想学Sketch了😺

**Comment by simplezhli** [comment]
@freecats 不是我设计的，是公司同事。源文件的话我具体问问。

**Comment by simplezhli** [comment]
@freecats  问了下，暂不开源

**Comment by tianlinzx** [comment]
这个设计确实好看。不开源也理解，表示尊重。

**Comment by freecats** [comment]
> @freecats 问了下，暂不开源

完全理解，能够学习到这样优秀的Flutter项目工程，真心表示感谢(*^▽^*)
