### ISSUE TITLE
大佬,有单独的密码输入的功能说明么?

### ISSUE THREAD

**Issue by pheromone** [simplezhli/flutter_deer#10]
大佬,有单独的密码输入的功能说明么?

**Comment by simplezhli** [comment]
具体指的是什么效果？

**Comment by pheromone** [comment]
@simplezhli  就是密码输入或者验证码输入这一个小模块. 我看了你写的和其他widget结合起来了.能不能单独封装成一个widget,方便其他项目使用那种.

**Comment by simplezhli** [comment]
这个你还是自己抽离出来使用吧，毕竟代码有了，你可以自由修改。或者可以看看大喵的这个项目https://github.com/CarGuo/GSYFlutterDemo
