### ISSUE TITLE
dio里用rx dart的具体原因是什么？

### ISSUE THREAD

**Issue by liongkj** [simplezhli/flutter_deer#100]
你好，如题。我发现dio的官方例子都是直接async await的。你的app里用的rx dart的stream具体是干嘛的？

**Comment by simplezhli** [comment]
没有什么具体原因，这个项目就是练习作用。这里只是刚好练一下RxDart，哈哈。

**Comment by liongkj** [comment]
那以你的理解加了rxdart有什么优势吗？我只了解加了rxdart可以聆听api的变化，对吗？

**Comment by simplezhli** [comment]
我的理解其实RxDart就是Stream的拓展封装，Stream本身就是响应式的。RxDart为我们提供了许多便于使用方法及操作符。比如`RetryWhenStream` ，` RetryStream` ， `MergeStream`等。

**Comment by liongkj** [comment]
明白了感谢
