### ISSUE TITLE
订单页面下面的五个选项卡对应的页面还是一起滚动

### ISSUE THREAD

**Issue by githubityu** [simplezhli/flutter_deer#102]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`Pixel 3 XL API 28`
- [x] 设备系统版本：如 `Android 9`
- [x] Flutter 版本：如 `1.12.13+hotfix.8`

### 具体问题描述 ###
订单页面下面的五个选项卡对应的页面还是一起滚动
第一个页面滚动到一定距离，再滚动第二个到一定距离再滚动到顶部，第一个也自动滚到顶部了

**Comment by simplezhli** [comment]
这是正常的，因为这里头部有一个伸缩效果。伸缩是靠列表的滑动距离处理的，如果一边滑至顶部，如果其他选项卡的滑动距离不同步，那么伸缩效果会受影响。

其实默认情况下底下的页面会一起滑动，我这里处理了一下，将各自滑动区分了。

相比商品页就没有这个问题。

**Comment by githubityu** [comment]
1.建议商品规格向左可以侧滑并显示删除按钮，能否添加一个点击其他位置可以隐藏删除按钮。我代码试了好多次（ Slidable.of(context)?.close();），没有成功

**Comment by simplezhli** [comment]
兄弟，观察的很仔细，这个建议不错，体验会更好。Slidable也确实没有提供你说的这类需求，我翻了一下源码，找到了一个判断方法。
```java
if (_slidableController.activeState != null) {
   _slidableController.activeState.close();
}
```
我将他添加到了item的点击事件中，如果打开就关闭，否则跳转页面。

**Comment by simplezhli** [comment]
本来想用 `SlidableController`的`onSlideIsOpenChanged`，但是它需要同时实现`onSlideAnimationChanged`。我提供了两种方法，你都可以试试。修改代码，我会稍后上传。
