### ISSUE TITLE
文本输入框输入内容切回桌面回来后消失

### ISSUE THREAD

**Issue by HuasirX** [simplezhli/flutter_deer#103]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米8`
- [x] 设备系统版本：如 `Android 10`
- [x] Flutter 版本：如 `1.12.13+hotfix.8`

### 具体问题描述 ###
文本输入框输入内容在切回桌面回来后被清除掉了，请问有什么方案可以解决

**Comment by simplezhli** [comment]
这个是升级1.12 前Android项目的bug，README有相关描述： 1.12.13已知问题 flutter/issues/47137。

解决方法就是不升级 https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
