### ISSUE TITLE
希望补充切换主题的功能

### ISSUE THREAD

**Issue by DavidMGT** [simplezhli/flutter_deer#104]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 10`
- [x] Flutter 版本：如 `1.12.13+hotfix.8`

### 具体问题描述 ###
现在只有暗黑模式，希望大神提供一个主题切换的功能来参考

**Comment by simplezhli** [comment]
emmmm...其实思路和暗黑模式一样，只是颜色修改一下。不过因为deer中还有部分与主色调相同的图片，所以这个功能就没有做了。可以看https://github.com/Sky24n/flutter_wanandroid 的实现。大同小异。
