### ISSUE TITLE
作者您好，关于BLOC改造项目，MyTextField中的TextEditingController dispose问题

### ISSUE THREAD

**Issue by mrchenmo** [simplezhli/flutter_deer#106]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 10`
- [x] Flutter 版本：如 `1.12.13+hotfix.8`

#### 异常日志 ####

我使用flutter-bloc改造这个项目，目的是学习BLOC模式。在完成注册pop回上一个页面也就是Login页面的时候，会遇到A TextEditingController was used after being disposed.发现是MyTextField
widget.controller?.removeListener(() {});
widget.controller?.dispose();
这两句话导致的，这个dispose我可以写在Login页面里面吗？请问。我还没有弄明白为什么会发生这个错误

**Comment by simplezhli** [comment]
错误信息是说 TextEditingController 释放后又调用了它，这个具体就要看你的代码了。TextEditingController 的dispose可以写在Login页面，但是不利于管理，不建议。

**Comment by mrchenmo** [comment]
@simplezhli 就是所有使用MyTextField的地方都得手动dispose，现在我还没搞明白为什么会报这个错误，先这样写，改好之后再改回去。Login->RegisterPage。然后pop回Login，就报错了好奇怪。
