### ISSUE TITLE
requestNetwork ()添加对多个网络的请求并合并成一个model

### ISSUE THREAD

**Issue by zhangle1** [simplezhli/flutter_deer#107]
### 运行环境 ###
目前调用requestNetwork 的话对单一网络请求比较好处理，想集成下多个网络请求应该怎么做。
Future.wait().then() , 然后做个callback出来 目前我是这么做的 但是感觉写的不是很美观= =

**Comment by simplezhli** [comment]
如果需要等待多个接口请求完成可以使用`RxDart`的`ZipStream`，不需要可以使用`MergeStream`。大致是这样：
```
     ZipStream([
        Stream.fromFuture(_request("GET", url)), // <-- 接口1
        Stream.fromFuture(_request("GET", url_))  // <-- 接口2
      ], (values) => values,)
      .listen((result){
        print(result);
      }, onError: (e, _) {
        print(e);
      });
```

不过和Future.wait相差不多，麻烦的在于数据结果的处理封装。

**Comment by zhangle1** [comment]
对我的感觉就是结合的不是很舒服...  如果android的话 retrofit+rxjava,数据流很轻松就转换过来了。 dart的话  好像也可以做，要加reflectable+dartmapper+  dio+rxdart的adapter？ 期待有大佬能做出来。。

**Comment by simplezhli** [comment]
这种场景我用到的不是很多，不过我觉得还行......   PS：`ZipStream`中有提供zip2 ~ zip9便于简化类型转换。
