### ISSUE TITLE
Refresh list goods after add new goods by using Provider?

### ISSUE THREAD

**Issue by bctechjsc** [simplezhli/flutter_deer#108]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米iphone 6s,  note 8`
- [x] 设备系统版本：如 `Android 9,10`
- [x] Flutter 版本：如 `1.12.13+hotfix.9`

### 具体问题描述 ###
Hi, 
After add new goods, then back goods list and refresh by using provider??? or anyway to refresh list (ensure keep current page/scroll position)?

Thanks you!

**Comment by simplezhli** [comment]
Jump to the goods add page：

```dart
NavigatorUtils.pushResult(context, GoodsRouter.goodsEditPage, (result) {
    // refresh
});
```

added successfully：

```dart
NavigatorUtils.goBackWithParams(context, goodsInfo);
```

or ：https://github.com/simplezhli/flutter_deer/issues/33


keep scroll position ：Extend AutomaticKeepAliveClientMixin override wantKeepAlive to true

```dart
class GoodsListState extends State<GoodsList> with AutomaticKeepAliveClientMixin {

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Container();
  }

  @override
  bool get wantKeepAlive => true;
}
```

**Comment by bctechjsc** [comment]
Cool, it works. Thanks you!
