### ISSUE TITLE
我们有交流群吗？

### ISSUE THREAD

**Issue by lchjczw** [simplezhli/flutter_deer#109]
我们有交流群吗？

**Comment by simplezhli** [comment]
@lchjczw 没有，没有精力管理。有问题就提issus吧。

**Comment by lchjczw** [comment]
正在阅读源码，实际上简单的问题，没好意思在issue上问，要是有个群，人多，有问题，也不一定你自己来回答，还有其他群成员，我是想好好看下，给这个项目写个代码生成器，每个新页面生成基本的骨架，直接写业务逻辑和界面就快多了

**Comment by lchjczw** [comment]
如果你确实没时间，要不然我建个群， @simplezhli 拉你做其中一个管理员如何？

**Comment by lchjczw** [comment]
到时候做一个基础分支，拉下来就可以直接做的，而不需要在现在的基础上在修改，就是我们开始把项目做成一个小框架，以后主要维护和修复其中的一些bug，这样以后项目以这个为基础，基础框架的bug也就越来越少，wiget添加越来越多，熟悉了，开发速度应该会很快 @simplezhli 你觉得怎么样

**Comment by simplezhli** [comment]
@lchjczw 想法很好，我会尽力支持你的。群的事情交给你了。

**Comment by lchjczw** [comment]
OK，我一会儿建好微信群，发二维码

**Comment by lchjczw** [comment]
![微信群](https://raw.githubusercontent.com/lchjczw/flutter_deer/master/preview/WeChatGroup.jpeg)
如果打不开，直接复制链接`https://raw.githubusercontent.com/lchjczw/flutter_deer/master/preview/WeChatGroup.jpeg`

**Comment by dxjdqc** [comment]
> ![微信群](https://camo.githubusercontent.com/ab77d9b6d391bd4666ce62b7f945a878e44188a0/68747470733a2f2f757365722d676f6c642d63646e2e786974752e696f2f323032302f342f32302f313731393662333039323137626263343f773d3130383026683d3231303926663d706e6726733d313832303539)
> 如果打不开，直接复制链接`https://user-gold-cdn.xitu.io/2020/4/20/17196b309217bbc4?w=1080&h=2109&f=png&s=182059`

码过期，链接打不开

**Comment by simplezhli** [comment]
交流群暂时停止加入

**Comment by simplezhli** [comment]
限时限量加入。

![Screenshot_2020-06-06-08-58-49-842_com tencent mm](https://user-images.githubusercontent.com/12456431/83932339-66556800-a7d4-11ea-8bae-327445865a11.jpg)

**Comment by sbigtree** [comment]
为什么不是qq群呢，微信群好麻烦
