### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by 309791679** [simplezhli/flutter_deer#111]
老哥写东西是一点注释没有啊，各种组件嵌套，有的还不放在一个目录下

**Comment by 309791679** [comment]
就单添加商品那个页面，我都缕了半小时了，单一个联动分了貌似3个页面，每一个里面还嵌入了好多组件，咱能不能改改，太难了

**Comment by simplezhli** [comment]
@309791679 我只给我认为关键的部分添加注释，其他都是一些widget的普通用法。至于目录问题，我是将页面和组件分开放，我并不认为不好。如果对你造成困扰，我很抱歉。可能这个项目不适合你。
