### ISSUE TITLE
app进入首页不自动跳转

### ISSUE THREAD

**Issue by deleteNames** [simplezhli/flutter_deer#112]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 7`
- [x] 设备型号：如：`android虚拟机22和28，诺基亚X7`
- [x] 设备系统版本：如 `Android 9和android22和28`
- [x] Flutter 版本：如 `1.17.0-3.3.pre`

### 具体问题描述 ###
app进入首页不自动跳转

**Comment by simplezhli** [comment]
见 https://github.com/simplezhli/flutter_deer/issues/89
