### ISSUE TITLE
Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.

### ISSUE THREAD

**Issue by ruancaipu** [simplezhli/flutter_deer#113]
### Mac  ###

- [x] 电脑系统：如：`MacOS Catelin 10.15.4`
- [x] 设备系统版本：如 `Android 10`
- [x] Flutter 版本：Flutter 1.18.0-12.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision c2b7342ca4 (2 days ago) • 2020-05-06 23:16:03 +0800
Engine • revision 33d2367950
Tools • Dart 2.9.0 (build 2.9.0-5.0.dev 9c94f08410)

#
#### 异常日志 ####
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...                                              1.1s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A barcode_scan
      A flutter_2d_amap
      A sqflite
      - Flutter
      - flutter_plugin_android_lifecycle
      - image_picker
      - path_provider
      - path_provider_macos
      - shared_preferences
      - shared_preferences_macos
      - shared_preferences_web
      - url_launcher
      - url_launcher_macos
      - url_launcher_web
      - webview_flutter

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `barcode_scan` from `.symlinks/plugins/barcode_scan/ios`
    -> Fetching podspec for `flutter_2d_amap` from `.symlinks/plugins/flutter_2d_amap/ios`
    -> Fetching podspec for `flutter_plugin_android_lifecycle` from `.symlinks/plugins/flutter_plugin_android_lifecycle/ios`
    -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `path_provider_macos` from `.symlinks/plugins/path_provider_macos/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `shared_preferences_macos` from `.symlinks/plugins/shared_preferences_macos/ios`
    -> Fetching podspec for `shared_preferences_web` from `.symlinks/plugins/shared_preferences_web/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    -> Fetching podspec for `url_launcher_macos` from `.symlinks/plugins/url_launcher_macos/ios`
    -> Fetching podspec for `url_launcher_web` from `.symlinks/plugins/url_launcher_web/ios`
    -> Fetching podspec for `webview_flutter` from `.symlinks/plugins/webview_flutter/ios`

    Resolving dependencies of `Podfile`
    [!] Unable to find a specification for `AMap2DMap` depended upon by `flutter_2d_amap`

    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * mistyped the name or version.
     * not added the source repo that hosts the Podspec to your Podfile.

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:389:in `find_cached_set'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:165:in `search_for'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_by'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update

Error running pod install
Error launching application on iPhone 11 Pro Max.

**Comment by simplezhli** [comment]
@ruancaipu 根据提示，尝试使用`pod repo update` 或 `pod install --repo-update`。也可以在[iOS问题汇总](https://github.com/simplezhli/flutter_deer/blob/master/iOS%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB.md)中尝试寻找解决办法。

还有确保Flutter sdk与我使用的stable 1.17.0一致，以避免新版本带来的不兼容问题。

**Comment by ruancaipu** [comment]
所有方法都尝试过了 还是不行啊

**Comment by simplezhli** [comment]
@ruancaipu ios目录的Podfile文件中把第二行的platform :ios, '9.0'注释打开试试。

**Comment by ruancaipu** [comment]
还是同样的，折腾了几天了，新建的工程可以在ios虚拟机上跑起来

**Comment by simplezhli** [comment]
@ruancaipu 那我暂时也没好的办法了。。。

**Comment by ruancaipu** [comment]
嗯 我解决了就close

**Comment by simplezhli** [comment]
@ruancaipu 期待你的解决方法

**Comment by ruancaipu** [comment]
有突破了 哥  
 barcode_scan:
    git:
      url: https://github.com/simplezhli/flutter_barcode_reader.git
flutter_2d_amap:
    git:
      url: https://github.com/simplezhli/flutter_2d_amap.git
类似这样的就始终build错误。你这个是不是私有库啊？

**Comment by simplezhli** [comment]
不是私有库，只是依赖方式不同。

**Comment by ruancaipu** [comment]
我修改了source 'https://gitee.com/mirrors/CocoaPods-Specs.git'
pod install 等待很长时间就ok了

**Comment by simplezhli** [comment]
@ruancaipu 感谢你的反馈。

**Comment by ruancaipu** [comment]
大佬，XLog如果是swift怎么配置呀？
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method logD on channel x_log)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)

**Comment by simplezhli** [comment]
@ruancaipu 你的代码是什么时候的？xlog已经去除了，现在log打印使用纯dart的方式了。

**Comment by ruancaipu** [comment]
我刚刚重新拉了代码 感谢大佬 哪个讨论群邀请码失效了 能拉我么，一起学习

**Comment by simplezhli** [comment]
@ruancaipu 其实不准备再进人了。。。以后有空位了优先留个你。

**Comment by ruancaipu** [comment]
👌谢谢

**Comment by simplezhli** [comment]
@ruancaipu https://github.com/simplezhli/flutter_deer/issues/109

**Comment by huoda1237** [comment]
执行完pod repo update以后，将podfile.lock删除，然后重新执行就可以了
