### ISSUE TITLE
关于 Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences) 错误的解决办法

### ISSUE THREAD

**Issue by mrchenmo** [simplezhli/flutter_deer#115]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 10`
- [x] Flutter 版本：1.17如 `1.12.13+hotfix.9`

#### 异常日志 ####
由于SpUtil基于shared_preferences: ^0.5.7+2的封装，shared_preferences官方文档指出测试环境下需要添加SharedPreferences.setMockInitialValues({});，所以需要在项目中引入 shared_preferences: ^0.5.7+2在main中添加上面那句话，即可解决

**Comment by simplezhli** [comment]
@mrchenmo 这里的测试环境指的是单元测试。。。而debug模式下运行这并不是指测试环境。这个方法的目的也是为了mock数据用的。回到这个问题，这个错误是deer最新的代码报的吗？

**Comment by simplezhli** [comment]
我看了一下`setMockInitialValues`的源码，它是将`_completer`置为null，这样在`SharedPreferences.getInstance()`中就跳过了`_store.getAll`的调用。这也就是你发现问题解决的原因。但这样做你的数据只是在内存中保存，并不会在磁盘保存。也就是sp无效。
```java
static Future<SharedPreferences> getInstance() async {
    if (_completer == null) {
      _completer = Completer<SharedPreferences>();
      try {
        final Map<String, Object> preferencesMap =
            await _getSharedPreferencesMap();
        _completer.complete(SharedPreferences._(preferencesMap));
      } on Exception catch (e) {
        // If there's an error, explicitly return the future with an error.
        // then set the completer to null so we can retry.
        _completer.completeError(e);
        final Future<SharedPreferences> sharedPrefsFuture = _completer.future;
        _completer = null;
        return sharedPrefsFuture;
      }
    }
    return _completer.future;
  }

```

**Comment by mrchenmo** [comment]
> 我看了一下`setMockInitialValues`的源码，它是将`_completer`置为null，这样在`SharedPreferences.getInstance()`中就跳过了`_store.getAll`的调用。这也就是你发现问题解决的原因。但这样做你的数据只是在内存中保存，并不会在磁盘保存。也就是sp无效。
> 
> ```java
> static Future<SharedPreferences> getInstance() async {
>     if (_completer == null) {
>       _completer = Completer<SharedPreferences>();
>       try {
>         final Map<String, Object> preferencesMap =
>             await _getSharedPreferencesMap();
>         _completer.complete(SharedPreferences._(preferencesMap));
>       } on Exception catch (e) {
>         // If there's an error, explicitly return the future with an error.
>         // then set the completer to null so we can retry.
>         _completer.completeError(e);
>         final Future<SharedPreferences> sharedPrefsFuture = _completer.future;
>         _completer = null;
>         return sharedPrefsFuture;
>       }
>     }
>     return _completer.future;
>   }
> ```

sp确实是不起作用了，这段代码就进不去app，我没有用最新的代码，因为我改了东西。我直接升级FlutterSDK 以后就一直报错。

**Comment by mrchenmo** [comment]
@simplezhli 我看了之前的issues 也没解决报错的问题啊

**Comment by mrchenmo** [comment]
@simplezhli 我对比了最新的代码和我本地的代码SplashPage这里并没有什么变化，我打算把SDK升级到1.17.1试试

**Comment by simplezhli** [comment]
@mrchenmo 其实之前的issues已经提到了，你对比一下 `MainActivity`

**Comment by mrchenmo** [comment]
> @mrchenmo 其实之前的issues已经提到了，你对比一下 `MainActivity`

![image](https://user-images.githubusercontent.com/18020929/82290353-4c94e200-99d9-11ea-8313-20859db24f0e.png)
这是我本地的

**Comment by simplezhli** [comment]
这是最新的：

```java
public class MainActivity extends FlutterActivity {

  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    super.configureFlutterEngine(flutterEngine);
    flutterEngine.getPlugins().add(new InstallAPKPlugin(this));
  }
}
```

**Comment by mrchenmo** [comment]
> 这是最新的：
> 
> ```java
> public class MainActivity extends FlutterActivity {
> 
>   @Override
>   public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
>     super.configureFlutterEngine(flutterEngine);
>     flutterEngine.getPlugins().add(new InstallAPKPlugin(this));
>   }
> }
> ```
> 
> 修改log：weilu 2020-5-7-0007 11:31 Flutter version 1.17.0

 super.configureFlutterEngine(flutterEngine);加上这句话好了，这是为什么呢？大佬

**Comment by simplezhli** [comment]
之前的issues已经说过了：https://github.com/simplezhli/flutter_deer/issues/89#issuecomment-581758782  

只是在新的Flutter版本中，这个在`onCreate`中已经去除了，放在了`configureFlutterEngine`中。

我会时不时的修改调整代码，以保证它可以良好的支持稳定版。如果你不拉新的代码，可以去看我的提交记录。如果你用的老代码，我不能保证没有问题，可能你碰到的问题我已经解决过了。

**Comment by mrchenmo** [comment]
> 之前的issues已经说过了：[#89 (comment)](https://github.com/simplezhli/flutter_deer/issues/89#issuecomment-581758782)
> 
> 只是在新的Flutter版本中，这个在`onCreate`中已经去除了，放在了`configureFlutterEngine`中。
> 
> 我会时不时的修改调整代码，以保证它可以良好的支持稳定版。如果你不拉新的代码，可以去看我的提交记录。如果你用的老代码，我不能保证没有问题，可能你碰到的问题我已经解决过了。

好的，麻烦 close吧，谢谢。

**Comment by mrchenmo** [comment]
@simplezhli 在 Flutter 1.12 开始 Flutter 团队调整了 Android 插件的实现代码，在 1.12 之后 Android 开始使用新的插件 API ，基于的旧的 PluginRegistry.Registrar 不会立即被弃用，但官方建议迁移到基于的新API FlutterPlugin ，另外新版本官方建议插件直接使用 Androidx 支持，官方提供的插件也已经全面升级到  Androidx。
是不是因为这个升级导致的。

**Comment by simplezhli** [comment]
@mrchenmo 1.12就改了，这个问题1.12不存在。你说呢？
