### ISSUE TITLE
iOS无法运行，改了pods仓库地址也不行

### ISSUE THREAD

**Issue by yinminang** [simplezhli/flutter_deer#116]
### 运行环境 ###

- [x] 电脑系统：MAC
- [x] 设备型号：SE simulator
- [x] 设备系统版本：iOS 13.3
- [x] Flutter 版本：1.12.13+hotfix.9

### 具体问题描述 ###
项目无法运行，iOS项目cocoapods 改了仓库无效
#### 异常日志 ####
Cloning spec repo `edu-git-cocoapods-specs` from
    `https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git`
      $ /usr/bin/git clone https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git --
      edu-git-cocoapods-specs
    [!] Unable to add a source with url `https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git` named
    `edu-git-cocoapods-specs`.
    (/usr/bin/git clone https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git --
    edu-git-cocoapods-specs

    Cloning into 'edu-git-cocoapods-specs'...
    fatal: the remote end hung up unexpectedly
    fatal: early EOF
    fatal: index-pack failed
    )

**Comment by simplezhli** [comment]
@yinminang 这个镜像可能失效了，试试`https://github.com/CocoaPods/Specs.git`，同时host添加`199.232.4.133 raw.githubusercontent.com`

**Comment by simplezhli** [comment]
刚看了一下清华的镜像正常，https://mirrors.tuna.tsinghua.edu.cn/help/CocoaPods/
