### ISSUE TITLE
iOS pod install 出现异常

### ISSUE THREAD

**Issue by limebinary** [simplezhli/flutter_deer#117]
[!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

    [!] 'AMap2DMap' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts. Otherwise, please reach out to the library author to notify them of this security issue.

    [!] 'AMapSearch' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts. Otherwise, please reach out to the library author to notify them of this security issue.

跟更新的barcode_scan: 3.0.1有关，替换回原来的扫描插件则恢复正常。

**Comment by simplezhli** [comment]
@limebinary 感谢反馈，确实是这个插件导致的，这块我更换后忘记测了。我尝试修改，发现了许多问题：

```
The Swift pod `barcode_scan` depends upon `MTBBarcodeScanner`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

The 'Pods-Runner' target has transitive dependencies that include statically linked binaries

xcodebuild: error: Scheme Runner is not currently configured for the build action.
  Command: /usr/bin/env xcrun xcodebuild -configuration Debug -quiet -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/weilu/Downloads/flutter_deer/build/ios -sdk iphonesimulator -arch x86_64 FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
```

我暂时将这部分回退，后面再排查具体问题。

**Comment by limebinary** [comment]
感谢回复。既然已经回退，这个issue就先关了。
