### ISSUE TITLE
运行iOS的时候安装不了AMap2DMap、AMapSearch这两个库

### ISSUE THREAD

**Issue by Hjt830** [simplezhli/flutter_deer#121]
### 运行环境 ###

- [x] 电脑系统：如：`Mac  10.15.4`
- [x] 设备型号：如：`iPhone 11 Pro Max 模拟器`
- [x] 设备系统版本：如 `iOS 13.3`
- [x] Flutter 版本：如 `1.19.0-2.0.pre.114`

### 具体问题描述 ###
运行到iOS模拟器的时候，AMap2DMap、AMapSearch这两个库安装不了，我按照了iOS问题汇总来尝试解决问题，但是没有用
#### 问题截图  ####
![image](https://user-images.githubusercontent.com/13915006/82629809-6f1a3b80-9c23-11ea-8aaf-eefd8af85cae.png)

#### 异常日志 ####
[!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no
    platform was specified. Please specify a platform for this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

    [!] 'AMap2DMap' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in
    a safe network with only trusted hosts. Otherwise, please reach out to the library author to
    notify them of this security issue.

    [!] 'AMapSearch' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're
    in a safe network with only trusted hosts. Otherwise, please reach out to the library author to
    notify them of this security issue.

Error running pod install
Error launching application on iPhone 11 Pro Max.

**Comment by simplezhli** [comment]
@Hjt830 你这个不是错误信息，只是警告。可以忽略。

**Comment by simplezhli** [comment]
iOS运行不起来，大都是网络问题（也可能和kaihui有关）。如果`source 'https://github.com/CocoaPods/Specs.git'`加host配置都无效。我也爱莫能助了。

还有我感觉你的代码也不是最新的。。。

**Comment by Hjt830** [comment]
我昨天从git上面拉下来的，我也觉得有可能是网络问题，用tinghua镜像也下载不下来，远程连接一场场导致断开
