### ISSUE TITLE
common_utils升级，DataFormats 名称更改的问题

### ISSUE THREAD

**Issue by ansonhorse** [simplezhli/flutter_deer#125]
### 运行环境 ###
- [x] Flutter 版本：如 `1.17.1`

### 具体问题描述 ###
`common_utils` 更改了类名 `DataFormats` -> `DateFormats`
https://github.com/Sky24n/common_utils/blob/8efc2e42f639c1f66f86ea41d7a8670d5d6fd408/CHANGE_LOG.md#v121-20200529

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/7548142/83332392-8d400580-a2cd-11ea-9276-9005f6c62d0b.png)

**Comment by simplezhli** [comment]
了解，我随后修改一下。common_utils最近有几次破坏性的升级，我之后固定一下版本号吧。。。
