### ISSUE TITLE
这个掘金号是你的吗？鹿哥https://juejin.im/post/5edf70fee51d4578702f5ebe

### ISSUE THREAD

**Issue by mrchenmo** [simplezhli/flutter_deer#127]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 10`
- [x] Flutter 版本：如 `1.17.2`

**Comment by simplezhli** [comment]
@mrchenmo 不是，我早上看到了这篇文章。还评论了一下，刚看还给我删了。。。

**Comment by simplezhli** [comment]
已经给掘金反馈了，文章已删除。
