### ISSUE TITLE
如何登录？

### ISSUE THREAD

**Issue by mutu123** [simplezhli/flutter_deer#13]
验证码发生到哪里去了？

**Comment by simplezhli** [comment]
@mutu123  并没有什么接口。。。，随意填数据就行。主要还是UI的实现。

**Comment by mutu123** [comment]
登录按钮点击没反应，跳转不了ರ_ರ 心塞




| |
杜康
邮箱：15527660071@163.com
|

签名由 网易邮箱大师 定制

在2019年07月05日 15:24，唯鹿 写道：

@mutu123 并没有什么接口。。。，随意填数据就行。主要还是UI的实现。

**Comment by simplezhli** [comment]
@mutu123  我做了简单的数据校验，用户名需要输入11位数字，密码大于6位。你可以翻翻代码都可以解决这些问题。

**Comment by mutu123** [comment]
好的，代码还没看，只是下载你的app，期待你的后续，加油💪




| |
杜康
邮箱：15527660071@163.com
|

签名由 网易邮箱大师 定制

在2019年07月05日 16:50，唯鹿 写道：

@mutu123 我做了简单的数据校验，用户名需要输入11位数字，密码大于6位。你可以翻翻代码都可以解决这些问题。

**Comment by simplezhli** [comment]
感谢支持！
