### ISSUE TITLE
店铺页面添加图标之后溢出问题

### ISSUE THREAD

**Issue by kvii2202** [simplezhli/flutter_deer#130]
# 描述
**想在页面中添加图标，但是发现格子溢出了** 图片如下👇

![无标题](https://user-images.githubusercontent.com/56432636/84717950-f9975600-afa9-11ea-93f8-14de4117e120.png)
----
**尝试在 column 组件外嵌套可滚动组件来解决问题，但是会报错。如何去解决这个问题？**
> 报错信息
The following assertion was thrown during performLayout():
RenderFlex children have non-zero flex but incoming height constraints are unbounded.
When a column is in a parent that does not provide a finite height constraint, for example if it is
in a vertical scrollable, it will try to shrink-wrap its children along the vertical axis. Setting a
flex on a child (e.g. using Expanded) indicates that the child is to expand to fill the remaining
space in the vertical direction.
These two directives are mutually exclusive. If a parent is to shrink-wrap its child, the child
cannot simultaneously expand to fit its parent.
Consider setting mainAxisSize to MainAxisSize.min and using FlexFit.loose fits for the flexible
children (using Flexible rather than Expanded). This will allow the flexible children to size
themselves to less than the infinite remaining space they would otherwise be forced to take, and
then will cause the RenderFlex to shrink-wrap the children rather than expanding to fit the maximum
constraints provided by the parent.

**Comment by simplezhli** [comment]
@kvii2202 添加`SingleChildScrollView`，去除`Flexible`。

**Comment by kvii2202** [comment]
爱你么么哒
