### ISSUE TITLE
Unable to find a specification for `MTBBarcodeScanner`

### ISSUE THREAD

**Issue by think-you** [simplezhli/flutter_deer#131]
### 运行环境 ###

- [x] 电脑系统：如：`macOS Catalina`
- [x] 设备型号：如：`MBP 15.4`
- [x] 设备系统版本：10.15.5
- [x] Flutter 版本： `1.17.2`

### 具体问题描述 ###
Unable to find a specification for `MTBBarcodeScanner`

**Comment by simplezhli** [comment]
@think-you 更新一下repo试试`pod repo update`

**Comment by simplezhli** [comment]
看看`pod search MTBBarcodeScanner` 可以搜到吗？实在不行执行一下`pod install --verbose`，看一下详细错误信息。

**Comment by think-you** [comment]
是我环境的问题，谢谢
