### ISSUE TITLE
你好请问fluro里面怎么封装页面跳转动画

### ISSUE THREAD

**Issue by longzc1314** [simplezhli/flutter_deer#132]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 10`
- [x] Flutter 版本：如 `1.17.2`

**Comment by simplezhli** [comment]
@longzc1314 `navigateTo`的`transition`属性设为`TransitionType.custom`，同时实现`transitionBuilder`就行了。话说这个问题不应该去看看fluro源码或是在fluro底下问吗？

**Comment by longzc1314** [comment]
谢谢你  Application.router.navigateTo(context, path,
        replace: replace,
        clearStack: clearStack,
        transition: TransitionType.inFromBottom);  直接这里设置transition好像是无效的 我用另一种方式 处理 也是设置这个值是可以的  你这个项目要去实现transitionBuilder是吧

**Comment by simplezhli** [comment]
@longzc1314 我尝试设置`TransitionType.inFromBottom`是有效的，自下而上的进入页面。

**Comment by longzc1314** [comment]
你好刚试了在home去跳转的时候是可以的 但从登陆也到home页面好像是不生效的 我再看看 谢谢你 打扰了

**Comment by simplezhli** [comment]
@longzc1314 进Home页使用了`clearStack`，所以是没有过渡效果。
