### ISSUE TITLE
你好 请问下 网络请求回来的数据最外层的code跟data是框架自带的是吗

### ISSUE THREAD

**Issue by longzc1314** [simplezhli/flutter_deer#133]
{"code":0,"data":{"exceptionCode":"500","exceptionMsg":"账号或密码不正确","bizContent":null,"bebugMsg":""},"message":""}
这个是我请求返回的数据，我需要自己再把data返回的数据在解析判断一次是吧。还是可以直接替换成最外层的code跟data

**Comment by longzc1314** [comment]
BaseEntity.fromJson(Map<String, dynamic> json) {
    code = json[Constant.code] as int;
    message = json[Constant.message] as String;
    if (json.containsKey(Constant.data) &&
        json[Constant.data].containsKey(Constant.exceptionCode)) {
      if (json[Constant.data][Constant.exceptionCode] != "0") {
        data = null;
        code = int.parse(json[Constant.data][Constant.exceptionCode]);
        message = json[Constant.data][Constant.exceptionMsg];
      } else {
        Log.d("msg======$data");
        data = _generateOBJ<T>(json[Constant.data]);
      }
    }
  }
你好 我在这里去处理了 这样做可以吗

**Comment by simplezhli** [comment]
@longzc1314 不用这么麻烦，你的情况去除main.dart的`AdapterInterceptor`，将`BaseEntity`的code/message修改为你的exceptionCode/exceptionMsg就行了

**Comment by longzc1314** [comment]
好的 非常感谢你的指教，入门师傅
