### ISSUE TITLE
页面传值以后再获取网络请求

### ISSUE THREAD

**Issue by freedoem** [simplezhli/flutter_deer#135]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 10`
- [x] Flutter 版本：如 `1.17.2`

### 具体问题描述 ###
页面间传值后，进行网络请求，这个参数怎么能传入到presenter中。我在页面中的 initstate中接收参数，然后调用presenter的方法进行传值并网络请求，但是程序直接报错了。

**Comment by freedoem** [comment]
dependOnInheritedWidgetOfExactType<_InheritedTheme>() or dependOnInheritedElement() was called before _BiddingDetailPageState.initState() completed.
I/flutter (12531): When an inherited widget changes, for example if the value of Theme.of() changes, its dependent widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor or an initState() method, then the rebuilt dependent widget will not reflect the changes in the inherited widget.
I/flutter (12531): Typically references to inherited widgets should occur in widget build() methods. Alternatively, initialization based on inherited widgets can be placed in the didChangeDependencies method, which is called after initState and whenever the dependencies change thereafter.

**Comment by simplezhli** [comment]
见：https://weilu.blog.csdn.net/article/details/94849020  第三点

**Comment by freedoem** [comment]
嗯啊，谢大神回复，之前看到过这段代码。现在的问题是，从上个页面传过来的参数，怎么传入到preseter中。addfirst 调用第一帧发送网络请求，但参数不知道什么时候传入进去。初学者，见谅。

**Comment by freedoem** [comment]
void initState() {
    LogUtil.e('我是页面的initState');
    super.initState();
     Map argument=widget.argument;
     if(argument!=null&&argument.isNotEmpty){
       if(argument.containsKey('id')){
         id = widget.argument['id'];
       //  _biddingDetailPresenter.setParams(id);

          _biddingDetailPresenter.postBiddingDetailRequest(id);
       }
     }

**Comment by freedoem** [comment]
//  String id;
//   void setParams(String carId){
//      id=carId;
//   }

    @override
  void initState() {
    super.initState();
    LogUtil.e('我是presenter的initState');
//    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
//
//       postBiddingDetailRequest(id);
//    });
  }


  postBiddingDetailRequest(String carId) {
    Map<String, String> params = Map();
    params['id'] = carId;
    asyncRequestNetwork<BiddingDetailModelEntity>(
      Method.post,
      url: HttpApi.bidding_detail,
      params: params,
      onSuccess: (data) {
         view.setBiddingDetail(data);
      },
    );

  }

**Comment by simplezhli** [comment]
@freedoem 项目中的shop_page.dart和shop_presenter.dart就是这样的一个例子。

**Comment by freedoem** [comment]
嗯啊，看到了，shop_page里面的例子是房子presenter中的addfirst中的，现在我的解决方式是放在页面初始化的addfirst中。思维惯性，多有打扰，抱歉哈

**Comment by simplezhli** [comment]
都可以，按照自己的习惯来就好。那我就关闭这个issue了？

**Comment by freedoem** [comment]
想友情赞助下，没找到地方啊
