### ISSUE TITLE
有没有开个视频， 讲讲这个项目

### ISSUE THREAD

**Issue by TrumpUSA** [simplezhli/flutter_deer#136]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 10`
- [x] Flutter 版本：如 `1.17.2`

**Comment by simplezhli** [comment]
精力有限，没有相关视频。可以关注我的博客，里面关于Flutter方面的基本都来自这个项目。

**Comment by happy-sw** [comment]
你的博客链接呢

**Comment by simplezhli** [comment]
@happy-sw 其实README中有，我再贴一下吧。https://blog.csdn.net/qq_17766199/category_9026839.html
