### ISSUE TITLE
keyboard_actions国内镜像貌似无法下载

### ISSUE THREAD

**Issue by JokerLoLgrey** [simplezhli/flutter_deer#139]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`

### 具体问题描述 ###
keyboard_actions国内镜像貌似无法下载

#### 问题截图 ####

![image](https://user-images.githubusercontent.com/33446705/87775594-f3babc00-c858-11ea-9b15-fe939402099f.png)

**Comment by simplezhli** [comment]
@JokerLoLgrey 不是下载问题，是3.3.0有破坏性升级，你可以根据它的文档修改或者暂时使用3.2.1+1。

**Comment by JokerLoLgrey** [comment]
> @JokerLoLgrey 不是下载问题，是3.3.0有破坏性升级，你可以根据它的文档修改或者暂时使用3.2.1+1。后面我会提交修改后的代码。

ok,版本锁定解决了

**Comment by simplezhli** [comment]
修改代码已提交。
