### ISSUE TITLE
页面弹出遮罩略有延迟

### ISSUE THREAD

**Issue by bigbirdhzp** [simplezhli/flutter_deer#14]
进入APP后，我点击底部“店铺”Tab，然后点击右上角的闹铃Icon，发现弹出的遮罩有延迟。
我的测试机器是红米Note-7，MIUI 10 9.7.4|开发版，安卓版本为9。flutter版本为1.5.4-hotfix.2
具体表现为：刚弹出遮罩的时候，还会看到原来底部的页面，如下图所示：
![image](https://user-images.githubusercontent.com/22903159/60777999-adbc1a00-a167-11e9-8381-36ee29a26083.png)

**Comment by simplezhli** [comment]
你试试release版本有没有同样问题，debug模式下的性能问题没有参考意义。https://www.pgyer.com/gYXj

**Comment by bigbirdhzp** [comment]
> 你试试release版本有没有同样问题，debug模式下的性能问题没有参考意义。https://www.pgyer.com/gYXj

感谢指导。在release下没有问题。
