### ISSUE TITLE
How can I rebuild current Page

### ISSUE THREAD

**Issue by bctechjsc** [simplezhli/flutter_deer#140]
Hello, I have a problem. I want to have scan button such as image below:
<img width="377" alt="Screen Shot 2020-07-28 at 13 52 04" src="https://user-images.githubusercontent.com/61673430/88629552-97b62a00-d0d9-11ea-9068-61ed0372d748.png">
When I have finished QR code. I want to reload current Page. But It's not working. How can I do it?
<img width="696" alt="Screen Shot 2020-07-28 at 13 50 52" src="https://user-images.githubusercontent.com/61673430/88629654-c16f5100-d0d9-11ea-805c-79c0f107f26f.png">
Thanks you!

### 运行环境 ###

- [x] 电脑系统：如：`MacOS`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 10`
- [x] Flutter 版本：如 `1.17.2`

**Comment by simplezhli** [comment]
Try the [event_bus](https://github.com/marcojakob/dart-event-bus).
