### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by gonghui91** [simplezhli/flutter_deer#141]
### 运行环境 ###

- [x] 电脑系统：如：`macos`
- [x] Flutter 版本：如 `1.17.5`

### 具体问题描述 ###
 请教一下，您放在平台上的apk才10M，我用您的源码build有25M

**Comment by simplezhli** [comment]
默认打包会存在 android-arm, android-arm64, android-x64三种平台，我是指定了`android-arm`一种进行打包。如：
`flutter build apk --target-platform android-arm --split-per-abi --no-shrink`

**Comment by pangteman** [comment]
牛哇牛哇,作者牛哇!!!
