### ISSUE TITLE
Util下的utils里面定义的两个WidgetBuilder报错，keyboard_actions升级到3.3.0+1

### ISSUE THREAD

**Issue by mrchenmo** [simplezhli/flutter_deer#142]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 10`
- [x] Flutter 版本：如 `1.17.2`

#### 异常日志 ####

lib/util/utils.dart:7:1: Error: 'WidgetBuilder' is imported from both 'package:flutter/src/widgets/framework.dart' and 'package:keyboard_actions/keyboard_custom.dart'.
import 'package:keyboard_actions/keyboard_actions.dart';

hide 掉keyboard_actions里面的WidgetBuilder就好了

**Comment by simplezhli** [comment]
@mrchenmo 之前已经升了3.3.0+1，请拉取最新代码。

**Comment by maomao1020** [comment]
AMapSearchKit 版本 7.4.0+sea.a8f44f2 提示/Users/jerry/.pub-cache/git/flutter_2d_amap-323fcf8203d89a4235f923a1b53ae1e455c9afb3/ios/Classes/FlutterAMap2D.m:13:9: 'AMapSearchKit/AMapSearchKit.h' file not found
