### ISSUE TITLE
AMapSearchKit/AMapSearchKit.h' file not found

### ISSUE THREAD

**Issue by maomao1020** [simplezhli/flutter_deer#143]
### 运行环境 ###

- [x] 电脑系统：如：`mac`
- [x] 设备型号：如：` 模拟器`
- [x] 设备系统版本：如 `Iphone SE`
- [x] Flutter 版本：如 `1.20.0`

### 具体问题描述 ###
AMapSearchKit/AMapSearchKit.h' file not found
#### 异常日志 ####
AMapSearchKit 版本 7.4.0+sea.a8f44f2 提示/Users/jerry/.pub-cache/git/flutter_2d_amap-323fcf8203d89a4235f923a1b53ae1e455c9afb3/ios/Classes/FlutterAMap2D.m:13:9: 'AMapSearchKit/AMapSearchKit.h' file not found

**Comment by simplezhli** [comment]
建议先尝试清除缓存重试：

flutter clean
删除ios目录下的 Podfile.lock和Pods
pod deintegrate
pod repo update
最后重新运行安装
