### ISSUE TITLE
运行测试命令时，`Command PhaseScriptExecution failed with a nonzero exit code`报错

### ISSUE THREAD

**Issue by lawlietwind** [simplezhli/flutter_deer#144]
### 运行环境 ###

- [x] 电脑系统：如：`macOS 10.15.6 `
- [x] 设备型号：如：`iOS模拟器iPhone 11 Pro Max`
- [x] 设备系统版本：如 `iOS13.6`
- [x] Flutter 版本：如 `1.20.0`

### 具体问题描述 ###

在iOS、Android虚拟机以及iOS真机中运行测试`flutter drive --profile --target=test_driver/driver.dart`进行测试。报出如下错误`Command PhaseScriptExecution failed with a nonzero exit code`，无法启动app进行测试。

#### 问题截图 ####

![image](https://user-images.githubusercontent.com/13810063/91703091-41427c80-ebac-11ea-862d-e13746eb2ee7.png)

#### 尝试过的方法 ####

- 更换过Xcode中的build system。`无效`
-  使用安卓虚拟机以及iOS真机运行。`无效`
-  使用`flutter clean`清理缓存。`无效`

**Comment by simplezhli** [comment]
@lawlietwind 尝试去除`--profile `，使用`flutter drive --target=test_driver/driver.dart`测试。我本地和[Github Actions](https://github.com/simplezhli/flutter_deer/actions/runs/228069630)暂没发现这个问题。

**Comment by simplezhli** [comment]
flutter issus 搜到了此类[问题](https://github.com/flutter/flutter/issues?q=Command+PhaseScriptExecution+failed+with+a+nonzero+exit+code)，可以尝试master分支看是否已修复。

**Comment by lawlietwind** [comment]
> @lawlietwind 尝试去除`--profile `，使用`flutter drive --target=test_driver/driver.dart`测试。我本地和[Github Actions](https://github.com/simplezhli/flutter_deer/actions/runs/228069630)暂没发现这个问题。

去掉`--profile`暂时可以使用
