### ISSUE TITLE
版本不兼容改如何处理

### ISSUE THREAD

**Issue by liuweitao2** [simplezhli/flutter_deer#145]
大神，我是新手，想学习一下你的项目
可是报各种不兼容我该如何处理

===========================================
The current Flutter SDK version is 0.0.0-unknown.

Because flutter_deer depends on flutter_swiper any which requires Flutter SDK version >=0.1.4 <3.0.0, version solving failed.
pub get failed (1; Because flutter_deer depends on flutter_swiper any which requires Flutter SDK version >=0.1.4 <3.0.0, version solving failed.)
exit code 1

===========================================
![image](https://user-images.githubusercontent.com/41280799/92064405-0456cf80-edd0-11ea-9bbb-84967d324530.png)

全是红的

**Comment by simplezhli** [comment]
`The current Flutter SDK version is 0.0.0-unknown.`，说明无法正常获取sdk版本，检查你的环境配置。根据官网文档一步步来。https://flutter.cn/docs/get-started/install
