### ISSUE TITLE
[建议] app 应用版本问题

### ISSUE THREAD

**Issue by kvii2202** [simplezhli/flutter_deer#146]
# 关于 app 引用版本配置的建议

项目中的模块级 [build.gradle](https://github.com/simplezhli/flutter_deer/blob/master/android/app/build.gradle) 下有这么一段儿

``` gradle
def flutterVersionCode = '14'
def flutterVersionName = '1.1.3'
```
上面代码指定了当前给用户显示的版本和判断是否需要更新的版本

而在 `flutter` 默认创建的 `build.gradle` 中是这样的

```gradle
def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}
```

上面代码读取了 `android\local.properties` 中的存放的版本信息

去查了一下，发现只要在 [pubspec.yaml](https://github.com/simplezhli/flutter_deer/blob/master/pubspec.yaml "项目配置文件") 中配置 `version: 1.0.0+1` 就能直接生成版本信息，不需要手动维护了。

也就是说，在使用 `version: 1.0.0+1` 的配置之后。
运行 `flutter build apk`  会直接在 `android\local.properties`  中生成项目所需要的配置

```properties
省略无关代码……
flutter.versionName=1.0.0
flutter.versionCode=1
```

请问在项目中直接配置版本信息是有什么深意吗？感觉直接写在 `pubspec.yaml` 中更方便一点儿。

---
另：安卓的壳工程不考虑使用 `android studio` 把 `java` 代码直接转换成 `kotlin` 代码？

**Comment by simplezhli** [comment]
@kvii2202 感谢你的建议。这个项目是一年多以前创建的，不知道是我的操作问题还是bug，当时版本信息无法正确生成生效，所以当时就一直手动维护了。（现在已经正常，我会改回来的）
java代码的问题其实一样，当时创建项目默认是只有 java和object c。不过这个并没有太大影响，相较来说，java和object c接受度还是高一点。暂时保持原样，有需要的可以自己用as转换。
