### ISSUE TITLE
找到一段 kuso 代码逻辑

### ISSUE THREAD

**Issue by kvii2202** [simplezhli/flutter_deer#147]
在 [intercept.dart](https://github.com/simplezhli/flutter_deer/blob/master/lib/net/intercept.dart "186行") 的第 186 行有这么一段：
``` dart
// 401 token失效时，单独处理，其他一律为成功
if (response.statusCode == ExceptionHandle.unauthorized) { // <- 看这里
  response.statusCode = ExceptionHandle.unauthorized;
} else {
  response.statusCode = ExceptionHandle.success;
}
```

若 `statusCode` 等于 `unauthorized` 就把它赋值成 `unauthorized`……
我想应该是大佬一时手滑了。改一下比较好。
``` dart
// 401 token失效时，单独处理，其他一律为成功
if (response.statusCode != ExceptionHandle.unauthorized) {
  response.statusCode = ExceptionHandle.success;
} /* else 逻辑写在这里 */
```
---
另：就为了一个 `if` 语句提交 pr 确实有点不值得，只能期望大佬抽时间改下了。

**Comment by simplezhli** [comment]
@kvii2202 这段是我项目中的一个处理，并不适用所有场景。这个拦截器也是选择添加的。
