### ISSUE TITLE
出现好多异常啊。。

### ISSUE THREAD

**Issue by Sing1** [simplezhli/flutter_deer#149]
![image](https://user-images.githubusercontent.com/15246585/94554192-4fa7b500-028c-11eb-9832-e4450ab4dae4.png)

**Comment by Sing1** [comment]
![image](https://user-images.githubusercontent.com/15246585/94554275-6fd77400-028c-11eb-9db2-9cd21534e7be.png)

**Comment by Sing1** [comment]
![image](https://user-images.githubusercontent.com/15246585/94554524-c775df80-028c-11eb-833f-8b856e7403b8.png)

**Comment by Sing1** [comment]
这对一个新手来说学起来太难了，是因为升级某些版本导致的吗

**Comment by Sing1** [comment]
应该是环境的版本问题，
Flutter channels:
  beta
  dev
  master
* stable



请问大佬你的是那个环境下的版本？

**Comment by simplezhli** [comment]
@Sing1 先确保你的flutter 版本是否和我的一致，请仔细看README。而且我的项目也不适合新手。建议先掌握基础Widget的用法。

**Comment by jiunwu** [comment]
試著把 
pubspec.yaml

environment:
  sdk: ">=2.7.0 <3.0.0"

改成

sdk: ">=2.8.0 <3.0.0"
之後就沒有異常了
