### ISSUE TITLE
Global Provider Error

### ISSUE THREAD

**Issue by FitzMusk** [simplezhli/flutter_deer#153]
When I am trying to move ``` ChangeNotifierProvider<BaseListProvider<SearchItem>>(
      create: (_) => provider,``` from ```order_search_page.dart``` to ```main.dart```. I cannot get any data but loading state on order_search_page. could you tell me the reason and what can I do? Thanks in advance!

**Comment by simplezhli** [comment]
Can you describe your operation in detail

**Comment by FitzMusk** [comment]
Sure. I do this for I tend to put ```consumer``` of ```ChangeNotifierProvider<BaseListProvider<SearchItem>>``` at another page (to share ```ChangeNotifierProvider<BaseListProvider<SearchItem>>```'s state), but this ''another page''' is under another widget tree. So I am considering put the ```ChangeNotifierProvider``` at ```main.dart```.

**Comment by FitzMusk** [comment]
Sure. I do this for I intend to put consumer of ChangeNotifierProvider<BaseListProvider<SearchItem>> at another page (to share ChangeNotifierProvider<BaseListProvider<SearchItem>>'s state), but this ''another page''' is under another widget tree. So I am considering put the ChangeNotifierProvider at main.dart.

**Comment by FitzMusk** [comment]
Sure. I do this for I intend to put consumer of ChangeNotifierProvider<BaseListProvider<SearchItem>> at another page (to share ChangeNotifierProvider<BaseListProvider<SearchItem>>'s state), but this ''another page''' is under another widget tree. So I am considering put the ChangeNotifierProvider at main.dart.

**Comment by FitzMusk** [comment]
For example, at ```main.dart```  ```ChangeNotifierProvider<ThemeProvider>``` woks fine as a global provider. However, when I added ```ChangeNotifierProvider<BaseListProvider<SearchItem>>``` at ```main.dart```, it's consumer doesn't work.

**Comment by simplezhli** [comment]
Can I have a look at the specific code

**Comment by FitzMusk** [comment]
thank for your reply.
Here is your code:
![90A55F9B-520D-469C-9E71-7034E8C46990](https://user-images.githubusercontent.com/43529681/97378036-557cce80-18fc-11eb-9b96-0fa37425cf13.png)
![EE2BF9C5-6359-4312-8377-A4192C5E7FDC](https://user-images.githubusercontent.com/43529681/97378037-57df2880-18fc-11eb-86a4-745a026bf4f6.png)
Here is your code after my change:
![71B0AB23-38A6-4559-B9BE-62DCE3422DFD](https://user-images.githubusercontent.com/43529681/97378065-675e7180-18fc-11eb-9951-ca492829b96e.png)
![C8EDF4A8-789F-478D-BEC5-60C102E62B38](https://user-images.githubusercontent.com/43529681/97378070-688f9e80-18fc-11eb-9e4f-2495da40de12.png)

**Comment by simplezhli** [comment]
![image](https://user-images.githubusercontent.com/12456431/97379862-ccb46180-1900-11eb-9487-7c73d9b530eb.png)

![image](https://user-images.githubusercontent.com/12456431/97380189-7d226580-1901-11eb-920e-63a5a4c42b33.png)


`view.provider` replaced with `baseListProvider`

**Comment by FitzMusk** [comment]
finally, it works!! Huge appreciation from here. I will thank u  in the app!! ;)
