### ISSUE TITLE
关于多语言在 APP 内切换问题

### ISSUE THREAD

**Issue by Rookie-liu** [simplezhli/flutter_deer#155]
### 感谢 ###
鹿神你好, 拜读了您的代码,收益良多 . 感觉您为想我这种菜鸟开源出来的思路以及解决办法

### 具体问题描述 ###

我这面确实有一个具体的问题, 现在您代码里面支持了中文和英文的多语言 , 现在系统切换的情况下也可以切换, 现在我的想要在 APP 中手动切换语言, 思考了许久也不知道怎么去根据您当前的代码去实现, 还求鹿神指点指点. 感谢.

**Comment by simplezhli** [comment]
整体思路和夜间模式一致，不同的是控制MaterialApp中的locale参数。我把具体的实现提交一下，你可以参考一下。

**Comment by Rookie-liu** [comment]
> 整体思路和夜间模式一致，不同的是控制MaterialApp中的locale参数。我把具体的实现提交一下，你可以参考一下。

首先感谢回复和修改的神速,
再次鹿神费神费力给我们出解决方案, 重新下载看多语言没有问题
最后想请问鹿神有没有交流群 或者微信群,希望可以加一下.

**Comment by simplezhli** [comment]
有个微信群，不过目前没时间管理，暂时不打算进人了。关于项目的问题就提issue就行。
