### ISSUE TITLE
iPhone12 pro Max模拟器TextField无法弹出软键盘

### ISSUE THREAD

**Issue by liulinhui** [simplezhli/flutter_deer#156]
### 运行环境 ###

- [x] 电脑系统：如：`macOs Big Sur 11.1`
- [x] 设备型号：如：`MacBook Pro(15-inch,2018)`
- [x] 设备系统版本：如 `iPhone12 pro Max`
- [x] Flutter 版本：如 `1.22.5`

### 具体问题描述 ###
iPhone12 pro Max模拟器TextField无法弹出软键盘,但是在iPhone12，iPhone12 pro以及iPhone11都是可以正常弹出的，Android模拟器也是可以弹出的
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/16570911/104832665-a08bf980-58cd-11eb-9aa8-2ccf6f5c2d5c.png)

#### 异常日志 ####
无

**Comment by simplezhli** [comment]
@liulinhui 模拟器的话，怀疑是设置问题。尝试Hardware －> Keyboard －> Toggle Software keyboard. 或者直接使用快捷键commod + k
