### ISSUE TITLE
下载了示例demo 进行安装测试，为什么 滑动列表时，文字会有抖动感？

### ISSUE THREAD

**Issue by zhang1395hao** [simplezhli/flutter_deer#157]
### 运行环境 ###

- [ ] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`华为P40`
- [x] 设备系统版本：如 `Android 10`

### 具体问题描述 ###

下载了示例demo apk 进行安装测试，为什么 滑动列表时，文字会有抖动感？

**Comment by simplezhli** [comment]
可以发个录屏吗?

**Comment by simplezhli** [comment]
@zhang1395hao 可以尝试最新1.1.5版本（基于flutter2.0.0），看是否还存在同样问题。我先关闭这个问题，如果还是存在问题可以再次打开。
