### ISSUE TITLE
版本兼容问题

### ISSUE THREAD

**Issue by yanqiangsjz** [simplezhli/flutter_deer#158]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 10`
- [ ] Flutter 版本：如 `1.22.6`

### 具体问题描述 ###
pub get y依赖包版本冲突
#### 异常日志 ####

Because flutter_deer depends on flutter_localizations any from sdk which depends on intl 0.17.0-nullsafety.2, intl 0.17.0-nullsafety.2 is required.
So, because flutter_deer depends on intl ^0.16.1, version solving failed.
pub get failed (1; So, because flutter_deer depends on intl ^0.16.1, version solving failed.)

将 intl 版本修改为0.17.0-nullsafety.2  后
Because no versions of intl_translation match >0.17.10+1 <0.18.0 and intl_translation 0.17.10+1 depends on intl >=0.15.3 <0.17.0, intl_translation ^0.17.10+1 requires intl >=0.15.3 <0.17.0.
So, because flutter_deer depends on both intl 0.17.0-nullsafety.2 and intl_translation ^0.17.10+1, version solving failed.
pub get failed (1; So, because flutter_deer depends on both intl 0.17.0-nullsafety.2 and intl_translation ^0.17.10+1, version solving failed.)

**Comment by yanqiangsjz** [comment]
flutter 版本： 1.25.0-8.2.pre

**Comment by simplezhli** [comment]
@yanqiangsjz  目前是intl 和intl_translation 版本不匹配，需要升级intl_translation。但由于目前intl_translation未发布相匹配版本。目前可以参考：https://github.com/dart-lang/intl_translation/issues/118#issuecomment-753492127 。或是暂时去除intl_translation依赖。

还是推荐使用和本项目相同的稳定sdk版本 1.22.6。

**Comment by yanqiangsjz** [comment]
@simplezhli   OK 谢谢大佬指点  已解决

**Comment by jh95813** [comment]
相对稳定的版本1.22.6在stable分支。如果是这样的话就无法开启mac desktop调试。解决办法还是屏蔽intl_translation依赖吧。

**Comment by simplezhli** [comment]
@jh95813 目前是的

**Comment by simplezhli** [comment]
flutter 已发布stable 2.0.0，默认开启Web。我以做好了相关适配。桌面支持同样已经发布在稳定 Channel。

**Comment by jh95813** [comment]
大佬优秀
