### ISSUE TITLE
请教下网络请求相关问题

### ISSUE THREAD

**Issue by criusKer** [simplezhli/flutter_deer#159]
想请教下requestNetwork和asyncRequestNetwork两个方法的区别是什么

**Comment by simplezhli** [comment]
@criusKer  requestNetwork 会返回Future 适用于刷新，加载更多这类场景（这部分项目中有例子）。asyncRequestNetwork就不返回。其实无脑用requestNetwork也行。

**Comment by criusKer** [comment]
原以为会和性能有关，怕用错场景，多谢回答
