### ISSUE TITLE
Compiler message: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.

### ISSUE THREAD

**Issue by crazyandcoder** [simplezhli/flutter_deer#16]
**如果出现以下问题：**

Compiler message: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.

**可以尝试下面做法：**

As a temporary workaround, you can navigate in Android Studio to Dart Packages > cached_network_image-0.7.0 > src > cached_network_image_provider.dart and remove the informationCollector named parameter (line 46), so the load(CachedNetworkImageProvider key) method will be as follows:

@override
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
    return new MultiFrameImageStreamCompleter(
        codec: _loadAsync(key),
        scale: key.scale,
    );
  }
This may not the best solution, but if you want to stay in Flutter 1.5.9, this workaround will allow you to run your app.

**Comment by simplezhli** [comment]
@crazyandcoder  这个项目的flutter sdk 为 1.5.4，你的flutter版本高于1.5.9，会有此问题。cached_network_image暂时的方案是https://github.com/renefloor/flutter_cached_network_image/issues/171， flustars: 升级到 0.2.6+1

**Comment by simplezhli** [comment]
@crazyandcoder  作者提供了新版本，cached_network_image: ^0.8.0   flustars: ^0.2.6+1  请替换这两行。我后面会同步上去。

**Comment by crazyandcoder** [comment]
好的，多谢。
