### ISSUE TITLE
关于空安全问题

### ISSUE THREAD

**Issue by tianketianke** [simplezhli/flutter_deer#161]

**Comment by simplezhli** [comment]
@tianketianke  官方给出了过渡和兼容的方法，详情见[迁移至空安全](https://dart.cn/null-safety/migration-guide)。我目前是等待依赖全部支持空安全后再做代码的迁移。当然你也可以先迁移代码至空安全，使用命令`flutter run --no-sound-null-safety`运行项目。详细见大喵的[Flutter 升级 2.0 填坑指导，带你原地起飞](https://juejin.cn/post/6938342360833064974)

**Comment by simplezhli** [comment]
目前进度：`cached_network_image` 与`flutter_driver`在flutter 2.0.3（master分支正常）中存在冲突，异常如下：

![image](https://user-images.githubusercontent.com/12456431/113087743-dc6d0480-9216-11eb-8bcb-0e2d2cb2dd19.png)

所以暂缓迁移工作，预计需要等到下一个稳定版。但这并不影响在flutter 2.0的使用。

**Comment by simplezhli** [comment]
对于使用到的三方库没有空安全版本的问题，目前已经替换了项目中用到的扫码插件barcode_scan。
`flutter_swiper`因为许久不维护（上一次更新19年3月22日），提交的相关PR也不进行合并。。。如果最终迁移时没有更新那就选用`flutter_card_swiper`或`flutter_swiper_null_safety`替换。

**Comment by simplezhli** [comment]
通过`dependency_overrides`将冲突的依赖覆盖，目前已完成了代码空安全的迁移。安装包大小10.3M -> 10.1M，减小了135KB。

**Comment by simplezhli** [comment]
代码已提交，并通过测试，此问题关闭。
