### ISSUE TITLE
关于flutter web qrcode scanner

### ISSUE THREAD

**Issue by hahazheng** [simplezhli/flutter_deer#162]
后续会支持 web qrcode scanner ？
目前针对web qrcode有木有好的方案讨论
另外，以下链接是否有可行性
https://github.com/check1e/flutter_web_qr_scanner

**Comment by simplezhli** [comment]
扫码功能主要依赖相关插件实现，自己支持的优先级不高。

之前关注过相关问题，以前使用的barcode_scan](https://github.com/apptreesoftware/flutter_barcode_reader)插件有相关PR，你可以参考一下。还有以前搜集相关资料的时候看到过一个实现：https://github.com/mockfrog/flutter_barcode_scanner_web

对于你发的这个看了一下，没有发现相关实现代码。

**Comment by hahazheng** [comment]
是的，我会关注，感谢你
关于 barcode_scanner_web 有个成型的例子
https://github.com/check1e/flutter_barcode_scanner_web
但是我在运行期间，总是得到一个错误
NoSuchMethodError: method not found: 'getUserMedia' on null

**Comment by simplezhli** [comment]
@hahazheng 我看实际上是使用了jsQR这个库，我查了一下issues，发现这是浏览器的安全特性，不支持http上使用。相关链接：https://github.com/cozmo/jsQR/issues?q=getUserMedia

**Comment by simplezhli** [comment]
jsQR提供的demo效果不错，手机上可以正常使用。https://cozmo.github.io/jsQR/

**Comment by hahazheng** [comment]
@simplezhli Hi, 我查阅了issues, 并设置了 chrome://flags/#unsafely-treat-insecure-origin-as-secure
 barcode_scanner_web可以良好的运行

可是在实际应用中， getUserMedia不支持http上使用这个在开发中国怎么处理？

谢谢

**Comment by simplezhli** [comment]
@hahazheng 现在的正式环境应该都已经采用https了，否则浏览器会有安全警告。我认为这不是一个问题。
