### ISSUE TITLE
按钮文字偏下

### ISSUE THREAD

**Issue by yunyuchen** [simplezhli/flutter_deer#165]
项目中所有的按钮的文字似乎都有点偏下，IOS中没有问题，安卓很明显。
这个有没有什么比较好的解决方案？

**Comment by simplezhli** [comment]
@yunyuchen 这是一直以来存在的一个问题，目前我的处理方法是`TextStyle`中设置`height`属性为1.1这个经验值。

因为偏下在按钮高度比较小时表现明显，所以项目中仅有几处这样处理。

**Comment by yunyuchen** [comment]
好的，非常感谢！

**Comment by simplezhli** [comment]
此问题可以跟踪这个Issus：https://github.com/flutter/flutter/issues/79931
