### ISSUE TITLE
有计划使用 getx 的状态管理库吗？

### ISSUE THREAD

**Issue by hlj2722** [simplezhli/flutter_deer#166]

**Comment by simplezhli** [comment]
@hlj2722 这个项目就是一个练习项目，包括已使用的provider也只是个别几个页面在练习使用。各种状态管理方案很多，适合自己的使用习惯就好，这里不做过多的使用。如果使用，也只是以demo的形式添加。目前没有使用getx的计划。

**Comment by simplezhli** [comment]
@hlj2722 这个项目就是一个练习项目，包括已使用的provider也只是个别几个页面在练习使用。各种状态管理方案很多，适合自己的使用习惯就好，这里不做过多的使用。如果使用，也只是以demo的形式添加。目前没有使用getx的计划。
