### ISSUE TITLE
DioUtils._onError() if code == null 条件不触发

### ISSUE THREAD

**Issue by JonYun** [simplezhli/flutter_deer#167]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 10`
- [x] Flutter 版本：如 `2.0.6`

### 具体问题描述 ###
在空安全环境下，code == null永远不会触发  参数code应该是可空类型
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/41783492/118775247-4de13f00-b8b9-11eb-86e4-5191562cdf54.png)

**Comment by simplezhli** [comment]
@JonYun 感谢反馈！我看了一下代码，主要问题是BaseEntity中的code类型设置有误，因为`response.statusCode`返回类型是`int?`。

我已将code改为`int?`类型。
