### ISSUE TITLE
关于dio的拦截器这一块请教一下

### ISSUE THREAD

**Issue by YeFei572** [simplezhli/flutter_deer#169]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 10`
- [x] Flutter 版本：如 `2.2.1`

### 具体问题描述 ###
看代码，项目启动的时候直接加载`Dio`的拦截器到`list`集合，然后在`DioUtils`中进行拦截器加载，想问一下，如果我要发起一个不需要填写token的请求，怎么屏蔽这个authorization的拦截器呢？

**Comment by YeFei572** [comment]
有的接口需要鉴权有的接口不能鉴权（不能传token，否则报错），我想是不是该有个参数什么的来区分一下？求个思路

**Comment by simplezhli** [comment]
接口少了在拦截器单独判断一下，多了的话。。。搞两个dio，区分调用。其他方式相对来说增加复杂度。或者让后端处理一下，不要折腾我们了。

**Comment by YeFei572** [comment]
如果整两个dio的话，那是不是意味着要创建两个不同的dio实例呢？ 
我也觉得统一比较好， 但是现实总是那么不如意。

**Comment by simplezhli** [comment]
@YeFei572 是的，两个实例。deer的`TokenInterceptor`中就会创建一个新的dio用来做重新请求。包括做下载时也是。

**Comment by YeFei572** [comment]
如果两个都是单例貌似也没啥问题是吧。挺好，就这么整吧
