### ISSUE TITLE
空安全迁移, 有什么需要注意的,请指教

### ISSUE THREAD

**Issue by fanlb** [simplezhli/flutter_deer#171]
Hi,  我目前接手的项目也准备升级到Dart2.12.0, 改动过程中发现几乎每个dart文件都需要做空安全修改, 改动量较大, 主要怕改出问题,
想请教下,  有什么好升级建议吗?

**Comment by simplezhli** [comment]
可以看这里 https://github.com/simplezhli/flutter_deer/issues/161 ，先确保依赖全部升级到空安全。代码顶部先全部添加`// @dart=2.9`，再逐步迁移。

**Comment by fanlb** [comment]
> 可以看这里 #161 ，先确保依赖全部升级到空安全。代码顶部先全部添加`// @dart=2.9`，再逐步迁移。

好的, 感谢 👍🏿
