### ISSUE TITLE
pub get 报错

### ISSUE THREAD

**Issue by wangmeng17** [simplezhli/flutter_deer#172]
报错信息
D:\MySoft\develop\flutterSDK\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in flutter_deer...                    
Could not find a file named "pubspec.yaml" in "D:\MySoft\develop\flutterSDK\flutter\.pub-cache\hosted\pub.flutter-io.cn\lottie-1.0.1".
pub get failed (66; Could not find a file named "pubspec.yaml" in "D:\MySoft\develop\flutterSDK\flutter\.pub-cache\hosted\pub.flutter-io.cn\lottie-1.0.1".)
Process finished with exit code 66
版本信息
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1052], locale zh-CN)
    • Flutter version 2.2.3 at D:\MySoft\develop\flutterSDK\flutter
    • Framework revision f4abaa0735 (30 hours ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by simplezhli** [comment]
@wangmeng17 运行 `flutter pub pub cache repair`，删除依赖缓存。然后重新`flutter pub get`

**Comment by wangmeng17** [comment]
谢谢，已解决。把缓存删完，重新下载代码，重试又没报错了。。
