### ISSUE TITLE
您好，关于网络请求部分的问题

### ISSUE THREAD

**Issue by bypanghu** [simplezhli/flutter_deer#173]
### 具体问题描述 ###
您好，最近入手flutter 项目，选择用您的项目进行入手学习，但是看到网络封装这块不是很了解，希望出一个wiki 可以简单说明一下怎么用的，谢谢

**Comment by simplezhli** [comment]
@bypanghu  目前的封装并不具有通用性，建议还是先熟悉dio的用法，了解了dio的使用，这样才能根据你的实际情况去解决问题。我的封装实现仅供参考，只是提供一个思路。

**Comment by bypanghu** [comment]
好的
