### ISSUE TITLE
MyTextField

### ISSUE THREAD

**Issue by AKA-LinCoder** [simplezhli/flutter_deer#174]
### iOS ###

- [x] iMac
- [x] 模拟器
- [x] ios14：
- [x] 2.2.0

**Comment by simplezhli** [comment]
@AKA-LinCoder `MyTextField`里面主要针对输入密码、数字格式处理。所以里面使用了`inputFormatters`限制了输入内容，如果你需要输入中文，去除`inputFormatters`部分设置就行了。

**Comment by simplezhli** [comment]
具体代码位置：https://github.com/simplezhli/flutter_deer/blob/c0678567b04e71e6045b12514f7bfe19e0deefe0/lib/login/widgets/my_text_field.dart#L110-L111

**Comment by AKA-LinCoder** [comment]
好的，谢谢了
