### ISSUE TITLE
您好 为什么 Presenter 网络请求 isShow 为true时  page界面 自动销毁呢

### ISSUE THREAD

**Issue by yueweilu** [simplezhli/flutter_deer#175]
Future getCategory(Map<String, String> params){
    return requestNetwork<BookLibraryCategortListEntity>(Method.post,
        url: HttpApi.get_book_library_category,
        queryParameters: params,
        isShow: true,
        onSuccess: (data) {
          if (data != null) {
              view.setLibraryCategory(data.xList??[]);
          } else {
          }
        },
        onError: (_, __) {
          /// 加载失败
          Log.e('-------------');
        }
    );
  }

**Comment by simplezhli** [comment]
@yueweilu isShow为 true时，会在请求结束关闭dialog时调用pop。如果页面关闭了，看是不是中间dialog被关闭。或是自己有重复调用pop操作。

**Comment by yueweilu** [comment]
isShow 不是为了显示加载状态的吗？为什么结束会调用pop呢

**Comment by yueweilu** [comment]
我的界面逻辑很简单，就是按照您的这个框架结构 就是在四个tab中的其中一个界面进行网络请求 isShow为true时就会自动的销毁了

**Comment by simplezhli** [comment]
我的代码中shop_presenter里面也是用的isShow为true，没有发现你说到的问题。具体情况你检查一下自己的代码。

**Comment by yueweilu** [comment]
好的谢谢  我自己再查一查

**Comment by yueweilu** [comment]
您好 我找到了问题的所在了  因为我调用接口的位置是在initState()内  那时候page 还没有build完成

**Comment by simplezhli** [comment]
@yueweilu 明白了，如果有initState中请求数据这类需求可以使用`WidgetsBinding.instance.addPostFrameCallback`处理。

**Comment by yueweilu** [comment]
好的非常感谢

**Comment by yueweilu** [comment]
好的，非常感谢
