### ISSUE TITLE
请教一下启动的问题一直卡在assembleDebug

### ISSUE THREAD

**Issue by 344020353** [simplezhli/flutter_deer#177]
![image](https://user-images.githubusercontent.com/6700402/132983991-65a0fb48-6d75-430c-9024-075685106640.png)
![image](https://user-images.githubusercontent.com/6700402/132984031-283d20d2-454d-4929-a1b9-99a33f22f7d1.png)
确认版本没有问题

**Comment by simplezhli** [comment]
卡主一般是下载gradle卡主了，看能不能访问https://services.gradle.org/distributions/gradle-6.5-all.zip 下载后放在本地。或者修改项目的gradle版本号为你本地已有的版本。

**Comment by 344020353** [comment]
多谢 大佬 解决了
大概是按照这个操作顺序
1.重新构建命令
f1540dd1dd8037efa9f36502071996cc.png
2.安装flutter 配置相应的安卓SDK，当andriod和flutter 安装顺序不一样时
flutter config --android-sdk path
flutter config --android-studio-dir path
3.然后在flutter run就成功了，
界面UI很棒，虽然是Demo 但是已经有线上的水准，值得多多学习
