### ISSUE TITLE
编译通不过，windows flutter 2.5.0

### ISSUE THREAD

**Issue by nightsimon** [simplezhli/flutter_deer#178]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：``
- [x] 设备系统版本：如 Android 11`
- [x] Flutter 版本：如 `2.5.0`

### 具体问题描述 ###
编译通不过报错，找不到 SystemChrome的方法
lib/main.dart:47:16: Error: Method not found: 'SystemChrome.setEnabledSystemUIMode'.
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: [SystemUiOverlay.bottom]);
               ^^^^^^^^^^^^^^^^^^^^^^

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/45738680/133069505-f30d1d94-0d39-4829-86e5-53ad167ae3d7.png)

**Comment by nightsimon** [comment]
Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git 
Framework • revision 4cc385b4b8 (5 days ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0

**Comment by simplezhli** [comment]
@nightsimon 这个方法是flutter 2.5新增的，如果找不到，确保你的环境安装是否正确。或者你可以先切到代码到适配2.5以前，这两者差别不大。

**Comment by nightsimon** [comment]
@simplezhli 嗯，刚开始本地装了两个版本的 flutter ，一直识别的是旧版本的 flutter, 没有识别到新版本的。

删除旧版本的，重新识别下就好了。谢谢
