### ISSUE TITLE
运行失败,Error output from Xcode build:

### ISSUE THREAD

**Issue by LockLight** [simplezhli/flutter_deer#184]
### 运行环境 ###

- [x] 电脑系统：如：`macOS`
- [x] 设备型号：如：`iphone13`
- [x] 设备系统版本：如 `iOS 14`
- [x] Flutter 版本：如 `Flutter 2.6.0-12.0.pre.670`

### 具体问题描述 ###
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Running pod install...                                           2,422ms
Running Xcode build...                                                  
Xcode build done.                                           30.0s
Failed to build iOS app
Error output from Xcode build:
↳
    2021-11-17 15:44:24.244 xcodebuild[49827:18667954] [MT] PluginLoading: Required plug-in compatibility UUID
    8BAA96B4-5225-471B-B124-D32A349B8106 for plug-in at path '~/Library/Application
    Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    2021-11-17 15:44:24.244 xcodebuild[49827:18667954] [MT] PluginLoading: Required plug-in compatibility UUID
    8BAA96B4-5225-471B-B124-D32A349B8106 for plug-in at path '~/Library/Application
    Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    ** BUILD FAILED **

Xcode's output:
↳
    lib/order/page/order_track_page.dart:42:30: Error: The argument type 'Widget Function(BuildContext, {dynamic onStepCancel,
    dynamic onStepContinue})' can't be assigned to the parameter type 'Widget Function(BuildContext, ControlsDetails)?'.
     - 'Widget' is from 'package:flutter/src/widgets/framework.dart'
     ('../flutter/packages/flutter/lib/src/widgets/framework.dart').
     - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart'
     ('../flutter/packages/flutter/lib/src/widgets/framework.dart').
     - 'ControlsDetails' is from 'package:flutter/src/material/stepper.dart'
     ('../flutter/packages/flutter/lib/src/material/stepper.dart').
                controlsBuilder: (_, {onStepContinue, onStepCancel}) {
                                 ^
    Failed to package /Users/locklight/Documents/Flutter/flutter_deer.
    Command PhaseScriptExecution failed with a nonzero exit code
    rsync: link_stat "/Users/locklight/Documents/Flutter/flutter_deer/build/ios/Debug-iphonesimulator/App.framework" failed: No
    such file or directory (2)
    rsync error: some files could not be transferred (code 23) at
    /System/Volumes/Data/SWE/macOS/BuildRoots/38cf1d983f/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996)
    [sender=2.6.9]
    rsync: link_stat "/Users/locklight/Documents/Flutter/flutter_deer/build/ios/Debug-iphonesimulator/App.framework" failed: No
    such file or directory (2)
    rsync error: some files could not be transferred (code 23) at
    /System/Volumes/Data/SWE/macOS/BuildRoots/38cf1d983f/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996)
    [sender=2.6.9]

    Unhandled exception:
    Exception: Command "rsync -av --delete --filter - .DS_Store
    /Users/locklight/Documents/Flutter/flutter_deer/build/ios/Debug-iphonesimulator/App.framework
    /Users/locklight/Documents/Flutter/flutter_deer/build/ios/Debug-iphonesimulator/Runner.app/Frameworks" exited with code 23
    #0      Context.runSync
    (file:///Users/locklight/Documents/Flutter/flutter/packages/flutter_tools/bin/xcode_backend.dart:105:7)
    #1      Context.embedFlutterFrameworks
    (file:///Users/locklight/Documents/Flutter/flutter/packages/flutter_tools/bin/xcode_backend.dart:190:5)
    #2      Context.run (file:///Users/locklight/Documents/Flutter/flutter/packages/flutter_tools/bin/xcode_backend.dart:61:9)
    #3      main (file:///Users/locklight/Documents/Flutter/flutter/packages/flutter_tools/bin/xcode_backend.dart:17:5)
    #4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
    #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel

Could not build the application for the simulator.
Error launching application on iPhone 13.

**Comment by LockLight** [comment]
找了各种解决办法,无法处理,感谢解惑

**Comment by simplezhli** [comment]
@LockLight flutter版本使用 2.5.x ，不确定2.6.x是否有破坏性升级。

**Comment by LockLight** [comment]
切换版本成功运行,感谢回复如此之快
