### ISSUE TITLE
flutter pub get

### ISSUE THREAD

**Issue by dluffymonkey** [simplezhli/flutter_deer#185]
### 运行环境 ###

- [x] 电脑系统：如：`MacOS`
- [x] 设备型号：如：`11.5.2`
- [x] 设备系统版本：如 ``
- [x] Flutter 版本：
Flutter 2.5.3 • channel stable • git@github.com:flutter/flutter.git
Framework • revision 18116933e7 (5 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

### 具体问题描述 ###
flutter pub get 报错

#### 问题截图 ####

<img width="1546" alt="WeChat0138abfc5eee1485747dc84230fb962d" src="https://user-images.githubusercontent.com/8476885/142179552-fdb774a5-9e9f-42a7-863b-9f11fd949ce0.png">

#### 异常日志 ####
[flutter_deer] flutter pub get
Running "flutter pub get" in flutter_deer...                    
Because intl_translation >=0.17.7 depends on intl >=0.15.3 <0.17.0 and intl_translation >=0.17.0 <0.17.7 depends on intl ^0.15.3, intl_translation >=0.17.0 requires intl >=0.15.3 <0.17.0.
So, because flutter_deer depends on both intl ^0.17.0 and intl_translation ^0.17.0+1, version solving failed.
pub get failed (1; So, because flutter_deer depends on both intl ^0.17.0 and intl_translation ^0.17.0+1, version solving failed.)
exit code 1

**Comment by simplezhli** [comment]
@dluffymonkey 你的代码至少是半年多以前的，intl_translation这个依赖很久之前就不用了。拉取最新代码尝试编译安装。

**Comment by dluffymonkey** [comment]
我把您这边的代码加到我git的upstream了，然后合并了一下，现在没有报错了，已经跑起来了，回复的非常及时，万分感谢

**Comment by simplezhli** [comment]
@dluffymonkey 好的，那我就问题关闭了。

**Comment by dluffymonkey** [comment]
嗯嗯，打扰了，我准备照着你的代码，重新自己敲一遍练手
