### ISSUE TITLE
运行报一堆错

### ISSUE THREAD

**Issue by ZFbaby** [simplezhli/flutter_deer#187]
### 运行环境 ###

- [x] 电脑系统：如：`macOS 11.5.1`
- [x] 设备型号：如：`模拟器`
- [x] 设备系统版本：如 `Android 11`
- [x] Flutter 版本：如 `2.5.2`

### 具体问题描述 ###
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
../../Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/common_utils-2.0.2/lib/src/money_util.dart:87:59: Error: The method 'toInt' isn't defined for the class 'Decimal'.
 - 'Decimal' is from 'package:decimal/decimal.dart' ('../../Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/decimal-2.0.0/lib/decimal.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toInt'.
    return NumUtil.multiplyDecStr(yuan.toString(), '100').toInt();
                                                          ^^^^^
../../Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/common_utils-2.0.2/lib/src/num_util.dart:134:29: Error: A value of type 'Rational' can't be returned from a function with return type 'Decimal'.
 - 'Rational' is from 'package:rational/rational.dart' ('../../Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/rational-2.0.0/lib/rational.dart').
 - 'Decimal' is from 'package:decimal/decimal.dart' ('../../Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/decimal-2.0.0/lib/decimal.dart').
    return Decimal.parse(a) / Decimal.parse(b);
                            ^

FAILURE: Build failed with an exception.

* Where:
Script '/Users/dzmacbook/Documents/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/dzmacbook/Documents/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by simplezhli** [comment]
@ZFbaby 问题出在了common_utils库的[这里的](https://github.com/Sky24n/common_utils/blob/ff114dd3ad1b312f32b248fb3c946ec8ffde8875/pubspec.yaml#L11)依赖规则上：
```
decimal: ">=1.0.0 <3.0.0"
```
看错误日志，目前你使用的刚更新的2.0.0版本，里面用到的方法去除了，所以导致运行异常。

![16383409854069](https://user-images.githubusercontent.com/12456431/144185620-510e90e7-5bf9-4b41-a07c-d60dc6dfc5f1.png)

我本地使用的是1.5.0版本，目前正常。
解决方法，添加覆盖依赖配置到pubspec.yaml中：

```
dependency_overrides:
  decimal: 1.5.0
```

感谢你的反馈，后面我会提交修复代码。

**Comment by ZFbaby** [comment]
谢谢拉，可以运行了，给你点颗星



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月1日(星期三) 下午2:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [simplezhli/flutter_deer] 运行报一堆错 (Issue #187)





 
@ZFbaby 问题出在了common_utils库的这里的依赖规则上：
 decimal: "&gt;=1.0.0 <3.0.0"  
看错误日志，目前你使用的刚更新的2.0.0版本，里面用到的方法去除了，所以导致运行异常。
 

 
我本地使用的是1.5.0版本，目前正常。
 解决方法，添加覆盖依赖配置到pubspec.yaml中：
 dependency_overrides:   decimal: 1.5.0  
感谢你的反馈，后面我会提交修复代码。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by simplezhli** [comment]
@ZFbaby 感谢支持！
