### ISSUE TITLE
红色报错信息

### ISSUE THREAD

**Issue by lsdlh** [simplezhli/flutter_deer#189]
### 运行环境 ###
Windows 10

- [x] 电脑系统：如：`Windows 10`
- [ ] 设备型号：如：`小米MIX 2s`
- [ ] 设备系统版本：如 `Android 11`
- [ ] Flutter 版本：如 `2.8.0`

### 具体问题描述 ###
能运行跑起来，为什么这么多红色报错
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/45959509/146737183-0c2ea99c-5f6b-41ed-88c5-ae95f2723152.png)

**Comment by xueqiulou** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by simplezhli** [comment]
@lsdlh 你的环境发一下。确保是最新代码且与README中环境一致。

**Comment by lsdlh** [comment]
> 

Flutter 2.8.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cf44000065 (11 days ago) • 2021-12-08 14:06:50 -0800
Engine • revision 40a99c5951
Tools • Dart 2.15.0

**Comment by simplezhli** [comment]
@lsdlh 不清楚其他文件是什么原因有lint警告。图中的dart文件在项目的`analysis_options.yaml`中已经排除了。我这边使用的Android Studio是正常的。

**Comment by simplezhli** [comment]
未回复，暂时关闭。如果还有问题可以重新打开。
