### ISSUE TITLE
大佬您好，关于app开发的

### ISSUE THREAD

**Issue by rhymelph** [simplezhli/flutter_deer#19]
大致查看了一下整体的项目，发现并没有使用mvp，数据、逻辑和视图都写到一起不太好吧，如果另一个人接手你的项目，可能会造成review困难，是否可以引用状态管理呢？而且mvp对于Flutter感觉并不适用，应该为mvvm，我个人理解为Flutter的界面是根据数据驱动，所以数据作为主导，并不像android开发那样，可以只更新一个控件，所以这个项目对于初学者比较友好（建议作为学习ui项目），但对于真正的企业项目，貌似不够用！

**Comment by simplezhli** [comment]
@rhymelph 本项目主要还是UI练习，至于mvp还是bloc之类的其实都是看场景的。我是习惯于mvp模式，所以后面引用了provider作为状态管理来完善mvp。因为这个项目本身是我用来练习Flutter的，所以mvp甚至以后的一些实现方案并不会出现在所有的页面，给你造成的误解表示抱歉，感谢你的建议。
