### ISSUE TITLE
想请教Semantics相关问题

### ISSUE THREAD

**Issue by wapscccs** [simplezhli/flutter_deer#190]
您好，我是一个盲人开发者，看到您有研究过Semantics相关内容
在IOS设备中，当我们开启”旁白后“，从一个页面返回上一级页面时，可以使用旁白手势进行返回，具体操作方式是：
两根手机按住屏幕不放，然后快速的向右移动一段距离，然后快速向左移动一段距离，即可实现返回，我们称之为搓擦手势
但是我在Flutter中没有找到相关的方法可以实现这个功能，不知道你是否可以提供一些帮助？非常感谢~

**Comment by simplezhli** [comment]
@wapscccs 目前Flutter并不支持搓擦手势，不过你可以参考这里的解决方法。https://github.com/flutter/flutter/issues/74246#issuecomment-971326926

**Comment by wapscccs** [comment]
> @wapscccs目前Flutter不支持搓擦，不过你可以参考这里的解决方法[。flutter/flutter#74246（评论）](https://github.com/flutter/flutter/issues/74246#issuecomment-971326926)

非常感谢，已经解决了我的问题~

**Comment by simplezhli** [comment]
@wapscccs 好的，那我就关闭了。
