### ISSUE TITLE
最新FlutterJsonBeanFactory4.2.8插件下生成Bean，会报错

### ISSUE THREAD

**Issue by diedaifa** [simplezhli/flutter_deer#191]
### 运行环境 ###

- [x] 电脑系统：如：`macOS Monterey 版本12.0.1`
- [x] 设备型号：如：`iPhone7`
- [x] 设备系统版本：如 `iOS14.4.2`
- [x] Flutter 版本：如 `2.8.0`

### 具体问题描述 ###
最新FlutterJsonBeanFactory插件下，option+j  生成Bean，会报错。
原先后缀为help.dart的转换为.g.dart的后缀了。

希望在最新的FlutterJsonBeanFactory版本下，适配一下。

#### 问题截图 ####
<img width="500" alt="WeChat43ec0762b05f422cd22788baa6f842a7" src="https://user-images.githubusercontent.com/10303272/147173760-98b9a173-7d09-476c-a116-a6416eb20a00.png">
<img width="500" alt="WeChat499179cadfc3907537b1b200c62c1230" src="https://user-images.githubusercontent.com/10303272/147173813-9d754d9f-7564-47aa-9983-ef37be643349.png">

**Comment by simplezhli** [comment]
@diedaifa 好的，我这边处理一下，感谢你的反馈。

**Comment by simplezhli** [comment]
@diedaifa 已经适配了，你可以拉取代码试一下。
