### ISSUE TITLE
call current tab refresh at pageview

### ISSUE THREAD

**Issue by canhbd** [simplezhli/flutter_deer#193]
### 运行环境 ###

- [x] 电脑系统：如：`MaxOSX`
- [x] 设备型号：如：`小米Samsung note 8`
- [x] 设备系统版本：如 `Android 9`
- [x] Flutter 版本：如 `1.22.6`

### 具体问题描述 ###
Hello, I have a problem, please help me.

I want to have a search bottom at parent page; each tab view, when i click to search button. how can i call refresh current tabview

<img width="507" alt="Screen Shot 2021-12-26 at 18 40 55" src="https://user-images.githubusercontent.com/45847757/147406908-d6e875c7-4f15-4578-b5e3-eff1bc2998ab.png">

Thank you!

**Comment by simplezhli** [comment]
You can refer to this: https://github.com/simplezhli/flutter_deer/issues/140#issuecomment-664843616
