### ISSUE TITLE
在主tab页中打开下一级页面，OrderPage和GoodsPage都会走build方法，返回之后还会再走一遍，不知道这是不是Bug，想请教下作者

### ISSUE THREAD

**Issue by itlws** [simplezhli/flutter_deer#194]
### 运行环境 ###

- [x] 电脑系统：如：`MacBook Air`
- [x] 设备型号：如：`iPhone 11`
- [x] 设备系统版本：如 `ios 15.1`
- [x] Flutter 版本：如 `2.5.2`

### 具体问题描述 ###
在主tab页中打开下一级页面，OrderPage和GoodsPage都会走build方法，返回之后还会再走一遍
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/7419461/148174107-22c5ab6d-409f-4e74-af2f-9eabe03b199c.png)

**Comment by simplezhli** [comment]
@itlws 周内有些忙，很抱歉现在才回复你。这个问题其实是因为使用了`SingleTickerProviderStateMixin `导致了build。
源码如下：
```
@override
  void didChangeDependencies() {
    if (_ticker != null)
      _ticker!.muted = !TickerMode.of(context);
    super.didChangeDependencies();
  }
```
`TickerMode.of`方法源码：
```
 static bool of(BuildContext context) {
    final _EffectiveTickerMode? widget = context.dependOnInheritedWidgetOfExactType<_EffectiveTickerMode>();
    return widget?.enabled ?? true;
  }
```

`_EffectiveTickerMode`中的属性变化时会触发build，这与它的机制有关，所以不是一个bug。而且本身重复build不会有太大的性能问题，不过我认为这里是有优化空间。

目前能做的有两种方法：
一种类似项目中的`RiseNumberText`，进行封装，控制它的使用范围，来减小这种build的范围。

另一种可以在页面中重写方法`didChangeDependencies `，这样就不会执行`TickerMode.of`方法。
```
@override
void didChangeDependencies() {
}
```
不过这种方法会破坏原本的处理，需要根据页面具体情况使用。

**Comment by itlws** [comment]
好的，明白了，感谢作者的耐心讲解！
