### ISSUE TITLE
执行完pub get 报错

### ISSUE THREAD

**Issue by yemeihanxing** [simplezhli/flutter_deer#195]
执行了pub get 后，
main.dart
login 页面
import 'package:flutter_gen/gen_l10n/deer_localizations.dart'; 显示错误，此文件在哪里的？？

**Comment by simplezhli** [comment]
@yemeihanxing 这些文件是自动生成的。多尝试几次pub get，或是直接运行。

**Comment by yemeihanxing** [comment]
> @yemeihanxing 这些文件是自动生成的。多尝试几次pub get，或是直接运行。

好的，谢谢
