### ISSUE TITLE
项目中封装了网络请求但是没有模拟请求网络数据，如果可以请完善一下，数据解析比较难懂

### ISSUE THREAD

**Issue by Ave838** [simplezhli/flutter_deer#196]

**Comment by simplezhli** [comment]
@Ave838 项目中有两处使用示例order_search_page和shop_page，而且数据解析并没有什么特别的封装。

**Comment by Ave838** [comment]
谢谢回复，我说的数据解析是Flutter中的数据解析相对来说有点复杂，项目中的网络请求找到了

**Comment by simplezhli** [comment]
@Ave838 flutter中限制了反射的使用，所以只能如此解析。目前也只能通过工具生成bean，来减少这块的手动书写。这方面项目使用了插件[FlutterJsonBeanFactory](https://github.com/zhangruiyu/FlutterJsonBeanFactory)，可以了解一下。
