### ISSUE TITLE
我在本地编译后的app.release.apk包有20M左右,作者你是如何减小打包体积到10M的?

### ISSUE THREAD

**Issue by pangteman** [simplezhli/flutter_deer#197]

**Comment by simplezhli** [comment]
@pangteman 其实之前的issue和文档中都有。。。你可以看这里：https://github.com/simplezhli/flutter_deer/blob/master/docs/Android问题汇总.md

**Comment by pangteman** [comment]
牛哇牛哇,作者牛哇!!!
