### ISSUE TITLE
 请看这个 🥺

### ISSUE THREAD

**Issue by Lakhankumawat** [simplezhli/flutter_deer#198]
## 这个问题对于一些不懂中文的开发者来说很严重

> 事实上，我不了解 chinense，发现在项目中实现 bunny 真的很难  

> 我是一名 Flutter 开发人员，我制作开源 UI

> 如果您想知道我是如何在“使用谷歌翻译”中输入这么多中文的

<hr>

> 最后但并非最不重要的应用程序真的很好你的努力真的被看到了但无法获得评论以及README中写的内容，希望你能理解兄弟😃
## Zhège wèntí duìyú yīxiē bù dǒng zhōngwén de kāifā zhě lái shuō hěn yánzhòng

> shìshí shàng, wǒ bù liǎojiě chinense, fāxiàn zài xiàngmù zhōng shíxiàn bunny zhēn de hěn nán   

> wǒ shì yī míng Flutter kāifā rényuán, wǒ zhìzuò kāiyuán UI

> rúguǒ nín xiǎng zhīdào wǒ shì rúhé zài “shǐyòng gǔgē fānyì” zhōng shūrù zhème duō zhōngwén de

<hr >

> zuìhòu dàn bìngfēi zuì bù chóng yào de yìngyòng chéngxù zhēn de hěn hǎo nǐ de nǔlì zhēn de bèi kàn dàole dàn wúfǎ huòdé pínglùn yǐjí README zhōng xiě de nèiróng, xīwàng nǐ néng lǐjiě xiōngdì 😃

**Comment by xueqiulou** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Lakhankumawat** [comment]
> 这是来自QQ邮箱的假期自动回复邮件。   您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

哇 ！你有一个自动生成的电子邮件设置，请告诉我你是如何为你设置的

**Comment by simplezhli** [comment]
@Lakhankumawat The bunny animation is 77 frames in total, which actually means that the animation is played in different states.
https://github.com/simplezhli/flutter_deer/blob/6eaf35563f20a624cf28d291f5b84729a6c547a7/lib/demo/lottie/bunny.dart#L13-L23
These are the frame rate ranges for each state.

**Comment by Lakhankumawat** [comment]
> @Lakhankumawat The bunny animation is 77 frames in total, which actually means that the animation is played in different states.
> 
> https://github.com/simplezhli/flutter_deer/blob/6eaf35563f20a624cf28d291f5b84729a6c547a7/lib/demo/lottie/bunny.dart#L13-L23
> 
> 
> These are the frame rate ranges for each state.

that is okay but what about multilingual support in repo 🥺

**Comment by simplezhli** [comment]
Currently only this: https://github.com/simplezhli/flutter_deer/blob/master/README-EN.md

**Comment by Lakhankumawat** [comment]
🙇 Thanks ... I could have helped but bit busy these days. Also in main README if possible  mention a link to EN version so that newcomer can easily navigate to it o/w README-EN in file structure is bit un noticable .

**Comment by simplezhli** [comment]
Thank you for the suggestion, I will add on.
