### ISSUE TITLE
flutter web项目访问单个页面的链接地址打不开，404

### ISSUE THREAD

**Issue by haoxuhong** [simplezhli/flutter_deer#199]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 12`
- [x] Flutter 版本：如 `2.10.0`

### 具体问题描述 ###
flutter web项目访问单个页面的链接地址打不开，404
如：在浏览器上单独访问地址：https://simplezhli.github.io/flutter_deer/order/info
打不开，报404
#### 问题截图 ####

![WechatIMG103](https://user-images.githubusercontent.com/18694420/153171464-d5208470-5b73-444d-a004-667e36fbe342.jpeg)

**Comment by simplezhli** [comment]
@haoxuhong 因为目前没有迁移至Navigator 2.0，具体可以看这篇[【译】学习Flutter中新的Navigator和Router系统](https://weilu.blog.csdn.net/article/details/108902282)

**Comment by haoxuhong** [comment]
通过这样运行就可以通过链接访问：flutter run -d chrome --web-hostname 10.1.4.28 --web-port 8081

如访问链接：http://10.1.4.28:8081/flutter_deer/store/auditResult

发布到生产环境就不可以，我在想是不是调试环境下和生产环境下有什么不同，生产环境下是不是需要配置些东西才能访问？

注：上面的10.1.4.28是我电脑的IP，8081是端口号，您可以改为自己的IP和端口号试试

**Comment by haoxuhong** [comment]
好的，谢谢回复，查出来问题了吗？

**Comment by simplezhli** [comment]
问题应该是我使用了PathUrlStrategy，所以需要要配置服务器来支持。文档：https://flutter.cn/docs/development/ui/navigation/url-strategies#configuring-your-web-server  具体如何配置GitHub pages我还需要找找。

**Comment by simplezhli** [comment]
[参考这里](https://stackoverflow.com/questions/29390425/github-pages-url-rewrite-support)，尝试了自定义404页面的方式，发现无效。
后面在flutter的issue中找到了这个[问题](https://github.com/flutter/flutter/issues/98189)，可以关注一下。

**Comment by haoxuhong** [comment]
好的，谢谢回复，有解决办法了麻烦说下。

**Comment by haoxuhong** [comment]
页面链接打不开我知道是#号的原因了，加上#号就能打开了，现在有个问题：

我自己项目中微信授权登录后跳转到首页因为首页链接有#号获取不到#号后面的参数。
我的想法是能不能首页使用去除#号，其它页面带#号，这种的怎么实现？

现在只能做到要么项目所有页面链接都带#号，要么都不带#号，如何实现某个页面不带#号，其它页面带#号呢？

**Comment by simplezhli** [comment]
这方面我也不是很清楚，你可以去flutter的项目下问一下。

**Comment by haoxuhong** [comment]
好的

**Comment by ManXliu** [comment]
> 页面链接打不开我知道是#号的原因了，加上#号就能打开了，现在有个问题：
> 
> 我自己项目中微信授权登录后跳转到首页因为首页链接有#号获取不到#号后面的参数。 我的想法是能不能首页使用去除#号，其它页面带#号，这种的怎么实现？
> 
> 现在只能做到要么项目所有页面链接都带#号，要么都不带#号，如何实现某个页面不带#号，其它页面带#号呢？

可以搜索 哔哩哔哩搜索王叔不秃 flutter web 劝退指南这个视频里面有 实现方式

**Comment by haoxuhong** [comment]
@ManXliu 您好，刚看了下"王叔不秃 flutter web 劝退指南"教程，里面只有怎么去掉#号的方式，没说怎么实现实现某个页面不带#号，其它页面带#号的情况，是我看的教程不对吗？能罚下视频链接吗？

**Comment by haoxuhong** [comment]
@simplezhli @ManXliu 感谢两位的帮忙，问题解决了，需要在后端nginx服务器上配置下
![image](https://user-images.githubusercontent.com/18694420/155494647-d8ed8670-f214-4ad4-859d-53b050649c52.png)

我去掉#号后，对应到前端应该是history模式
原理说明：
https://blog.csdn.net/Honnyee/article/details/81286356

**Comment by simplezhli** [comment]
问题解决，那我就关闭了。
