### ISSUE TITLE
能把SpUtil移除下吗？

### ISSUE THREAD

**Issue by Sky24n** [simplezhli/flutter_deer#2]
[flustars](https://github.com/Sky24n/flustars)库本身就已经包含了SpUtil了，你这样把源码暴露在外面，大家都直接copy你项目里面的工具类使用了，而不去使用pub库了，谢谢

**Comment by simplezhli** [comment]
@Sky24n 感谢指出，是我疏忽了，已修正。不过使用0.2.5+1 版本 导致 Method not found: 'ImageStreamListener'。希望可以尽快发布修复后的版本，我暂时使用的0.2.5。

**Comment by Sky24n** [comment]
这个是对的，是因为flutter 1.6.3版本开始，这个方法就改变了导致的不兼容。升级到 1.6.3版本后就没有问题了。我是基于这个版本开发的。
```dart
[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17763.503], locale zh-CN)

这是最新的源码。
class ImageStreamListener {
  /// Creates a new [ImageStreamListener].
  ///
  /// The [onImage] parameter must not be null.
  const ImageStreamListener(
    this.onImage, {
    this.onChunk,
    this.onError,
  }) : assert(onImage != null);
```
