### ISSUE TITLE
flutter build apk 提示android sdk版本低

### ISSUE THREAD

**Issue by fuzhenfeng** [simplezhli/flutter_deer#202]
### 运行环境 ###

- [x] 电脑系统：macOS 11.3.1
- [x] 设备型号：
- [x] 设备系统版本：
- [x] Flutter 版本：Flutter 2.10.0 Dart 2.16.0

### 具体问题描述 ###
执行 flutter build apk 后异常

#### 异常日志 ####
* What went wrong:
Execution failed for task ':app:checkReleaseAarMetadata'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.window:window-java:1.0.0-beta04.

compileSdkVersion 29 targetSdkVersion 29 改成 compileSdkVersion 31 targetSdkVersion 31
不知道这样对不对？

**Comment by simplezhli** [comment]
大兄弟，先拉取最新代码试一下。如果还有问题，再反馈。没必要一个异常就开一个issue吧。

**Comment by fuzhenfeng** [comment]
确实是代码旧了，重新拉了一个就可以了。
