### ISSUE TITLE
是否能提供一个可以快速构建的基础模板

### ISSUE THREAD

**Issue by MaybeQHL** [simplezhli/flutter_deer#203]
是否能提供一个可以快速构建的基础模板

**Comment by MaybeQHL** [comment]
删除一些代码示例 保留基础的网络请求、路由、主题配置 等等。

**Comment by simplezhli** [comment]
这个项目只是我个人对开发flutter项目的理解，提供一个解决方案，仅供参考。你可以结合自己的项目和使用习惯去封装，这样也能加深理解。示例代码其实就在这些文件夹下，删了就好。
![image](https://user-images.githubusercontent.com/12456431/155254397-840807a2-99cd-42fc-af01-9eac8f478789.png)

**Comment by MaybeQHL** [comment]
> 这个项目只是我个人对开发flutter项目的理解，提供一个解决方案，仅供参考。你可以结合自己的项目和使用习惯去封装，这样也能加深理解。示例代码其实就在这些文件夹下，删了就好。 ![image](https://user-images.githubusercontent.com/12456431/155254397-840807a2-99cd-42fc-af01-9eac8f478789.png)

ok
