### ISSUE TITLE
iOS release 版本在地址选择页地址列表不显示

### ISSUE THREAD

**Issue by simplekkj** [simplezhli/flutter_deer#204]
### 运行环境 ###

- [x] 电脑系统：`macOS 12.2.1 21D62 darwin-x64`
- [x] 设备型号：`iPhone 11`
- [x] 设备系统版本：`iOS 15.3.1`
- [x] Flutter 版本：`Channel stable, 2.10.2`

### 具体问题描述 ###
ios release 版本在地址选择页只显示地图不显示地址列表

#### 问题截图 ####
![IMG_457CC93BA2F4-1](https://user-images.githubusercontent.com/90430774/155715620-acce3ea9-dc13-4648-961a-2081833cab42.jpeg)

**Comment by simplezhli** [comment]
debug下正常吗？有具体的错误信息可以提供一下吗？

**Comment by simplekkj** [comment]
之前直接上 release 了，刚在 debug 看了下，是 Key 验证失败

> Debug service listening on ws://127.0.0.1:51955/96JN-xyyYpQ=/ws
> Syncing files to device iPhone 11...
> fopen failed for data file: errno = 2 (No such file or directory)
> Errors found! Invalidating cache...
> fopen failed for data file: errno = 2 (No such file or directory)
> Errors found! Invalidating cache...
> Can't find keyplane that supports type 5 for keyboard iPhone-PortraitTruffle-PhonePad; using 27170_PortraitTruffle_iPhone-Complex-Pad_Default
> [] nehelper sent invalid result code [1] for Wi-Fi information request
> 授权失败
> Key验证失败 
> >>>>>>>>>
> 	BundleID:com.simplekkj.test 
> 	Key:4327916279bf45a044bb53b947442387 
> 	SDK:AMAP_SDK_iOS_2DMap_5.6.0 
> 	csid:739CEBB6-66E3-4A3D-A002-04679A579317 
> 	gsid:033043136016164579415875700015630844832, 033043136016164579415875700015630844832 
> 	info:INVALID_USER_SCODE 
> 	time:20220225 210239 
> 
> 
> 	请在高德开放平台官网中搜索【INVALID_USER_SCODE】相关内容进行解决。
> 	多谢合作。
> <<<<<<<<<
> (null)
> [] nehelper sent invalid result code [1] for Wi-Fi information request
> [] nehelper sent invalid result code [1] for Wi-Fi information request
> App Transport Security has blocked a cleartext HTTP connection since it is insecure. Use HTTPS instead or add Exception Domains to your app's Info.plist.
> Cannot start load of Task <05F08548-19B0-490B-8E11-16A384620432>.<2> since it does not conform to ATS policy
> Task <05F08548-19B0-490B-8E11-16A384620432>.<2> finished with error [-1022] Error Domain=NSURLErrorDomain Code=-1022 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." UserInfo={NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection., NSErrorFailingURLStringKey=http://dualstack-arestapi.amap.com/sdk/compliance/params, NSErrorFailingURLKey=http://dualstack-arestapi.amap.com/sdk/compliance/params, _NSURLErrorRelatedURLSessionTaskErrorKey=(
>     "LocalDataTask <05F08548-19B0-490B-8E11-16A384620432>.<2>"
> ), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <05F08548-19B0-490B-8E11-16A384620432>.<2>, NSUnderlyingError=0x2803f5110 {Error Domain=kCFErrorDomainCFNetwork Code=-1022 "(null)"}}
> 直接请求定位数据
> (null)
> [] nehelper sent invalid result code [1] for Wi-Fi information request
> [] nehelper sent invalid result code [1] for Wi-Fi information request
> [] nehelper sent invalid result code [1] for Wi-Fi information request
> [] nehelper sent invalid result code [1] for Wi-Fi information request
> [] nehelper sent invalid result code [1] for Wi-Fi information request
> [] nehelper sent invalid result code [1] for Wi-Fi information request
> [] nehelper sent invalid result code [1] for Wi-Fi information request
> Key验证失败 
> >>>>>>>>>
> 	BundleID:com.simplekkj.test 
> 	Key:4327916279bf45a044bb53b947442387 
> 	SDK:AMAP_SDK_iOS_Search_8.1.0 
> 	csid:99999555-0B67-4836-A2FE-7086BA96E53D 
> 	gsid:033005086066164579416029800014820017497, 033005086066164579416029800014820017497 
> 	info:INVALID_USER_SCODE 
> 	time:20220225 210240 
> 
> 
> 	请在高德开放平台官网中搜索【INVALID_USER_SCODE】相关内容进行解决。
> 	多谢合作。
> <<<<<<<<<
>

**Comment by simplezhli** [comment]
key是和BundleID绑定的，我看你的BundleID是com.simplekkj.test。我的ID是com.weilu.flutterDeer

**Comment by simplekkj** [comment]
明白了, Thanks!

**Comment by simplekkj** [comment]
换了自己的 key 后已恢复
