### ISSUE TITLE
vivo x27pro android10  进入商品扫码页面黑屏，息屏后或home建退出再进入项目，相机好用

### ISSUE THREAD

**Issue by xiuzhenguo** [simplezhli/flutter_deer#205]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`v`
- [x] 设备系统版本：如 `Android 10`
- [x] Flutter 版本：如 `2.10.0`

**Comment by xueqiulou** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by simplezhli** [comment]
@xiuzhenguo 我这里目前复现不了，你可以试一下这个扫码插件的demo，看是否有同样的问题。https://github.com/juliuscanute/qr_code_scanner

**Comment by xiuzhenguo** [comment]
我试了下， 这个扫码插件https://github.com/juliuscanute/qr_code_scanner 也是有同样的问题在 vivo的手机上，当使用textFiled时obscureText属性设置为true后，就会出现黑屏的问题，息屏后或home建退出再进入项目，相机好用。其他型号的手机不会出现这个问题

**Comment by simplezhli** [comment]
@xiuzhenguo  你试一下最新代码，我尝试修改了一下。
