### ISSUE TITLE
web端文字超出，未出现省略号的问题

### ISSUE THREAD

**Issue by haoxuhong** [simplezhli/flutter_deer#207]
使用`TextOverflow.ellipsis`属性。

现象如下：

- 文字没有超出，后面出现红色省略号。

- 文字超出，未出现省略号。

**这个问题您解决了吗？**

**Comment by simplezhli** [comment]
@haoxuhong 我看已经显示正常了。不过canvaskit有个省略号的问题，我后面还需要处理一下。
