### ISSUE TITLE
登录这块是怎么控制的  有相关的介绍吗？

### ISSUE THREAD

**Issue by kotlings** [simplezhli/flutter_deer#210]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 12`
- [x] Flutter 版本：如 `3.0.1`

**Comment by simplezhli** [comment]
@kotlings 登录这里只是简单校验了一下格式，并没有真正的请求接口。

**Comment by kotlings** [comment]
比如web这个 ，项目启动之后我通过修改URL的链接 为home  他会跳转到到home页面，然后马上又弹出了登录来，我没看到哪里进行了登录的控制

**Comment by simplezhli** [comment]
参见：https://github.com/simplezhli/flutter_deer/issues/199

**Comment by kotlings** [comment]
好像什么都说了， 又好像都没说 .  就是纠结一个点把main.dart的home 改成不是SplashPage 就可以指定随意页面跳转， 否则跳转过去就会弹出登录界面

**Comment by simplezhli** [comment]
链接直接访问，可以认为整个应用重新初始化了。那么初始化后加载home，但`SplashPage`中有个1.5秒的延时跳转，延时结束然后进入到登录页。你的疑问应该就是因为有这个延时。
