### ISSUE TITLE
软键盘弹出，不顶起底部按钮，还保持不遮挡底部的输入框。

### ISSUE THREAD

**Issue by mrchenmo** [simplezhli/flutter_deer#213]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 12`
- [x] Flutter 版本：如 `3.0.1`

### 具体问题描述 ###
比如编辑商品页面有多个输入框，提交按钮在底部，如何实现，软键盘弹出，不把提交按钮顶到软键盘上方，处于底部的输入框获取焦点后，能滚动到软键盘上方，不被遮挡。
一直没找到好的实现方法，我现在是监听软键盘弹出将底部按钮隐藏，有一点缺陷就是软键盘落下时，底部会空白一下。

鹿哥，有好的解决方式吗？
#### 问题截图 ####

![image](https://user-images.githubusercontent.com/18020929/180139312-b06f3907-7281-4487-8e22-bf1a3eb96173.png)

**Comment by simplezhli** [comment]
@mrchenmo 可以试试把底部按钮放到`Scaffold`的`bottomNavigationBar`里面。

![image](https://user-images.githubusercontent.com/12456431/180179085-db95f2a3-6ae9-4b50-9d48-9a14cda30074.png)

**Comment by mrchenmo** [comment]
真的可以哎，鹿哥牛逼
