### ISSUE TITLE
你好，问一下Dio的baseUrl如何动态更改呢？

### ISSUE THREAD

**Issue by panyy** [simplezhli/flutter_deer#214]

**Comment by simplezhli** [comment]
@panyy 定义多个不同的`Options`，在这个对象里面指定不同的`baseUrl`。 请求接口时，传入相应的`Options`，来实现`baseUrl`的切换。

**Comment by panyy** [comment]
Options里面没有找到baseUrl

**Comment by simplezhli** [comment]
抱歉，我把`Options`和`BaseOptions`记混了。通过`dio.options.baseUrl = "http://xxx";`是可以动态修改的。
不过这么看来我暂时也没有什么比较好的方法了，你可以去dio的项目下问问。

**Comment by panyy** [comment]
好的
