### ISSUE TITLE
使用RestorationMixin实现临时状态存储报错

### ISSUE THREAD

**Issue by userhjp** [simplezhli/flutter_deer#215]
问题描述：
使用 RestorationMixin 实现临时状态存储报错。

重现步骤：
1、android 开发者选择->开启不保留活动（只有被系统杀死才会触发状态储存，手动退出app不会触发，开启方便测试）。
2、打开app然后返回桌面，因开启了不保留活动返回桌面app进程立即后台杀掉，按照RestorationMixin介绍会在杀掉前储存状态，以保证下次进入恢复到上次状态。
3、重新进入app，直接报错。关闭RestorationMixin（删除MaterialApp下restorationScopeId）后正常，当然状态储存肯定无效了。

看异常意思大概像是在路由未初始化还是其他影响到了，看着有点懵。
异常片段：
```
I/flutter (31550): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (31550): The following assertion was thrown building MediaQuery(MediaQueryData(size: Size(392.7, 834.9),
I/flutter (31550): devicePixelRatio: 2.8, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding:
I/flutter (31550): EdgeInsets(0.0, 32.7, 0.0, 0.0), viewPadding: EdgeInsets(0.0, 32.7, 0.0, 0.0), viewInsets:
I/flutter (31550): EdgeInsets.zero, alwaysUse24HourFormat: true, accessibleNavigation: false, highContrast: false,
I/flutter (31550): disableAnimations: false, invertColors: false, boldText: false, navigationMode: traditional,
I/flutter (31550): gestureSettings: DeviceGestureSettings(touchSlop: 8.0), displayFeatures: [DisplayFeature(rect:
I/flutter (31550): Rect.fromLTRB(0.0, 0.0, 64.4, 32.7), type: DisplayFeatureType.cutout, state:
I/flutter (31550): DisplayFeatureState.unknown)])):
I/flutter (31550): All routes returned by onGenerateInitialRoutes are not restorable. Please make sure that all routes
I/flutter (31550): returned by onGenerateInitialRoutes have their RouteSettings defined with names that are defined in
I/flutter (31550): the app's routes table.
I/flutter (31550): 'package:flutter/src/widgets/navigator.dart':
I/flutter (31550): Failed assertion: line 3310 pos 7: '_history.isNotEmpty'
I/flutter (31550):
I/flutter (31550): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (31550): more information in this error message to help you determine and fix the underlying cause.
I/flutter (31550): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (31550):   https://github.com/flutter/flutter/issues/new?template=2_bug.md
I/flutter (31550):
I/flutter (31550): The relevant error-causing widget was:
I/flutter (31550):   MediaQuery MediaQuery:file:///D:/projects/xuexi/flutter/flutter_deer/lib/main.dart:160:16
I/flutter (31550):
I/flutter (31550): When the exception was thrown, this was the stack:
I/flutter (31550): #2      NavigatorState.restoreState (package:flutter/src/widgets/navigator.dart:3310:7)
I/flutter (31550): #3      RestorationMixin._doRestore (package:flutter/src/widgets/restoration.dart:887:5)
I/flutter (31550): #4      RestorationMixin.didChangeDependencies (package:flutter/src/widgets/restoration.dart:873:7)
I/flutter (31550): #5      NavigatorState.didChangeDependencies (package:flutter/src/widgets/navigator.dart:3336:11)
I/flutter (31550): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4963:11)
I/flutter (31550): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
I/flutter (31550): ...     Normal element mounting (279 frames)
I/flutter (31550): #286    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
I/flutter (31550): #287    Element.updateChild (package:flutter/src/widgets/framework.dart:3545:20)
I/flutter (31550): #288    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
I/flutter (31550): #289    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
I/flutter (31550): #290    Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
I/flutter (31550): #291    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
I/flutter (31550): #292    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
I/flutter (31550): #293    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
I/flutter (31550): #294    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
I/flutter (31550): #295    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
I/flutter (31550): #296    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
I/flutter (31550): (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (31550):
I/flutter (31550): ═══════════════════════════════════════════════════════════════════════════════════
```

**Comment by simplezhli** [comment]
目前来看没有什么头绪，有时间了我找找原因。你可以写个简单的demo试一下，排除一下和fluro有没有关系。

**Comment by fixedyangsir** [comment]
同上，我也遇到这个问题

**Comment by simplezhli** [comment]
@userhjp @fixedyangsir 我看了一下[相关文档](https://api.flutter.dev/flutter/widgets/Navigator-class.html)，发现使用`RestorationMixin`的一些注意点。

State Restoration
If provided with a [restorationScopeId](https://api.flutter.dev/flutter/widgets/Navigator/restorationScopeId.html) and when surrounded by a valid [RestorationScope](https://api.flutter.dev/flutter/widgets/RestorationScope-class.html) the [Navigator](https://api.flutter.dev/flutter/widgets/Navigator-class.html) will restore its state by recreating the current history stack of [Route](https://api.flutter.dev/flutter/widgets/Route-class.html)s during state restoration and by restoring the internal state of those [Route](https://api.flutter.dev/flutter/widgets/Route-class.html)s. However, not all [Route](https://api.flutter.dev/flutter/widgets/Route-class.html)s on the stack can be restored:

- [Page](https://api.flutter.dev/flutter/widgets/Page-class.html)-based routes restore their state if [Page.restorationId](https://api.flutter.dev/flutter/widgets/Page/restorationId.html) is provided.
- [Route](https://api.flutter.dev/flutter/widgets/Route-class.html)s added with the classic imperative API ([push](https://api.flutter.dev/flutter/widgets/Navigator/push.html), [pushNamed](https://api.flutter.dev/flutter/widgets/Navigator/pushNamed.html), and friends) can never restore their state.
- A [Route](https://api.flutter.dev/flutter/widgets/Route-class.html) added with the restorable imperative API ([restorablePush](https://api.flutter.dev/flutter/widgets/Navigator/restorablePush.html), [restorablePushNamed](https://api.flutter.dev/flutter/widgets/Navigator/restorablePushNamed.html), and all other imperative methods with "restorable" in their name) restores its state if all routes below it up to and including the first [Page](https://api.flutter.dev/flutter/widgets/Page-class.html)-based route below it are restored. If there is no [Page](https://api.flutter.dev/flutter/widgets/Page-class.html)-based route below it, it only restores its state if all routes below it restore theirs.

If a [Route](https://api.flutter.dev/flutter/widgets/Route-class.html) is deemed restorable, the [Navigator](https://api.flutter.dev/flutter/widgets/Navigator-class.html) will set its [Route.restorationScopeId](https://api.flutter.dev/flutter/widgets/Route/restorationScopeId.html) to a non-null value. Routes can use that ID to store and restore their own state. As an example, the [ModalRoute](https://api.flutter.dev/flutter/widgets/ModalRoute-class.html) will use this ID to create a [RestorationScope](https://api.flutter.dev/flutter/widgets/RestorationScope-class.html) for its content widgets.

目前`fluro`路由跳转使用的是push方法，所以并不能恢复路由，那边相应的状态存储也就无法实现。

你们可以使用这个demo验证一下：`flutter create --sample=widgets.RestorableRouteFuture.1 mysample`

**Comment by fixedyangsir** [comment]
大佬再问一个问题，就是鸿蒙系统退到后台，进入黑屏，不知道怎么解决https://github.com/flutter/flutter/issues/109908

**Comment by xueqiulou** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by simplezhli** [comment]
@fixedyangsir 这个问题我也不是很清楚。目前flutter并没有专门兼容鸿蒙，所以这种问题只能反馈给鸿蒙那边。或者看其他人有没有好的解决办法。
