### ISSUE TITLE
运行之后报错，删除了flutter的cache重新upgrade也不行

### ISSUE THREAD

**Issue by liangjw1603** [simplezhli/flutter_deer#22]
![image](https://user-images.githubusercontent.com/22829915/61262812-3ca8e200-a7b9-11e9-95c0-3ece55fe1bc6.png)
请问这是什么问题...

**Comment by simplezhli** [comment]
仔细看 
 https://github.com/simplezhli/flutter_deer#%E9%A1%B9%E7%9B%AE%E8%BF%90%E8%A1%8C%E7%8E%AF%E5%A2%83

**Comment by liangjw1603** [comment]
感谢感谢，粗心了
