### ISSUE TITLE
BaseEntity解析wanAndroidAPI的错误json的null转换

### ISSUE THREAD

**Issue by android-1995** [simplezhli/flutter_deer#220]
```
class BaseEntity<T> {
...
  T? _generateOBJ<O>(Object json) {
    if (T.toString() == 'String') {
      return json.toString() as T;
    } else if (T.toString() == 'Map<dynamic, dynamic>') {
      return json as T;
    } else {
      /// List类型数据由fromJsonAsT判断处理
      return JsonConvert.fromJsonAsT<T>(json);
    }
  }
}
```
![image](https://user-images.githubusercontent.com/35674533/191633848-4badb5dd-51d5-4aa9-be70-7241b87f8895.png)
<br/><br/><br/>个人修改后的代码：
```
class BaseEntity<T> {
  BaseEntity(this.code, this.message, this.data);

  BaseEntity.fromJson(Map<String, dynamic> json) {
    code = json[Constant.code] as int?;
    message = json[Constant.message] as String;
    if (json.containsKey(Constant.data)) {
      data = _generateOBJ<T>(json[Constant.data] as Object?);
    }
  }

  int? code;
  late String message;
  T? data;

  T? _generateOBJ<O>(Object? json) {
    if (json == null) {
      return null;
    }
    if (T.toString() == 'String') {
      return json.toString() as T;
    } else if (T.toString() == 'Map<dynamic, dynamic>') {
      return json as T;
    } else {
      /// List类型数据由fromJsonAsT判断处理
      return JsonConvert.fromJsonAsT<T>(json);
    }
  }
}
```

**Comment by simplezhli** [comment]
@android-1995 这里确实存在这种问题。但是我使用了`AdapterInterceptor `将数据进行了处理，会保证data不为null。
https://github.com/simplezhli/flutter_deer/blob/c1a0bc6087a310778111b489e7f86f7e5e8d48ab/lib/net/intercept.dart#L160-L168

**Comment by android-1995** [comment]
- -AdapterInterceptor 的数据格式和wanAndroidAPI的字段不一样，所以我去掉了

**Comment by simplezhli** [comment]
`AdapterInterceptor`的作用其实是为了兼容REST风格的API，统一用法。如果数据本身就是code、 msg、 data这种格式那么可以去掉。

data为null是需要你这样处理一下，或者说接口不返回data字段其实更好。

**Comment by android-1995** [comment]
好的 好的，感谢解答

**Comment by simplezhli** [comment]
没事，有问题多交流。

**Comment by android-1995** [comment]
还真有个问题哈
有event相关的组件吗？我看项目里好像没有类似的组件，设置页的夜间模式、多语言的值，不会及时更新

**Comment by simplezhli** [comment]
EventBus？flutter我记得有相关的库，但是主要还是用的状态管理。项目中的ThemeProvider 、LocaleProvider 就是做相关功能的。你说的不及时更新指的是什么。

**Comment by android-1995** [comment]
我修改了夜间模式，然后返回上个界面的值没变
![Screenshot_2022-09-22-10-27-09-469_com weilu deer](https://user-images.githubusercontent.com/35674533/191644923-3eca2859-f621-4e79-9e02-627859d83577.jpg)
![Screenshot_2022-09-22-10-27-17-073_com weilu deer](https://user-images.githubusercontent.com/35674533/191644932-c2a086a7-4f62-4468-a51b-e5c04175abfa.jpg)
![Screenshot_2022-09-22-10-27-19-906_com weilu deer](https://user-images.githubusercontent.com/35674533/191644940-41379c06-c972-457b-9ff2-6d758eba1bf9.jpg)

**Comment by simplezhli** [comment]
好吧，这是个bug。。。我抽时间修一修。

**Comment by android-1995** [comment]
是通过注册ThemeProvider的监听值的变化赋值吗？

**Comment by simplezhli** [comment]
是的，和`MyApp`那里一样，套个`Consumer2`就行了。
