### ISSUE TITLE
代码格式化风格

### ISSUE THREAD

**Issue by android-1995** [simplezhli/flutter_deer#221]
想问下作者用的什么编译器？
我用的Android studio的dart默认风格，代码格式化之后格式跟作者的不一样，感觉作者的格式更好一点。

**Comment by simplezhli** [comment]
我也用的Android Studio。但是我不习惯用格式化，都是写的时候手动换行空格处理的。

**Comment by android-1995** [comment]
😆原来是这样，我说咋能一行写的长。自动格式化一行都挺短的。

**Comment by simplezhli** [comment]
哈哈，程序哪有人灵活。
