### ISSUE TITLE
登录页等页面的密码输入框，用X清空后，数字输入无反应，字母输入可以

### ISSUE THREAD

**Issue by android-1995** [simplezhli/flutter_deer#222]
### 运行环境 ###

 设备型号：如：`红米k40`

### 具体问题描述 ###

```
showSoftInput() view=io.flutter.embedding.android.FlutterView{2f2cafe VFE...... .F...... 0,0-1080,2400 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
show(ime(), fromIme=true)
```
清空之后输入字母回出现一条上面的日志

**Comment by simplezhli** [comment]
@android-1995 我这边无法复现问题，你可以看看其他设备是否正常。另外你的flutter版本是多少？

**Comment by android-1995** [comment]
```
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"
```

**Comment by simplezhli** [comment]
> ```
> environment:
>   sdk: ">=2.17.0 <3.0.0"
>   flutter: ">=3.0.0 <4.0.0"
> ```

不是这个，用命令`flutter doctor`查看。

**Comment by android-1995** [comment]
```
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [版本 10.0.19042.2006], locale zh-CN)
    • Flutter version 3.0.1 at F:\flutter\flutter_windows_3.0.1-stable\flutter                
    • Upstream repository https://github.com/flutter/flutter.git                              
    • Framework revision fb57da5f94 (4 months ago), 2022-05-19 15:50:29 -0700                 
    • Engine revision caaafc5604                                                              
    • Dart version 2.17.1                                                                     
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```
这个吗？

**Comment by android-1995** [comment]
![image](https://user-images.githubusercontent.com/35674533/192989012-1ab0bf7c-658a-4ff8-8513-14e34af784bc.png)
AS设置的好像跟上面的不是一个版本

**Comment by simplezhli** [comment]
版本看这是最新的，这个问题我也不清楚原因。你可以去flutter下问问。

**Comment by android-1995** [comment]
我把系统环境变量换成3.3.2重新编译还是一样，真是个神奇的问题

**Comment by simplezhli** [comment]
可以做几个尝试：
1.去除`MyTextField`中的`inputFormatters`。
2.删除x点击代码`widget.controller.text = ''`，或是修改代码为`widget.controller.text  = '123xxx'`

**Comment by android-1995** [comment]
> 删除x点击代码widget.controller.text = ''

这个可以，但是感觉改了没啥意义
其他两种还是一样错误。

**Comment by android-1995** [comment]
啊 抱歉。可能是我改了什么代码出错了，demo正常的。

**Comment by simplezhli** [comment]
![04d33c2f-966a-401f-a46f-b49897570559](https://user-images.githubusercontent.com/12456431/192998636-550dcf9c-ac41-4d9d-a6d0-ea6f9395104b.gif)

**Comment by android-1995** [comment]
我重新确认了一下。
目前是直接安装https://www.pgyer.com/gYXj的apk是正常的，clone代码run的apk是有问题的。
flutter 3.3.2
clone后没改任何代码直接run的

**Comment by simplezhli** [comment]
@android-1995 apk我看了一下，最后更新时间是2021-04-26，这中间这块的代码没有功能上的改动。
那么就是两种可能，一个是flutter版本问题，另一个就是release包下是正常的。

**Comment by android-1995** [comment]
你用debug的包复现了吗？

**Comment by simplezhli** [comment]
没有，我这边测试了两台设备都是正常的。

**Comment by simplezhli** [comment]
https://user-images.githubusercontent.com/12456431/193208640-653d6a1a-4402-4738-acf8-6e8fdee869c6.mp4

**Comment by android-1995** [comment]
[app-release.zip](https://github.com/simplezhli/flutter_deer/files/9681552/app-release.zip)
这是我打的release包，我这边试了还是有这个问题

**Comment by simplezhli** [comment]
https://user-images.githubusercontent.com/12456431/193211050-752d9447-470b-4bd0-bfba-c9cccdc09ab0.mp4

是正常的

**Comment by android-1995** [comment]
是卸载后重装的吗？

**Comment by simplezhli** [comment]
没有，但我刚才卸载重装了，一样是正常的。

**Comment by android-1995** [comment]
啊  那只能解释为设备导致的了

**Comment by simplezhli** [comment]
flutter与软键盘这里的问题我至今遇到了好几个，大都是个别设备有问题，有些目前都没有修复。比如这段代码就是以前一个问题的处理：
https://github.com/simplezhli/flutter_deer/blob/c1a0bc6087a310778111b489e7f86f7e5e8d48ab/lib/login/widgets/my_text_field.dart#L130-L137

**Comment by android-1995** [comment]
嗯 我在设置里面关闭了“安全键盘”，然后就正常了
