### ISSUE TITLE
登录失败时出现了LateInitializationError

### ISSUE THREAD

**Issue by feitas** [simplezhli/flutter_deer#223]
### 运行环境 ###

- [x] 电脑系统：如：`Mac`
- [x] 设备型号：如：模拟器
- [x] 设备系统版本：模拟器
- [x] Flutter 版本：如 `3.0.4`

### 具体问题描述 ###
没系统学习过flutter，想对接一些数据，登录的时候，登录失败的时候遇到了下面的问题，登录成功的时候没有什么问题

flutter: DEER-LOG v  ----------Start-----loggingInterceptor-----
flutter: DEER-LOG v  RequestUrl: http://xxxxxxx:11091/api/auth/token?login=admin&password=admin&db=lims
flutter: DEER-LOG v  RequestMethod: GET
flutter: DEER-LOG v  RequestHeaders:{content-type: application/x-www-form-urlencoded, charset: utf-8, User-Agent: Mozilla/5.0}
flutter: DEER-LOG v  RequestContentType: application/x-www-form-urlencoded
flutter: DEER-LOG v  RequestData: null
flutter: DEER-LOG e  ResponseCode: 404
flutter: DEER-LOG v  ----------End: 87 毫秒----------
flutter: isCompute:false
flutter: DEER-LOG e  接口请求异常： code: 404, mag: 未找到查询信息
flutter: LateInitializationError: Field 'view' has not been initialized.
flutter: #0      BasePresenter.view (package:flutter_deer/mvp/base_presenter.dart)
flutter: #1      BasePagePresenter._onError (package:flutter_deer/mvp/base_page_presenter.dart:113:5)

**Comment by xueqiulou** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by simplezhli** [comment]
@feitas 登录失败的时候是有关闭页面吗？
