### ISSUE TITLE
Because every version of flutter_driver from sdk depends on vm_service 9.3.0 and integration_test >=1.0.2+2 depends on vm_service >=4.2.0 <7.0.0, flutter_driver from sdk is incompatible with integration_test >=1.0.2+2.

### ISSUE THREAD

**Issue by ch930410** [simplezhli/flutter_deer#224]
**I downloaded a flutter project on github and reported the following error during the attempt:**

Running "flutter pub get" in flutter_deer-master...             
Because every version of flutter_driver from sdk depends on vm_service 9.3.0 and integration_test >=1.0.2+2 depends on vm_service >=4.2.0 <7.0.0, flutter_driver from sdk is incompatible with integration_test >=1.0.2+2.
So, because flutter_deer depends on both flutter_driver from sdk and integration_test ^1.0.2+2, version solving failed.
pub get failed
command: "F:\flutter\flutter_windows_2.8.1-stable\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --verbosity=warning get --no-precompile"
pub env: {
  "FLUTTER_ROOT": "F:\flutter\flutter_windows_2.8.1-stable\flutter",
  "PUB_ENVIRONMENT": "vscode.dart-code:flutter_cli:get",
  "PUB_CACHE": "C:\Users\Administrator\AppData\Local\Pub\Cache",
}
exit code: 1
last line of pub output: "So, because flutter_deer depends on both flutter_driver from sdk and integration_test ^1.0.2+2, version solving failed."

exit code 1

**Comment by simplezhli** [comment]
你的flutter版本多少？目前项目需要保证3.3以上。

**Comment by simplezhli** [comment]
你的代码是最新的吗？

**Comment by simplezhli** [comment]
> > 你的flutter版本多少？项目前项目需要保3.3以上。
> 
> Flutter 3.3.8 • channel stable • https://github.com/flutter/flutter.git Framework • revision 52b3dc25f6 (8 days ago) • 2022-11-09 12:09:26 +0800 Engine • revision 857bd6b74c Tools • Dart 2.18.4 • DevTools 2.15.0
> 
> --pubspec.yaml----------- environment: sdk: ">=2.10.0 <3.0.0" flutter: ">=2.0.0"
> 
> dev_dependencies: // Widget测试 flutter_test: sdk: flutter //集成测试 flutter_driver: sdk: flutter //https://github.com/flutter/plugins/tree/master/packages/integration_test integration_test: ^1.0.2+2 // 黄金测试 // flutter_goldens: // sdk: flutter // 单元测试 test: ^1.16.5

看你发版本像是以前的代码了。

**Comment by ch930410** [comment]
> > > 你的flutter版本多少？项目前项目需要保3.3以上。
> > 
> > 
> > Flutter 3.3.8 • channel stable • https://github.com/flutter/flutter.git Framework • revision 52b3dc25f6 (8 days ago) • 2022-11-09 12:09:26 +0800 Engine • revision 857bd6b74c Tools • Dart 2.18.4 • DevTools 2.15.0
> > --pubspec.yaml----------- environment: sdk: ">=2.10.0 <3.0.0" flutter: ">=2.0.0"
> > dev_dependencies: // Widget测试 flutter_test: sdk: flutter //集成测试 flutter_driver: sdk: flutter //https://github.com/flutter/plugins/tree/master/packages/integration_test integration_test: ^1.0.2+2 // 黄金测试 // flutter_goldens: // sdk: flutter // 单元测试 test: ^1.16.5
> 
> 看你发的版本像是以前的代码了。

是的，很久之前的代码了。我是需要更新下`flutter_driver `吗？

**Comment by simplezhli** [comment]
不用，你重新拉一下我的代码就行了。

**Comment by ch930410** [comment]
呃，能否说下这个应该怎么处理，本身就是在学习这个。

**Comment by simplezhli** [comment]
。。。git重新拉一下最新代码，或者你重新下载我的代码运行。
