### ISSUE TITLE
使用了dio的封装库，closeProgress方法执行了 ，但是加载视图不消失。

### ISSUE THREAD

**Issue by shenchunxing** [simplezhli/flutter_deer#225]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 11`
- [x] 设备型号：如：`M1`
- [x] 设备系统版本：如 `Android 12`
- [x] Flutter 版本：如 `3.0.3`

**Comment by shenchunxing** [comment]
class DPLoginPresenter extends BasePagePresenter<LoginIMvpView> {
  Future<dynamic> login(String username, String password) async {
    final Map<String, String> params = <String, String>{};
    params['username'] = username;
    params['saltType'] = '2';
    return requestNetwork<SaltEntity>(
        Method.post, url:HttpApi.getsalt,
        params: params, onSuccess: (data) {
    });
  }

**Comment by simplezhli** [comment]
加载视图有改动吗？或者有其他改动吗？

**Comment by shenchunxing** [comment]
> 加载视图有改动吗？或者有其他改动吗？

什么都没改动的，我也觉得很奇怪，查看了传入的context也是保持一致的，我这么使用应该是没问题的吧。刚入手flutter。

**Comment by shenchunxing** [comment]
> 加载视图有改动吗？或者有其他改动吗？

closeprogress里面的调用Navigator.of(context).pop.这个执行了的，还是无法关闭加载视图。这个和使用的路由框架么关系的吧，我用的是flutter_boost的。

**Comment by simplezhli** [comment]
> > 加载视图有改动吗？或者有其他改动吗？
> 
> closeprogress里面的调用Navigator.of(context).pop.这个执行了的，还是无法关闭加载视图。这个和使用的路由框架么关系的吧，我用的是flutter_boost的。

如果使用了flutter_boost，路由操作就需要使用`BoostNavigator` API。具体使用你可以看它的文档。

**Comment by shenchunxing** [comment]
> > > 加载视图有改动吗？或者有其他改动吗？
> > 
> > 
> > closeprogress里面的调用Navigator.of(context).pop.这个执行了的，还是无法关闭加载视图。这个和使用的路由框架么关系的吧，我用的是flutter_boost的。
> 
> 如果使用了flutter_boost，路由操作就需要使用`BoostNavigator` API。具体使用你可以看它的文档。


因为我是在登录页进行的操作，没有涉及到路由跳转，不是路由的原因。我试了还是关不了

**Comment by shenchunxing** [comment]
![Uploading 截屏2022-11-19 13.06.34.png…]()

**Comment by shenchunxing** [comment]
_login() async {
    _loginPresenter.login(_unameController.text,_pwdController.text);
  }
这是调用的代码，不知道哪里不对

**Comment by simplezhli** [comment]
建议你还是仔细阅读flutter_boost的文档，这里不解答其他框架的使用问题。如果你去除了flutter_boost后有同样的问题，欢迎反馈。

**Comment by shenchunxing** [comment]
> 建议你还是仔细阅读flutter_boost的文档，这里不解答其他框架的使用问题。如果你去除了flutter_boost后有同样的问题，欢迎反馈。

不是，我的意思是这个不是flutter_boost导致的问题，我这边的这个页面是第一个页面，不存在push和pop，就是点击了登录按钮，进行了登录接口的操作，会展示toast，但是接口调用结束，还是关闭不了该toast。

**Comment by shenchunxing** [comment]
代码我发你邮箱？，可以麻烦给我看下吗？

**Comment by simplezhli** [comment]
我已经说了是flutter_boost的问题导致dialog无法正常关闭，如果你知道它的原理你就明白我的意思了，你可以去它的项目下面问如何处理，不要在错误的方向上纠结了。

**Comment by simplezhli** [comment]
@shenchunxing 帮你看了一下代码，flutter_boost配置有问题。。。你仔细看一下文档：https://github.com/alibaba/flutter_boost/blob/master/docs/install.md#dart部分   

```dart
Widget appBuilder(Widget home) {
    return MaterialApp(
      home: home,
      debugShowCheckedModeBanner: true,

      ///必须加上builder参数，否则showDialog等会出问题
      builder: (_, __) {
        return home;
      },
    );
  }
```
加上就好了。。。

**Comment by shenchunxing** [comment]
好的，。感谢。这个注释以前我看到的，一直没理解也没注意。估计什么时候被我删了。想不到就出现这种问题。感谢感谢。刚一个人入手应公司要求入手flutter，以你的deer项目为引导了。👍🏻




ShenChunXing
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "simplezhli/flutter_deer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月19日(星期六) 下午2:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [simplezhli/flutter_deer] 使用了dio的封装库，closeProgress方法执行了 ，但是加载视图不消失。 (Issue #225)





 
@shenchunxing 帮你看了一下代码，flutter_boost配置有问题。。。你仔细看一下文档：https://github.com/alibaba/flutter_boost/blob/master/docs/install.md#dart部分
 Widget appBuilder(Widget home) {     return MaterialApp(       home: home,       debugShowCheckedModeBanner: true,       ///必须加上builder参数，否则showDialog等会出问题       builder: (_, __) {         return home;       },     );   }
 
加上就好了。。。

**Comment by simplezhli** [comment]
个人精力有限，不解答此项目外的使用问题，下不为例。🤝

**Comment by shenchunxing** [comment]
ShenChunXing
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "simplezhli/flutter_deer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月19日(星期六) 下午3:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [simplezhli/flutter_deer] 使用了dio的封装库，closeProgress方法执行了 ，但是加载视图不消失。 (Issue #225)





 
个人精力有限，不解答此项目外的使用问题，下不为例。🤝
