### ISSUE TITLE
FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by ch930410** [simplezhli/flutter_deer#226]
Flutter 3.4.0-17.2.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision d6260f127f (9 weeks ago) • 2022-09-21 13:33:49 -0500
Engine • revision 3950c6140a
Tools • Dart 2.19.0 (build 2.19.0-146.2.beta) • DevTools 2.16.0

在执行flutter run 报错如下：
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to F:\flutter\project\flutter_deer\android\app\build.gradle:
android {
  compileSdkVersion 33
  ...
}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction     
   > An issue was found when checking AAR metadata:

       1.  Dependency 'androidx.webkit:webkit:1.5.0' requires libraries and applications that
           depend on it to compile against version 32 or later of the
           Android APIs.

           :app is currently compiled against android-31.

           Recommended action: Update this project to use a newer compileSdkVersion
           of at least 32, for example 32.

           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

======根据上面的错误，修改`compileSdkVersion`的值为33，然后再次执行会抛出下面的错误 ===================

F:\flutter\project\flutter_deer\android\app\src\debug\AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 16 cannot be smaller than version 20 declared in library [:qr_code_scanner] F:\flutter\project\flutter_deer\build\qr_code_scanner\intermediates\merged_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 20,
                or use tools:overrideLibrary="net.touchcapture.qr.flutterqr" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

│   }                                                                                                          │
│ }                                                                                                            │
│                                                                                                              │
│                                                                                                              │
│ Note that your app won't be available to users running Android SDKs below 20.                                │
│ Alternatively, try to find a version of this plugin that supports these lower versions of the Android SDK.   │
│ For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration

**Comment by simplezhli** [comment]
Flutter版本保持和项目一致后在尝试，3.4.0目前不清楚有什么兼容问题。

**Comment by ch930410** [comment]
sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

在这区间里

**Comment by simplezhli** [comment]
如果这个区间给你带来了误解，我很抱歉。但这个通常只是一个最低版本的限制，但对于高版本谁也不知道未来是否有其他变化。

**Comment by ch930410** [comment]
> 如果这个区间给你带来了误解，我很抱歉。但这个通常只是一个最低版本的限制，但对于高版本谁也不知道未来是否有其他变化。

好的，咱们这能不能对一些项目运行过程中常见的问题写入到`README.md`里？比如我后面那个错误，虽然我改成20 可以运行起来项目，但是控制台会报错：`ERROR:D8: Cannot fit requested classes in a single dex file (# methods: 78809 > 65536`；经查后需要设置最低版本为21 才没有其他错误；

**Comment by simplezhli** [comment]
> > 如果这个区间给你带来了误解，我很抱歉。但这个通常只是一个最低版本的限制，但对于高版本谁也不知道未来是否有其他变化。
> 
> 好的，咱们这能不能对一些项目运行过程中常见的问题写入到`README.md`里？比如我后面那个错误，虽然我改成20 可以运行起来项目，但是控制台会报错：`ERROR:D8: Cannot fit requested classes in a single dex file (# methods: 78809 > 65536`；经查后需要设置最低版本为21 才没有其他错误；

我的代码提交后，通过了github action的集成测试，所以正常来说不会存在运行问题。只要你的运行环境和flutter版本和我的一致就行。通过你的描述，我感觉你的代码并不我的最新代码。

https://github.com/simplezhli/flutter_deer/blob/74dcf743283ac07072844e0c1b4de4edd7d6e9ef/android/app/build.gradle#L40-L46

**Comment by ch930410** [comment]
> > > 如果这个区间给你带来了误解，我很抱歉。但这个通常只是一个最低版本的限制，但对于高版本谁也不知道未来是否有其他变化。
> > 
> > 
> > 好的，咱们这能不能对一些项目运行过程中常见的问题写入到`README.md`里？比如我后面那个错误，虽然我改成20 可以运行起来项目，但是控制台会报错：`ERROR:D8: Cannot fit requested classes in a single dex file (# methods: 78809 > 65536`；经查后需要设置最低版本为21 才没有其他错误；
> 
> 我的代码提交后，通过了github action的集成测试，所以正常来说不会存在运行问题。只要你的运行环境和flutter版本和我的一致就行。通过你的描述，我感觉你的代码并不我的最新代码。
> 
> https://github.com/simplezhli/flutter_deer/blob/74dcf743283ac07072844e0c1b4de4edd7d6e9ef/android/app/build.gradle#L40-L46

之前一直失败，所以我把各端资源包给删了，执行了一次 `flutter create .`

**Comment by simplezhli** [comment]
Android，iOS的文件都有相关的代码改动，你直接删了后面还有会有其他问题。还是那句话，只要你的代码和flutter版本和此项目的保持一致，运行不会有问题的。
