### ISSUE TITLE
项目刚导入进行pub get报错。

### ISSUE THREAD

**Issue by MixRabbit** [simplezhli/flutter_deer#228]
`Generating synthetic localizations package failed with 1 error:
Exception: Found syntax errors.`
在网上查了说是本地化文件的语法有问题。但是不知道如何解决。

**Comment by simplezhli** [comment]
@MixRabbit 参考https://github.com/simplezhli/flutter_deer/issues/227

**Comment by China-Xuruize** [comment]
请问有交流群吗，想一起学习一下。。。。
