### ISSUE TITLE
请问一下 是否考虑结合Provider 开发多语言切换功能呢 ？

### ISSUE THREAD

**Issue by androidCoderxiao** [simplezhli/flutter_deer#23]

**Comment by simplezhli** [comment]
我可以尝试一下，不过可能需要一定的时间。你也可以提PR，哈哈！

**Comment by androidCoderxiao** [comment]
主要我对这一块掌握的还不够 ，想问问你有没有思路 哈哈 ~~~

**Comment by simplezhli** [comment]
思路并不难，就是全局的变量。Provider套在MaterialApp上就行了。哪里需要显示文字，通过Provider去获取判断就行了。

**Comment by simplezhli** [comment]
实现完整的功能的话，我就需要改动的地方多了。。。
