### ISSUE TITLE
5月22日刚拉代码 一直卡在 Running Gradle task 'assembleDebug'...

### ISSUE THREAD

**Issue by han1548772930** [simplezhli/flutter_deer#232]
### 运行环境 ###

-  电脑系统：：`Windows 11`
-  设备系统版本： `Android 13`
-  Flutter 版本： `3.10.0`
-  Java版本：`17`
### 具体问题描述 ###
我的 gradle-7.3.3 也是从网上下载下来 然后手动覆盖的
![微信截图_20230522204225](https://github.com/simplezhli/flutter_deer/assets/83765419/c210504c-1e90-4aa1-9429-3c7814e2942d)

#### 问题截图 ####
![微信截图_20230522204107](https://github.com/simplezhli/flutter_deer/assets/83765419/d522720d-cda2-4982-8773-1ea13db519e8)

**Comment by han1548772930** [comment]
还是卡在这里

**Comment by han1548772930** [comment]
我的小demo 
https\://services.gradle.org/distributions/gradle-7.5-all.zip

**Comment by han1548772930** [comment]
我用我demo的gradle还是不行 一直卡在那里  但是demo可以运行

**Comment by han1548772930** [comment]
如果我不把 -XX:MaxPermSize=1024m删除 就报这个错误了
![image](https://github.com/simplezhli/flutter_deer/assets/83765419/dff1cb7a-9ef6-4efc-bde2-de00ffd0aef5)

**Comment by han1548772930** [comment]
已经点小星星了 作者大大帮帮我 😭😭😭😭

**Comment by simplezhli** [comment]
卡住的原因不一定是gradle，下载kotlin相关包也比较耗时，而且引用的三方库中的kotlin也会下载，版本多了下载时间就长了。但是我项目中已经配置了阿里云的镜像，不清楚为什么还是这么慢。你再试试用Android Studio直接打开android目录运行，右下角会有下载进度。

**Comment by han1548772930** [comment]
右下角疯狂下载中

**Comment by han1548772930** [comment]
![image](https://github.com/simplezhli/flutter_deer/assets/83765419/f3122d6f-a80a-4ae8-932d-d3795588a1a1)

**Comment by simplezhli** [comment]
@han1548772930  运行起来就好，`Invalid image data`是有几张图片地址失效了，是图片框架报的，不影响的。

**Comment by han1548772930** [comment]
原來是作者大大故意留了几张失效的网图 我改了就正常了
