### ISSUE TITLE
纯新手，想问下'package:flutter_deer/widgets/my_app_bar.dart'里的flutter_deer是个包吗

### ISSUE THREAD

**Issue by taoman** [simplezhli/flutter_deer#233]
并且在pubspec.yaml需要引入吗

**Comment by simplezhli** [comment]
@taoman flutter_deer是项目名，如果放在其他项目中，需要重新导路径。

**Comment by taoman** [comment]
import 'package:flutter_deer/widgets/my_app_bar.dart';
会提示
Target of URI doesn't exist: 'package:flutter_deer/widgets/my_app_bar.dart'.
Try creating the file referenced by the URI, or try using a URI for a file that does exist.dart[uri_does_not_exist](https://dart.dev/diagnostics/uri_does_not_exist)
The imported package 'flutter_deer' isn't a dependency of the importing package.
Try adding a dependency for 'flutter_deer' in the 'pubspec.yaml' file.
这个不就是没有包导致的吗，可是我又没找到'flutter_deer' 这个相关的包，还请指教

**Comment by taoman** [comment]
> @taoman flutter_deer是项目名，如果放在其他项目中，需要重新导路径。
import 'package:flutter_deer/widgets/my_app_bar.dart';
会提示
Target of URI doesn't exist: 'package:flutter_deer/widgets/my_app_bar.dart'.
Try creating the file referenced by the URI, or try using a URI for a file that does exist.dart[uri_does_not_exist](https://dart.dev/diagnostics/uri_does_not_exist)
The imported package 'flutter_deer' isn't a dependency of the importing package.
Try adding a dependency for 'flutter_deer' in the 'pubspec.yaml' file.
这个不就是没有包导致的吗，可是我又没找到'flutter_deer' 这个相关的包，还请指教

**Comment by simplezhli** [comment]
这个文件在[这里](https://github.com/simplezhli/flutter_deer/blob/master/lib/widgets/my_app_bar.dart)。需要的文件可以在项目里面根据相对路径查找。

**Comment by taoman** [comment]
> 这个文件在[这里](https://github.com/simplezhli/flutter_deer/blob/master/lib/widgets/my_app_bar.dart)。需要的文件可以在项目里面根据相对路径查找。

好的，非常感谢
