### ISSUE TITLE
fluro的使用

### ISSUE THREAD

**Issue by YuQi9797** [simplezhli/flutter_deer#234]
作者您好，感谢您提供的项目，使我受益匪浅。

我想问一问作者封装的路由工具类 NavigatorUtils 中，我如何通过自定义的router传值“对象”呢？    
在自定义的Router中  router.define() 里 handler 的参数是` Map<String, List<String>> params`.  如果我想在跳转页面时，传参一个对象，似乎不行。 请问该如何解决呢？ 

谢谢！

**Comment by simplezhli** [comment]
@YuQi9797 你看需要的是不是这个：https://github.com/lukepighetti/fluro#class-arguments

**Comment by YuQi9797** [comment]
奥奥奥！ 是的！&nbsp; 谢谢！&nbsp; &nbsp;是我蠢了，没查到.. 感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月18日(星期五) 下午4:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [simplezhli/flutter_deer] fluro的使用 (Issue #234)





 
@YuQi9797 你看需要的是不是这个：https://github.com/lukepighetti/fluro#class-arguments
