### ISSUE TITLE
Failed to connect to the VM observatory service at: ws://127.0.0.1:64266/PbgpFj8Gfhg=/ws

### ISSUE THREAD

**Issue by 284658474** [simplezhli/flutter_deer#235]
### 运行环境 ###

- [x] 电脑系统：如：`mac pro`
- [x] 设备型号：如：`iphone 14 pro max`
- [x] 设备系统版本：如 `Android 13`
- [x] Flutter 版本：如 `3.10.0`

### 具体问题描述 ###
3.10.0版本以上包含 3.13.0版本  都有这个问题，请问如何解决
#### 问题截图 ####
<img width="1062" alt="image" src="https://github.com/simplezhli/flutter_deer/assets/35591968/6f6aa0d7-30d5-4b10-8fdd-6fa70e41fe4a">

<img width="1201" alt="image" src="https://github.com/simplezhli/flutter_deer/assets/35591968/cb871078-3604-4b49-9167-de3b62b806e3">

<img width="1193" alt="image" src="https://github.com/simplezhli/flutter_deer/assets/35591968/fbe6cb8a-161b-4e8b-b611-33a8dba0d52d">

#### 异常日志 ####
Incompatible protocol version: client=3.26 vm=4.4
Failed to connect to the VM observatory service at: ws://127.0.0.1:64266/PbgpFj8Gfhg=/ws
java.io.IOException: Incompatible protocol version: client=3.26 vm=4.4

**Comment by simplezhli** [comment]
不知道你的其他项目运行是否正常，感觉是环境问题。试试再切换渠道更新一下。
```
flutter channel stable
flutter upgrade --force
```

**Comment by 284658474** [comment]
最终解决版本，重新安装Android Studio

**Comment by simplezhli** [comment]
好的，解决了就好
