### ISSUE TITLE
android运行报错，望指点一二

### ISSUE THREAD

**Issue by Hyottoko** [simplezhli/flutter_deer#236]
<img width="1351" alt="截屏2023-10-08 19 02 41" src="https://github.com/simplezhli/flutter_deer/assets/12294442/c7581b7b-ef49-497b-bd52-c249f25b328f">

**Comment by simplezhli** [comment]
怀疑是flutter版本不对，看是否是3.13版本

**Comment by Hyottoko** [comment]
> 怀疑是flutter版本不对，看是否是3.13版本

我的版本是3.16.0-6.0.pre.34

**Comment by simplezhli** [comment]
高于3.13版本并未适配，建议使用stable渠道。

**Comment by Hyottoko** [comment]
> 高于3.13版本并未适配，建议使用stable渠道。

嗯嗯，谢谢。

**Comment by Hyottoko** [comment]
> 高于3.13版本并未适配，建议使用stable渠道。

非常感谢你的指点，我由master切换到stable后，可以编译运行使用了

**Comment by simplezhli** [comment]
> > 高于3.13版本并未适配，建议使用stable渠道。
> 
> 非常感谢你的指点，我由master切换到stable后，可以编译运行使用了

好的，那我就关闭这个issue了。
