### ISSUE TITLE
为什么不用riverpod

### ISSUE THREAD

**Issue by JasonYinH** [simplezhli/flutter_deer#238]
为什么不用riverpod

**Comment by simplezhli** [comment]
历史原因是写这个项目的时候还没有riverpod。虽然我个人也倾向riverpod，日常开发也是首选。对于这个项目的使用场景来说provider足够了，还没到必须要替换的程度，

**Comment by JasonYinH** [comment]
大佬，直接用您的作为项目开发框架，把provider迁移到riverpod好迁移吗，我是flutter小白

**Comment by simplezhli** [comment]
如果你不要需要语言，暗黑的切换那还是比较简单的可以删除provider。因为主要就是这里在用。如果需要，要稍微会一点provider，这样方便替换。

**Comment by JasonYinH** [comment]
谢谢佬，不需要语言
