### ISSUE TITLE
120hz刷新率问题请教

### ISSUE THREAD

**Issue by Ymmmsick** [simplezhli/flutter_deer#239]
### 运行环境 ###
[!] Flutter (Channel stable, 3.13.8, on Microsoft Windows [版本 10.0.19045.3570], locale zh-CN)
    ! Warning: `flutter` on your path resolves to D:\Dev\fvm\versions\3.13.8\bin\flutter, which
      is not inside your current Flutter SDK checkout at
      C:\Users\Administrator.DESKTOP-RA9U50C\fvm\default. Consider adding
      C:\Users\Administrator.DESKTOP-RA9U50C\fvm\default\bin to the front of your path.
    ! Warning: `dart` on your path resolves to D:\Dev\fvm\versions\3.13.8\bin\dart, which is
      not inside your current Flutter SDK checkout at
      C:\Users\Administrator.DESKTOP-RA9U50C\fvm\default. Consider adding
      C:\Users\Administrator.DESKTOP-RA9U50C\fvm\default\bin to the front of your path.
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.3)
[√] Android Studio (version 2022.3)
[√] Connected device (6 available)
- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米13 miu14`
- [x] 设备系统版本：如 `Android 14`
- [x] Flutter 版本：如 `3.13.8`

### 具体问题描述 ###
在我的小米13手机上（miui 14 android14）运行您的项目可以正常以120hz运行，但是我自己的项目中却被锁定了60hz，是有做什么特殊处理吗？按道理说如果小米检测到应用界面都是surfaceview绘制的，都应该限制才对，但是您的项目并不会限制锁60hz，很疑惑，我试了好几个应用，其中有一半是锁了60hz
#### 问题截图 ####
![image](https://github.com/simplezhli/flutter_deer/assets/5235312/b9d0f7fb-460b-4404-a3ba-677034f7237b)
![image](https://github.com/simplezhli/flutter_deer/assets/5235312/a1dc424a-459e-4851-bb3e-ef2e800ddf52)

**Comment by Ymmmsick** [comment]
对比了一下日志您的项目中没有输出以下日志（***Support Dynamic FPS.）：
I/hanjingyuan.app(11260): DF com.wuhanjingyuan.app Support Dynamic FPS.
但是我又并没有特殊设置过什么支持动态fps

**Comment by simplezhli** [comment]
项目中没有对刷新率做额外处理。不过有个插件可以设置高刷，你可以试试。https://github.com/ajinasokan/flutter_displaymode

**Comment by simplezhli** [comment]
@Ymmmsick 我在自己的vivo手机观察了一下，在系统默认的“智能切换”下，我手机上的几款flutter应用都是锁死的60hz。部分原生应用应该是有适配，可以到120hz。

**Comment by Ymmmsick** [comment]
这边找到原因了，在我的小米13上，我打出release包能够正常运行120hz，debug包会被锁定60，暂时不用管了，由于手上没有ov的手机，没有办法测试，昨天咨询过其他人有案例oppo能通过 https://github.com/ajinasokan/flutter_displaymode 这个方案解锁60hz，感谢您的解答
