### ISSUE TITLE
build时报错

### ISSUE THREAD

**Issue by CCodeInspect** [simplezhli/flutter_deer#242]
### 运行环境 ###

- [x] 电脑系统：如：`macos `
- [x] 设备型号：如：`小米13`
- [x] 设备系统版本：如 `14.1 `
- [x] Flutter 版本：如 ’Flutter 3.16.5 • channel stable • https://github.com/flutter/flutter.git‘

### 具体问题描述 ###

**build时报错**

    cd /Users/xxx/code/flutter_deer/ios/Pods
    /usr/bin/touch -c /Users/stackdin/Library/Developer/Xcode/DerivedData/Runner-gdwjkdohnxfjosbmbjkwjqfzgpof/Build/Products/Debug-iphoneos/FMDB/FMDB.framework
#### 问题截图 ####
![image](https://github.com/simplezhli/flutter_deer/assets/44918169/7c11193c-9c64-418b-8a65-9d8ea596fddf)

**Comment by simplezhli** [comment]
是运行的iOS吗，xcode是15.0吗？

**Comment by CCodeInspect** [comment]
> xcode是15.0吗？试一下我提交的最新代码。

回复晚了，是15.0
![image](https://github.com/simplezhli/flutter_deer/assets/44918169/fa1bdc7e-7656-4979-85af-482f5fb7c43c)

**Comment by CCodeInspect** [comment]
> xcode是15.0吗？试一下我提交的最新代码。

晚点去验证一下是不是xcode的问题，看现在能不能跑通。
