### ISSUE TITLE
请问一下

### ISSUE THREAD

**Issue by ylmyg** [simplezhli/flutter_deer#243]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 11`
- [x] 设备型号：如：`华为`
- [x] 设备系统版本：如 `Android 13`
- [x] Flutter 版本：如 `3.16.0`

### 具体问题描述 ###
请问一下，我公司对git拉取做了限制，拉取不下，像这里依赖获取该怎么办，可以从pub拉取，git不行，pub没有找到相应的库			 
 flutter_2d_amap:
    git:
      ref: '3850a4dc'
      url: 'https://github.com/simplezhli/flutter_2d_amap.git'

**Comment by simplezhli** [comment]
@ylmyg 如果可以下载代码到本地（https://github.com/simplezhli/flutter_2d_amap ），用本地路径替换url。
```
flutter_2d_amap:
  path: ../flutter_2d_amap
```

**Comment by baishengye** [comment]
把https的链接替换成ssh的链接就可以了，亲测有效

**Comment by ylmyg** [comment]
@simplezhli 是下载整个文件到本地，放在和项目相同目录的层级，然后根据目录去引入么（没有用到这种方式，不太懂），我下载amap到本地了，然后直接把amaplib里面所有的文件拷贝到deer里面，不知这种方式可以么？

**Comment by baishengye** [comment]
# 高德2D地图插件（支持Web） https://github.com/simplezhli/flutter_2d_amap
  flutter_2d_amap:
    git:
      ref: '3850a4dc'
      url: 'git@github.com:simplezhli/flutter_2d_amap.git'
我是这样写的，可以正常拉取

**Comment by ylmyg** [comment]
@baishengye 不行的，我们公司对于所有后缀名为.git路径都屏蔽下拉了

**Comment by ylmyg** [comment]
![1706865240956](https://github.com/simplezhli/flutter_deer/assets/7122217/5d22f126-a2c0-420a-b543-a630035971ea)
请问一下，我导入了本地的amap，运行以后出现这种情况会是什么问题呢。

**Comment by baishengye** [comment]
@ylmyg 迂回一下，官方的拉不下来，就把官方的仓库fork下来，然后用自己的连接

**Comment by ylmyg** [comment]
有一说一，这个项目做得确实漂亮。

**Comment by simplezhli** [comment]
@ylmyg 感谢你的认可，没问题就好。

**Comment by ylmyg** [comment]
@simplezhli 初学者，很多东西看不太懂
