### ISSUE TITLE
HttpException: Connection closed before response was received

### ISSUE THREAD

**Issue by dasewan** [simplezhli/flutter_deer#244]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`红米K60`
- [x] 设备系统版本：如 `Android 13`
- [x] Flutter 版本：如 `3.19.0`
- [x] fluro: ^2.0.5
- [x] dio: ^5.4.0

### 具体问题描述 ###
登录页面登录成功后跳转首页。首页请求接口数据报错。

这个问题是flutter3.10升级3.19后出现的问题，会出现网络请求中断错误，奇怪的是，我打开断点调试模式后，就可以正常请求
I/flutter ( 7325): DioException [unknown]: null
I/flutter ( 7325): Error: HttpException: Connection closed before response was received, uri = http://api.dasewan.cn/api/v1/indexno

#### 问题截图 ####
![image](https://github.com/simplezhli/flutter_deer/assets/8346782/7e1a1273-7330-4834-9861-9beb0e2c5675)

![image](https://github.com/simplezhli/flutter_deer/assets/8346782/0357f314-85aa-42d9-92b5-e4c4a2538b93)

![image](https://github.com/simplezhli/flutter_deer/assets/8346782/3be1d237-4ec3-4a3e-8fab-e9f0ebcc0324)

**Comment by simplezhli** [comment]
根据你的描述，还有我看到`LoginPage`在请求时才触发`dispose`。感觉和这里有点关系。`dispose`里是不是有`CancelToken`的cancel。

**Comment by simplezhli** [comment]
我找了3.16.9版本，也是类似。
![image](https://github.com/simplezhli/flutter_deer/assets/12456431/5276e149-f703-4af5-8294-27c242fb0aa1)

**Comment by dasewan** [comment]
是呀大佬，为什么登录页面已经跳转首页了，首页initState后，登录页才dispose呢，然后登录页就把首页的接口给cancel了。升级前好好的

**Comment by dasewan** [comment]
从表现看来，NavigatorUtils.push(context, Routes.home, clearStack: true);这个会触发dispose。而不加clearStack: true参数，就不会触发dispose。但是这个生命周期的顺序令人迷惑

**Comment by simplezhli** [comment]
你试试`addPostFrameCallback`请求接口时，再延时一点看会不会有这个问题，

**Comment by simplezhli** [comment]
我看了一下3.10.6，也是这个顺序，所以有点不清楚问题的原因了，哈哈。

**Comment by dasewan** [comment]
![image](https://github.com/simplezhli/flutter_deer/assets/8346782/5b29413d-a3b1-480d-a1e0-c7ce6c3e86fb)
您是这个意思吗？这样确实可以屏蔽这个问题，但是两个页面的生命周期还是错乱的

**Comment by simplezhli** [comment]
也不算错乱，安装原生也是类似的。打开一个页面的同时，上个页面finish触发onDestroy就在新页面创建以后。比较奇怪的是上个页面的CancelToken为什么会影响新页面。这两个页面也不是一个CancelToken对象。

**Comment by dasewan** [comment]
谢谢
