### ISSUE TITLE
AndroidStudio Koala更新到AndroidStudio Ladybug,安卓环境报错

### ISSUE THREAD

**Issue by yoyoyoyolol** [simplezhli/flutter_deer#246]
FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'D:\flutter_deer\android\settings.gradle' (C:\Users\XXXX\.gradle\caches\7.5\scripts\409v0i3wan4qwdk50sbbb9ach).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 618ms

┌─ Flutter Fix ───────────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project's Gradle version is incompatible with the Java version that Flutter is using   │
│ for Gradle.                                                                                     │
│                                                                                                 │
│ If you recently upgraded Android Studio, consult the migration guide at                         │
│ https://flutter.dev/to/to/java-gradle-incompatibility.                                          │
│                                                                                                 │
│ Otherwise, to fix this issue, first, check the Java version used by Flutter by running `flutter │
│ doctor --verbose`.                                                                              │
│                                                                                                 │
│ Then, update the Gradle version specified in                                                    │
│ D:\Coding\Flutter\LeonProject\flutter_deer\android\gradle\wrapper\gradle-wrapper.properties to  │
│ be compatible with that Java version. See the link below for more information on compatible     │
│ Java/Gradle versions:                                                                           │
│ https://docs.gradle.org/current/userguide/compatibility.html#java                               │
│                                                                                                 │
│                                                                                                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────┘
Error: Gradle task assembleDebug failed with exit code 1

这个怎么解决,大佬指点一下

**Comment by simplezhli** [comment]
@yoyoyoyolol 你发的错误信息里面已经有了答案，是使用的java版本和gradle不兼容。一个就是检查java版本，估计是项目现在用的java版本高于18，可以选择较低的版本。或者就是升级gradle。

**Comment by yoyoyoyolol** [comment]
问题已解决
如果使用jdk17的话可以参考这个问题: [https://github.com/flutter/flutter/issues/156111](url)
如果想更新使用jdk21和最新的gradle版本参考这个[https://github.com/flutter/flutter/issues/156307](url)

**Comment by yoyoyoyolol** [comment]
> @yoyoyoyolol 你发的错误信息里面已经有了答案，是使用的java版本和gradle不兼容。一个就是检查java版本，估计是项目现在用的java版本高于18，可以选择较低的版本。或者就是升级gradle。

问题已解决,感谢回复
