### ISSUE TITLE
Xcode16编译运行报错误

### ISSUE THREAD

**Issue by samuel-codes** [simplezhli/flutter_deer#247]
Xcode16编译运行报错误：
Error (Xcode): double-quoted include "SqfliteImportPublic.h" in framework header, expected angle-bracketed instead
/Users/admin/Desktop/flutter_deer-master/ios/Pods/Target%20Support%20Files/sqflite_darwin/sqflite_darwin-umbrella.h:12:8

Error (Xcode): 'Flutter/Flutter.h' file not found
/Users/admin/.pub-cache/hosted/pub.dev/sqflite_darwin-2.4.1-1/darwin/sqflite_darwin/Sources/sqflite_darwin/include/sqflite_darwin/SqfliteImportPublic.h:14:8

Error (Xcode): (fatal) could not build module 'sqflite_darwin'
/Users/admin/Library/Developer/Xcode/DerivedData/Runner-grtyjtfdcvsafieslyxlrrswkvhi/Build/Intermediates.noindex/Pods.build/Release-iphoneos/sqflite_darwin.build/VerifyModule/sqflite_darwin_objec
tive-c++_arm64-apple-ios12.0_gnu++20/Test/Test.framework/Headers/Test.h:0:8

Error (Xcode): (fatal) could not build module 'Test'
/Users/admin/Library/Developer/Xcode/DerivedData/Runner-grtyjtfdcvsafieslyxlrrswkvhi/Build/Intermediates.noindex/Pods.build/Release-iphoneos/sqflite_darwin.build/VerifyModule/sqflite_darwin_objec
tive-c++_arm64-apple-ios12.0_gnu++20/Test/Test.mm:0:8

Error (Xcode): (fatal) could not build module 'sqflite_darwin'
/Users/admin/Library/Developer/Xcode/DerivedData/Runner-grtyjtfdcvsafieslyxlrrswkvhi/Build/Intermediates.noindex/Pods.build/Release-iphoneos/sqflite_darwin.build/VerifyModule/sqflite_darwin_objec
tive-c_arm64-apple-ios12.0_gnu17/Test/Test.framework/Headers/Test.h:0:8

**Comment by simplezhli** [comment]
@samuel-codes 提供一下你的运行环境，尽量保证和本项目（3.24.0）一致。同时可以尝试参考：https://github.com/flutter/flutter/issues/157761
