### ISSUE TITLE
请问项目里intl_en.arb文件第一行有个@@last_modified，这个文件是用了什么工具生成的吗？

### ISSUE THREAD

**Issue by yoyoyoyolol** [simplezhli/flutter_deer#248]
![Screenshot 2024-11-04 at 9 53 21 PM](https://github.com/user-attachments/assets/67f74f99-4850-4304-8efa-946675a0c18a)
我看项目里提供的这个文档地址 [https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization](url)   intl_en.arb这个文件都是手动编辑的，为什么最顶上会有这个最后修改的时间戳？

**Comment by simplezhli** [comment]
@yoyoyoyolol 这个是很早以前多语言的一种处理方法，通过资源配置生成arb文件。有兴趣可以参看：https://www.jianshu.com/p/82c6656462b8  ，后面迁移到了官方的推荐方案，这个文件信息保留了下来。

**Comment by yoyoyoyolol** [comment]
> @yoyoyoyolol 这个是很早以前多语言的一种处理方法，通过资源配置生成arb文件。有兴趣可以参看：https://www.jianshu.com/p/82c6656462b8 ，后面迁移到了官方的推荐方案，这个文件信息保留了下来。
感谢解答了我的疑问
