### ISSUE TITLE
疑问: 为什么本地虚拟设备启动了, 运行很卡呢.

### ISSUE THREAD

**Issue by Dssssds** [simplezhli/flutter_deer#249]
### 运行环境 ###

- [x] 电脑系统：如：`mac m1 pro`
- [x] 设备型号：如：`ios15 pro max`
- [x] 设备系统版本：如 `ios 17`

### flutter doctor ###
![image](https://github.com/user-attachments/assets/b2105bbd-fcb8-43d4-ac3f-eb4d20e93255)

#### 问题截图 ####
启动之后,进行点击,就一卡一卡的, 是模拟器卡么? 
https://github.com/user-attachments/assets/653a8039-e589-4a8e-99d0-8f0de8c9899d

**Comment by simplezhli** [comment]
模拟器卡不卡看你的电脑配置了，另外debug模式下有许多调试信息，会没有release流畅。

**Comment by Dssssds** [comment]
好的明白了. 感谢. 继续学习您的代码了.
