### ISSUE TITLE
无法运行项目

### ISSUE THREAD

**Issue by pdliuw** [simplezhli/flutter_deer#25]
### 运行环境 ###

- [x] 设备型号：如：`Emulator`
- [x] 设备系统版本：如 `Android 8.0`
- [x] Flutter 版本：如 `1.7.8`

### 具体问题描述 ###

下载项目后无法运行项目

#### 问题截图  ####

下载项目后更新过如下配置
![image](https://user-images.githubusercontent.com/29451779/61579011-e974bd80-ab31-11e9-957e-46adedfbc1bc.png)
![image](https://user-images.githubusercontent.com/29451779/61579014-f4c7e900-ab31-11e9-8cfe-bce9bbd2c5a1.png)

#### 异常日志 ####

Error: Error when reading   .....flustart..... Permission denied
import 'package:flustars/flustars.dart';

**Comment by simplezhli** [comment]
我还无法确定具体的问题，尝试删除 flutter/.pub-cache 下的flustars包，重新 flutter packages get

**Comment by LoveqLRC** [comment]
same issue
```
.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.5/lib/src/widget_util.dart:88:8: Error: No named parameter with the name 'onError'.
    }, onError: (dynamic exception, StackTrace stackTrace) {
```

**Comment by simplezhli** [comment]
@LoveqLRC 仔细看https://github.com/simplezhli/flutter_deer#%E9%A1%B9%E7%9B%AE%E8%BF%90%E8%A1%8C%E7%8E%AF%E5%A2%83
