### ISSUE TITLE
无法编译运行

### ISSUE THREAD

**Issue by hx645021783** [simplezhli/flutter_deer#250]
1. flutter 已切换到3.24.0
2. 报错要切换jdk到21(已切换)
3. qr_code_scanner报错要切换到0.4.11（已切换）

依然无法编译。
ailed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.

**Comment by simplezhli** [comment]
可参考：https://github.com/flutter/flutter/issues/156304

**Comment by hx645021783** [comment]
还是不大行。似乎需要换成kts

**Comment by simplezhli** [comment]
我抽空升级一下AS看看

**Comment by simplezhli** [comment]
适配了AGP 8+，可以拉下最新代码试试。
