### ISSUE TITLE
请问下有默认的账号密码吗？

### ISSUE THREAD

**Issue by jeremyKay9527** [simplezhli/flutter_deer#251]
![Snipaste_2024-11-24_21-54-21](https://github.com/user-attachments/assets/5785e792-ca4b-4a82-89d5-6ef9c0390cca)

**Comment by simplezhli** [comment]
不需要账号，这里只做了位数校验，多输入点内容就行了。

**Comment by jeremyKay9527** [comment]
> 不需要账号，这里只完成了补货，多输入点内容就行了。

谢谢大佬
