### ISSUE TITLE
无法编译运行

### ISSUE THREAD

**Issue by Android-Adam** [simplezhli/flutter_deer#26]
### 运行环境 ###

- [x] 设备型号：如：`MI 8`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Flutter 版本：如 `1.5.4`

### 具体问题描述 ###
刚拉取最新代码，无法编译运行
#### 问题截图  ####
![image](https://user-images.githubusercontent.com/14156592/61601922-2cd24780-ac6a-11e9-9998-0cef3e3e269a.png)

**Comment by simplezhli** [comment]
试试删除flutter SDK目录下的.pub-cache下边的git文件夹，重新编译

**Comment by Android-Adam** [comment]
没有改变，依然是这个错误

**Comment by simplezhli** [comment]
@Android-Adam 我确实收到了几次这样的反馈，但是我无法本地环境复现。你试试搜索一下关键字看是否有解决办法。

**Comment by simplezhli** [comment]
@Android-Adam 我搜到一种可能是git的原因，尝试url使用https://github.com/simplezhli/flutter_2d_amap.git

**Comment by Android-Adam** [comment]
看起来就是这个原因，我修改之后，正常编译运行了

**Comment by simplezhli** [comment]
@Android-Adam 好的，我会再下次提交处理这个兼容问题。

**Comment by Android-Adam** [comment]
好的，谢谢
