### ISSUE TITLE
flutter packages get 报错

### ISSUE THREAD

**Issue by k350023393** [simplezhli/flutter_deer#27]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米 8`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Flutter 版本：如 `与源码一致`

### 具体问题描述 ###
程序down下来以后，执行flutter packages get 报错
#### 问题截图  ####
[flutter_deer] flutter packages get
Running "flutter pub get" in flutter_deer...                    
The current Flutter SDK version is 0.0.0-unknown.

Because oktoast 2.2.0 requires Flutter SDK version >=0.3.0 <2.0.0 and no versions of oktoast match >2.2.0 <3.0.0, oktoast ^2.2.0 is forbidden.

So, because flutter_deer depends on oktoast ^2.2.0, version solving failed.
pub get failed (1)
exit code 1

**Comment by simplezhli** [comment]
@k350023393 看报错信息是你的Flutter版本过低，确保Flutter版本至少为1.5.4。

**Comment by k350023393** [comment]
可以了，原因是我flutter用的是最新版的，切换为 Flutter version 1.5.4+hotfix.2 版本就可以了
