### ISSUE TITLE
验证码按钮状态更改问题

### ISSUE THREAD

**Issue by chenjinguang** [simplezhli/flutter_deer#30]
现在代码中是点击发送验证码按钮直接倒计时，正常的开发流程中，是先网络请求验证码发送成功后，才进行倒计时，请问这里该怎么修改呢

**Comment by simplezhli** [comment]
这是我实际项目中的代码，你可以参考一下：
<img width="994" alt="image" src="https://user-images.githubusercontent.com/12456431/62045484-072fda00-b238-11e9-902f-1e634f859fd3.png">

图中的getVCode 方法是一个 `Future<bool> Function() `，这里你就可以传入你的请求验证码接口。只有当成功时，才会开始倒计时。

**Comment by chenjinguang** [comment]
按照您上面说的，我这边的isSuccess一直返回null
![image](https://user-images.githubusercontent.com/2968935/62051057-22551680-b245-11e9-8374-d6d2d3bf1dfd.png)
![image](https://user-images.githubusercontent.com/2968935/62051094-36007d00-b245-11e9-9f39-9d3d40578286.png)

**Comment by simplezhli** [comment]
详细的我就不多说了，主要还是Future的用法问题。代码贴出来，你自己研究一下：
<img width="632" alt="image" src="https://user-images.githubusercontent.com/12456431/62054093-7ebb3480-b24b-11e9-8056-90e7933d65e0.png">

<img width="492" alt="image" src="https://user-images.githubusercontent.com/12456431/62054161-9eeaf380-b24b-11e9-9171-3b9caeea0250.png">

**Comment by simplezhli** [comment]
@chenjinguang 我补充了一下代码，你可以参考一下：https://github.com/simplezhli/flutter_deer/blob/master/lib/login/register_page.dart#L100

**Comment by chenjinguang** [comment]
谢谢^_^

- [ ]
