### ISSUE TITLE
dio添加代理后仍然无法用fiddler抓包

### ISSUE THREAD

**Issue by lxk123** [simplezhli/flutter_deer#31]
dio添加代理后仍然无法用fiddler抓包

**Comment by simplezhli** [comment]
还没有尝试过开发flutter时用fiddler抓包，我抽时间试试。如果是dio的问题，你不是应该去dio那里提issue嘛。。。

**Comment by simplezhli** [comment]
@lxk123 我照着这篇博客成功的抓到了包，你可以试试。https://www.jianshu.com/p/d831b1f7c45b
