### ISSUE TITLE
Could not find a file named "pubspec.yaml"  

### ISSUE THREAD

**Issue by docwei2050** [simplezhli/flutter_deer#32]
运行环境是最新的

#### 异常日志 ####
pub get failed (69) -- attempting retry 3 in 4 seconds...               
Could not find a file named "pubspec.yaml" in https://github.com/simplezhli/flutter_2d_amap.git 9705e914e9c3593f41cb4d32d0f43b3abb9b14f1.
Running "flutter pub get" in flutter_deer-master...                     
**pub get failed (1)**

**Comment by simplezhli** [comment]
试着将https换为git

**Comment by docwei2050** [comment]
好了
