### ISSUE TITLE
商品列表刷新问题

### ISSUE THREAD

**Issue by chenjinguang** [simplezhli/flutter_deer#33]
楼主，商品tab中，选择商品类别之后，应该根据类别变化发起网络请求，然后根据返回数据刷新商品列表，请问怎样做比较合适呢，没有找到合适的办法

**Comment by simplezhli** [comment]
实际项目中我在商品页的外层有两个provider，一个用来存储选择的tab下标和选择的分类，一个用来做通知刷新列表使用，一旦选择类别后，通知刷新列表（状态置为true）。收到刷新通知的tab就去刷新页面（因为会同时通知多个tab刷新，所以需要根据选中的tab来判断），刷新结束后将刷新状态置为false，避免其他provider的刷新影响。

**Comment by simplezhli** [comment]
实现起来不复杂，但是要控制好状态的刷新，避免无效的刷新数据需要下点功夫。

![image](https://user-images.githubusercontent.com/12456431/62280844-4308b080-b47f-11e9-9521-3d18bb71805e.png)

**Comment by chenjinguang** [comment]
楼主你好，我按照您提供的方法，刷新列表的provider没有问题，存储选择的tab下标的provider报错如下图所示，对provider的使用还是不太了解，感觉官方提供的demo比较简单，麻烦楼主帮忙看下该如何解决，谢谢~
![image](https://user-images.githubusercontent.com/2968935/62445541-098fb800-b793-11e9-89e5-f029c155aa11.png)

以下是部分页面代码，外层页面：
![image](https://user-images.githubusercontent.com/2968935/62445581-24fac300-b793-11e9-90c7-1f18456f3ddf.png)

![image](https://user-images.githubusercontent.com/2968935/62445599-33e17580-b793-11e9-809e-8540d512c886.png)

列表页面：
![image](https://user-images.githubusercontent.com/2968935/62445624-43f95500-b793-11e9-8e77-e08c027947d0.png)

![image](https://user-images.githubusercontent.com/2968935/62445638-49ef3600-b793-11e9-9840-408438317993.png)

**Comment by simplezhli** [comment]
首先如果使用了`provider`，就不需要使用`setState`来刷新页面了。
其次列表不需要`ChangeNotifierProvider` 再次提供一个新的刷新状态变化，只需要直接Provider.of()获取外层状态。

主要还是对provider的理解没有到位，还是先理解provider的实现原理及api再来使用。

**Comment by chenjinguang** [comment]
谢谢楼主，对provider的理解确实不到位，该好好看一些再写，我现在的做法是用MulitProvider,现在实现了想要的效果。
![image](https://user-images.githubusercontent.com/2968935/62452815-84f96580-b7a3-11e9-9a9b-f98c74ff611a.png)

**Comment by simplezhli** [comment]
对的，外层是两个`provider`，需要使用`MulitProvider`.
