### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by luchengmei** [simplezhli/flutter_deer#35]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`as模拟器`
- [x] 设备系统版本：如 `Android 8.1`
- [x] Flutter 版本：如 `1.7.8`

### 具体问题描述 ###
运行报错
#### 问题截图  ####
![image](https://user-images.githubusercontent.com/37893554/62614070-45668100-b93d-11e9-9b87-de70ebd9e6d4.png)

**Comment by simplezhli** [comment]
你的代码不是最新的吧，flustars和image的库都是之前的版本。
