### ISSUE TITLE
为什么我打release包要15M。你发的包才9M呢？

### ISSUE THREAD

**Issue by live17909** [simplezhli/flutter_deer#36]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Flutter 版本：如 `1.7.8`

### 具体问题描述 ###
为什么我打release包要15M。你发的包才9M呢？

**Comment by simplezhli** [comment]
我去除了64位的v8a
