### ISSUE TITLE
返回数据处理问题。

### ISSUE THREAD

**Issue by yyaini112** [simplezhli/flutter_deer#38]
为什么返回值会多message和code。怎么把data里面的data信息解析出来呢？

D/X-LOG   (13781): ResponseCode: 200
D/X-LOG   (13781): {
D/X-LOG   (13781):     "code": 0,
D/X-LOG   (13781):     "msg": null,
D/X-LOG   (13781):     "data": "登录成功!"
D/X-LOG   (13781): }
D/X-LOG   (13781): ----------End: 1267 毫秒----------
I/flutter (13781): response返回
I/flutter (13781): {"code":0,"data":{"code":0,"msg":null,"data":"登录成功!"},"message":""}

**Comment by simplezhli** [comment]
你可以去除dio_utils中的`AdapterInterceptor`拦截器。同时去除`validateStatus`属性设置。https://github.com/simplezhli/flutter_deer/blob/master/lib/net/dio_utils.dart#L35

**Comment by simplezhli** [comment]
因为你的接口格式是msg，所以还需要修改dio_utils中所有的`_map["message"]`为`_map["msg"]`,这样才能保证解析出msg参数。具体的需求还是需要你去改造，我只是提供了适用于我使用接口的方法。

**Comment by yyaini112** [comment]
感谢，只要把//_dio.interceptors.add(AdapterInterceptor());注释掉就ok了。validateStatus属性不变（true）也许。
