### ISSUE TITLE
如何让flutter的session保存不变。

### ISSUE THREAD

**Issue by yyaini112** [simplezhli/flutter_deer#39]
想要给flutter-deer写后端接口，让项目看起来更真实。
利用session判断用户是否登录过。
web端session不会发生变化。
flutter-deer的session一直在变化。
flutter-deer发两次登录请求
我拿到的sessiond7eb9518-97f1-429f-84fc-4fe3630748ea
我拿到的session54b24859-8756-44da-9e93-2ed528b7f7aa
web端发两次登录请求
我拿到的session80491d3e-ef47-4a83-835f-5646992304c7
我拿到的session80491d3e-ef47-4a83-835f-5646992304c7

**Comment by simplezhli** [comment]
session 或是 token，不都是登录成功由接口返回的。我们可以储存在本地使用，那么也不会变化。

**Comment by yyaini112** [comment]
不知道您有没有后端的开发经验。
后端验证方案：
1.当用户名和密码输入正确，把前端的session和用户id绑定（K-V）保存到redis。
2.前端请求需要权限的接口。判断session是否在redis中，不存在则，告诉用户未登录，存在则放行。
碰到的问题就是web端这个session是固定的。可以判断用户的登录状态。但Flutter-deer每次请求，都用不同的session生成。造成无法判断用户是否登录。
这个问题如何解决呢？

**Comment by simplezhli** [comment]
@yyaini112 大概了解了你的方式，看是否是cookie持久化的问题。可以看一下dio的文档https://github.com/flutterchina/dio/blob/master/README-ZH.md#cookie%E7%AE%A1%E7%90%86

**Comment by yyaini112** [comment]
感谢，是cookie持久化的问题，身份验证的问题已经解决了。
这个issue就不关闭了，以后对接flutter-deer有问题，直接在这问。

后端的技术是spring boot2.1.7.RELEASE + JDK1.8 + mybatis-plus3.1.0 + mysql +redis + aliyun-sms
对接完这个版本flutter-deer后，也会开源后端源码，和大家一起学习。

**Comment by simplezhli** [comment]
好的
