### ISSUE TITLE
写的真的是厉害,拜读中

### ISSUE THREAD

**Issue by changeyan** [simplezhli/flutter_deer#4]
抱住大神的大腿膜拜,日期选择那里是手撸的么

**Comment by simplezhli** [comment]
日历也是借用了现有的date_utils做的，算是站在巨人的肩膀上了。

**Comment by changeyan** [comment]
> 日历也是借用了现有的date_utils做的，算是站在巨人的肩膀上了。

这几天一直在学习，我要看透你的项目，虽然没有接口，但是看这个布局质量如果有接口一定非常优秀

**Comment by simplezhli** [comment]
客气了，欢迎交流！
