### ISSUE TITLE
首先这个练习的项目我觉得很好，很震惊。 但是我是初学者，大部分都看不懂。 如果有注释，或者有文字教程就好了

### ISSUE THREAD

**Issue by yfm-pliny** [simplezhli/flutter_deer#41]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Flutter 版本：如 `1.7.8`

**Comment by simplezhli** [comment]
@yfm-pliny 我虽然看了文档和很多项目，但其实我起初写的时候还是边查边写。这个项目我提供了设计图和实现代码，类似于提供了题目与参考答案。更多的还是要自己动手去练习、思考。甚至我更建议不看我的代码，直接照着设计图去实现。等写完时再看看我的，说不定你的方法更便捷。
