### ISSUE TITLE
TextField 居中问题

### ISSUE THREAD

**Issue by zilingyao** [simplezhli/flutter_deer#42]
### 运行环境 ###

- [x] 电脑系统：`Windows 10`
- [x] 设备型号：`小米6s`
- [x] 设备系统版本： `Android 9.0`
- [x] Flutter 版本： [`1.8.4`]

### 具体问题描述 ###

貌似所有的输入框 光标和hint没有垂直居中 稍微有点错位 搜索框尤其明显 不知道怎么回事

**Comment by simplezhli** [comment]
这个问题在Flutter中一直都有存在，并且在Android和iOS上`TextField`的表现还有一定差异。搜索框因为我添加了`icon`导致偏移比较明显。简单的方法只能调整`contentPadding`来处理这类问题。但是并不是最佳方案，我抽时间查查看有没有好的方法。

**Comment by zilingyao** [comment]
ok 明白 多谢了

**Comment by simplezhli** [comment]
@zilingyao 发现搜索框偏移明显是没有在`contentPadding`中设置`bottom`的大小。其余的错位现象属于Flutter 的问题，但是不是很明显。
