### ISSUE TITLE
你的博客文章“Flutter 动画曲线Curves 效果一览”里面的GIF图是怎么做的？

### ISSUE THREAD

**Issue by bigbirdhzp** [simplezhli/flutter_deer#43]
如下图，请问下图中的两部分别是怎么做的？如果是用软件的话，请告诉我用什么软件，感谢指导。

![image](https://user-images.githubusercontent.com/22903159/63397914-8ad78380-c3fe-11e9-8a48-b2cbdd409eab.png)

**Comment by simplezhli** [comment]
@bigbirdhzp 其实就是找了一个在线转换的网站，我用的是这个：https://www.aconvert.com/cn/video/mp4-to-gif/

**Comment by simplezhli** [comment]
文章中有说是“文档中提供的MP4转为了GIF”，并不是我制作的GIF。

**Comment by bigbirdhzp** [comment]
原来是这个网站，我也有用的。感谢指导^-^
