### ISSUE TITLE
我准备将MVP模块单独抽象出来作为工具类来使用,事实上我已经在做了

### ISSUE THREAD

**Issue by MeDeity** [simplezhli/flutter_deer#45]
我很喜欢这个项目的MVP实现方式,因此我准备将MVP模块单独抽象出来作为工具类来使用,事实上我已经在做了.
[flutter mvp实现方式](https://github.com/MeDeity/lib_mvp.git).

**Comment by simplezhli** [comment]
喜欢就好，使用上有好的建议欢迎反馈。

**Comment by MeDeity** [comment]
好的.
