### ISSUE TITLE
大佬，请问你的扫描的插件是怎样让他显示中文的，我这里手电筒的文字一直显示的是FLASH ON

### ISSUE THREAD

**Issue by danyunLu** [simplezhli/flutter_deer#46]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Flutter 版本：如 `1.7.8`

**Comment by simplezhli** [comment]
@danyunLu 我fork了源仓库，自己做了修改。。。

**Comment by danyunLu** [comment]
@simplezhli 是这个地址吗，我是不是可以直接用了https://github.com/simplezhli/flutter_barcode_reader

**Comment by simplezhli** [comment]
是的，如果你只需要文字为中文。

**Comment by danyunLu** [comment]
@simplezhli 好的，thanks~
