### ISSUE TITLE
Page类名都规范一下吧

### ISSUE THREAD

**Issue by charmfocus** [simplezhli/flutter_deer#47]
代码中有的Page类名有Page后缀，有的又没有，统一一下规范吧
比如

https://github.com/simplezhli/flutter_deer/blob/8f656e27fea17c7d806638b7f6840ab5fb801c59/lib/shop/shop_page.dart#L17

https://github.com/simplezhli/flutter_deer/blob/8f656e27fea17c7d806638b7f6840ab5fb801c59/lib/shop/shop_setting_page.dart#L19

**Comment by simplezhli** [comment]
@charmfocus 好的，感谢提醒
