### ISSUE TITLE
在订单页中，左右滑动切换子tab。会出现 卡顿。

### ISSUE THREAD

**Issue by jol5** [simplezhli/flutter_deer#48]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`meizu pro7 plus`
- [x] 设备系统版本：如 `Android 8.0`

### 具体问题描述 ###

直接下载的apk，订单页中，切换tab，每次都会在两个子tab切换动画走到一半的时候，会出现卡顿一下，然后顶部的子tab进行选中动画切换，最后才到内容剩下的一半切换完成。

**Comment by simplezhli** [comment]
了解，我这边排查一下。

**Comment by simplezhli** [comment]
@jol5 问题确定了，不过因为一些原因。。。我暂时只优化了刷新范围的部分，我这边的监测结果来看。耗时由36ms左右降到了23ms左右(还是超出16ms)。你可以重新下载最新的包（https://www.pgyer.com/gYXj ），看一下情况。
