### ISSUE TITLE
routers 路由管理封装类带参数push下级页面

### ISSUE THREAD

**Issue by OmgKevin** [simplezhli/flutter_deer#49]
### 具体问题描述 ###
 NavigatorUtils.push(context,MyPageRouter.feedbackPage);

这种的封装下，我想带参数push到下一级页面，怎么携带参数呢，且参数类型不全是String类型，

我参阅了fluro路由管理框架里面的写法，是直接把参数携带到path的后边，类似于：
String route = "/demo?message=$message&color_hex=$hexCode";

但是您在他的基础上进行了又一层的封装，我想知道在您的代码基础上如何去携带参数的哈

**Comment by OmgKevin** [comment]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/31239280/64614032-28284500-d40a-11e9-8c05-041cecabf3b8.png">

**Comment by OmgKevin** [comment]
然后以这种方式跳转的时候，页面报错警告红色
<img width="311" alt="image" src="https://user-images.githubusercontent.com/31239280/64614073-4130f600-d40a-11e9-8909-9ded0aee51fe.png">

**Comment by OmgKevin** [comment]
我这边的整体逻辑是：
<img width="642" alt="image" src="https://user-images.githubusercontent.com/31239280/64614736-bc46dc00-d40b-11e9-8a83-ebf67e1bfee5.png">
<img width="932" alt="image" src="https://user-images.githubusercontent.com/31239280/64614776-d1bc0600-d40b-11e9-8fca-2d79664918ae.png">
<img width="566" alt="image" src="https://user-images.githubusercontent.com/31239280/64614798-dd0f3180-d40b-11e9-8f0b-6d5f646fa48c.png">
，我这种到底是什么原因导致的呢？

**Comment by OmgKevin** [comment]
<img width="656" alt="image" src="https://user-images.githubusercontent.com/31239280/64614897-062fc200-d40c-11e9-9831-1d705849b517.png">

**Comment by OmgKevin** [comment]
<img width="717" alt="image" src="https://user-images.githubusercontent.com/31239280/64615521-4f344600-d40d-11e9-8f9c-30690a931dc8.png">

**Comment by OmgKevin** [comment]
<img width="678" alt="image" src="https://user-images.githubusercontent.com/31239280/64615595-70953200-d40d-11e9-8d2e-be5b46fe51e7.png">

**Comment by OmgKevin** [comment]
<img width="520" alt="image" src="https://user-images.githubusercontent.com/31239280/64615625-83a80200-d40d-11e9-9558-e914dfc14e51.png">

**Comment by OmgKevin** [comment]
此时我的路由跳转失去作用，点击没有反应

**Comment by simplezhli** [comment]
我是将路由的初始化分模块处理，所以需要先实现。参考https://github.com/simplezhli/flutter_deer/blob/master/lib/store/store_router.dart
 然后在主路由管理处注册https://github.com/simplezhli/flutter_deer/blob/master/lib/routers/routers.dart  ,你的问题是没有正确初始化路由，其他写法没有什么问题。

**Comment by OmgKevin** [comment]
嗯，我当时也看到你这块儿了，当时觉得要在每个页面上都写一个路由类略显麻烦，还不如统一管理起来，所以就只集中写了这一个，话说我这种写法的话，这种问题木有办法解决不 😢


在2019年09月11日 07:09，唯鹿 写道：

我是将路由的初始化分模块处理，所以需要先实现。参考https://github.com/simplezhli/flutter_deer/blob/master/lib/store/store_router.dart
然后在主路由管理处注册https://github.com/simplezhli/flutter_deer/blob/master/lib/routers/routers.dart ,你的问题是没有正确初始化路由，其他写法没有什么问题。

**Comment by OmgKevin** [comment]
params那里报警告，是因为我没有在花括号里，把SettingPage给return出去。现在加上了，可是点击还是没反应，控制台打印输出：
<img width="925" alt="image" src="https://user-images.githubusercontent.com/31239280/64663678-2ba9e380-d47f-11e9-9384-9c5f41e1d647.png">

**Comment by OmgKevin** [comment]
原因找到了，是因为fluro不支持中文传递，需要对其进行转码。params那里报警告错误是因为我没有在花括号里面将SettingPage 进行return
