### ISSUE TITLE
请教关于项目 clone 下来编译不了的问题

### ISSUE THREAD

**Issue by gzpaiwxc** [simplezhli/flutter_deer#5]
大佬 , 我是小白一个 , clone 下你的项目后 , package get 一直不行 , 一直提示 dart 的版本对应不上 , 请问该怎么解决呢 ? flutter 版本 1.5.4 , 错误如下:
![1560994506(1)](https://user-images.githubusercontent.com/16586195/59811980-c4c4d480-933e-11e9-9443-d5ccf8cd42c2.jpg)

**Comment by gzpaiwxc** [comment]
请问作者的 flutter sdk 是什么版本的呢?

**Comment by simplezhli** [comment]
我的环境信息在rademe中有的，你可以对照一下。

**Comment by simplezhli** [comment]
你的问题看报错信息是dart的sdk版本过低，不满足keyboard_actions这个库的要求

**Comment by AnleSu** [comment]
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/50828336/59845801-cfa85500-9390-11e9-96bc-59d4eaeafdf5.png">
大佬有遇到过这个错误嘛 run的时候报错 但是代码里并不提示有错误呀

**Comment by AnleSu** [comment]
Launching lib/main.dart on iPhone X in debug mode...

Compiler message:
file:///Users/suanle/.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.5/lib/src/widget_util.dart:88:8: Error: No named parameter with the name 'onError'.
    }, onError: (dynamic exception, StackTrace stackTrace) {
       ^^^^^^^
file:///Users/suanle/.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.5/lib/src/widget_util.dart:115:8: Error: No named parameter with the name 'onError'.
    }, onError: (dynamic exception, StackTrace stackTrace) {
       ^^^^^^^
Compiler failed on /Users/suanle/Documents/flutter_deer-master/lib/main.dart
Error launching application on iPhone X.
Exited (sigterm)

接上个问题 截图看不到 copy了一份错误log

**Comment by simplezhli** [comment]
这个问题是flustars的问题，具体可以查看链接。主要还是你的环境不匹配导致。https://github.com/Sky24n/flustars/issues/10

**Comment by AnleSu** [comment]
> 这个问题是flustars的问题，具体可以查看链接。主要还是你的环境不匹配导致。[Sky24n/flustars#10](https://github.com/Sky24n/flustars/issues/10)

解决了 感谢
