### ISSUE TITLE
SMSVerifyDialog类中,android 端当6位短信验证码输入完后,会同时执行3次onChanged回调里的长度相等判断

### ISSUE THREAD

**Issue by DestinyMing** [simplezhli/flutter_deer#50]
### 具体问题描述 ###
SMSVerifyDialog 的短信验证框 ，输入完6位的短信验证码的时候，里边的v.length == _codeList.length 的 if 判断 会触发3次，我用provider 代替 了setState(() {});刷新页面，但是还是有问题

**Comment by simplezhli** [comment]
身边没有电脑。。我检查了一下代码，怀疑是_controller.text=""这行的调用应该放在置空循环后面，否则会再次触发onChange。你尝试一下看是否有用。

**Comment by DestinyMing** [comment]
是的，确实是放在前边导致的，我用provider也重新做好了替代 了 setState 刷新页面，达到局部刷新的目的
