### ISSUE TITLE
环境冲突

### ISSUE THREAD

**Issue by JiweiMaster** [simplezhli/flutter_deer#51]
升级到flutter1.9版本之后，依赖之间的兼容性问题

Because date_utils >=0.1.0 depends on intl ^0.15.0 and every version of flutter_localizations from sdk depends on intl 0.16.0, date_utils >=0.1.0 is incompatible with flutter_localizations from sdk.
So, because flutter_deer depends on both flutter_localizations any from sdk and date_utils ^0.1.0+2, version solving failed.
pub get failed (1)

**Comment by simplezhli** [comment]
@JiweiMaster 我这边升级没有这个问题，你试试packages upgrade。
