### ISSUE TITLE
大佬，问题请教

### ISSUE THREAD

**Issue by k3cloudqxy** [simplezhli/flutter_deer#52]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Flutter 版本：如 `1.7.8`

### 具体问题描述 ###
大佬，一个flutter_deer之外的问题请教，就是比如我想在flutter_deer的app中实现一个功能，比如新订单来了，在桌面上app图标的右上角有个红色数字提示，类似微信未读消息提示的效果，有什么插件可以实现吗，在app登录后的页面中已实现通过websocket接收后台主动推送的消息，现在想把消息也提示到桌面app的右上角上，大佬，可否给点建议，感谢感谢

**Comment by simplezhli** [comment]
@k3cloudqxy  这个功能iOS端用'applicationIconBadgeNumber'就可以设置，Android这边没有统一规范，会比较难做。Android默认是根据通知栏的消息数量变化的。

**Comment by k3cloudqxy** [comment]
好的  感谢感谢
