### ISSUE TITLE
网络请求后Dialog执行closeProgress方法dialog没有关闭，界面黑屏

### ISSUE THREAD

**Issue by jisuz** [simplezhli/flutter_deer#54]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`华为荣耀`
- [x] 设备系统版本：如 `Android 4.4`
- [x] Flutter 版本：如 `1.7.8`

### 具体问题描述 ###
使用mvp框架，在presenter中执行网络请求操作，将requestNetwork中的isShow和isClose配置为ture，使用loading dialog加载界面，在网络请求成功后，loading dialog没有关闭，然后界面黑屏了，我这边通过日志打印，closeProgress是有执行的，但是loading dialog没有关闭，查不出什么原因，希望给个思路，谢谢哈
部分代码片段：
Future undoTodo(String code, String updateTime, String applyUuid) async {
    Map<String, Object> params = Map();
    params["code"] = code;
    params["updateTime"] = updateTime;
    params["applyUuid"] = applyUuid;
    await requestNetwork(Method.post,
        url: HttpApi.undoTodo,
        params: params,
        isShow: true,
        isClose: true,
        onSuccess: (data) {
          view.onRefresh();
          Toast.show("成功!");
        }, onError: (_, __) {
          print("$_, $__");
    });
  }
#### 问题截图  ####
![image](https://user-images.githubusercontent.com/7007140/65666531-695a5f00-e070-11e9-8e60-6592e8e79b84.png)

#### 异常日志 ####
I/flutter (10619): showProgress
I/flutter (10619): mounted: true
I/flutter (10619): _isShowDialog: false

I/flutter (10619): closeProgress
I/flutter (10619): mounted: true
I/flutter (10619): _isShowDialog: true

**Comment by jisuz** [comment]
补充一下哈，我是在AlertDialog中的点击事件调用网络请求的
 void _undoOrder(index) {
    DialogUtils.showConfirmDialog(context, '提示', '是否撤销？', '确定', () async {
      await presenter.undoTodo(
          todoProvider.list[index].code,
          todoProvider.list[index].updateDate.toString(),
          todoProvider.list[index].operatorUuid);
    }, '取消', () {});
  }

**Comment by simplezhli** [comment]
@jisuz  看样子pop方法将当前的页面返回了，你尝试不在AlertDialog中请求接口，看是否正常。

**Comment by jisuz** [comment]
我刚刚试了一下，不在AlertDialog中请求接口是正常的。
请问，这个有什么办法解决吗，loading dialog 封装在网络请求中，但是开发中遇到了需要先弹出询问对话框后，确认再请求接口

**Comment by simplezhli** [comment]
我这边测试是没有问题的，只是要保证对话框先关闭在请求接口。

**Comment by jisuz** [comment]
好的好的，谢谢哈，我这边试一下
