### ISSUE TITLE
标题吸附在最上面的时候不居中

### ISSUE THREAD

**Issue by WangYan666** [simplezhli/flutter_deer#55]
![IMG_0027](https://user-images.githubusercontent.com/13739711/65679317-6c147e80-e087-11e9-9ea1-bfaf76de1809.PNG)
![IMG_0028](https://user-images.githubusercontent.com/13739711/65679332-7171c900-e087-11e9-9007-3c9bb1f8686e.PNG)

**Comment by simplezhli** [comment]
Emmm... 我觉得如果你改了我的代码，应该也尝试去修改这个问题。我并不保证我的代码在所有场景下都是万能的。不过我会去修复这个问题。
