### ISSUE TITLE
关于dio泛型封装

### ISSUE THREAD

**Issue by wadewen** [simplezhli/flutter_deer#57]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`Redmi note7 pro`
- [x] 设备系统版本：如 `Android 8.0`
- [x] Flutter 版本：如 `1.9.1`

### 具体问题描述 ###
我应该如何修改dio_utils和base_entity（已经注释掉
AdapterInterceptor和validateStatus了）。
#### 问题截图  ####
{
    "code": 200,
    "success": true,
    "data": {
        "id": "1181389891706650626",
        "isDeleted": 0,
        "name": "小明",
    },
    "msg": "操作成功"
}
#### 异常日志 ####
接口请求异常： code: 1001, msg: 数据解析错误,，

**Comment by simplezhli** [comment]
具体的异常信息会有输出，会提示解析失败的原因。剩下要注意的是code值的校验，默认是code == 0为成功

**Comment by wadewen** [comment]
![image](https://user-images.githubusercontent.com/19342903/66371199-2637ae80-e9d5-11e9-8211-390bf81f6d68.png)

**Comment by simplezhli** [comment]
json 没有双引号，导致格式化错误。看你还有什么改动没有。

**Comment by wadewen** [comment]
是跟我注释掉AdapterInterceptor有关系吗？

**Comment by simplezhli** [comment]
没有影响，我这边也测试了一下。

**Comment by wadewen** [comment]
我主要就改了base_entity,是这里的问题吗？麻烦你看下。
class BaseEntity<T>{
  int code;
  bool success;
  T data;
  List<T> listData = [];
  String msg;
  BaseEntity(this.code,this.success, this.data, this.msg);

  BaseEntity.fromJson(Map<String, dynamic> json) {
    msg = json['msg'];
    code = json['code'];
    success = json['success'];

    if (json.containsKey(Constant.data)){
      if (json[Constant.data] is List) {
        (json[Constant.data] as List).forEach((item){
          listData.add(EntityFactory.generateOBJ<T>(item));
        });
      }else {
        if (T.toString() == "String"){
          data = json[Constant.data].toString() as T;
        }else if (T.toString() == "Map<dynamic, dynamic>"){
          data = json[Constant.data] as T;
        }else {
          data = EntityFactory.generateOBJ(json[Constant.data]);
        }
      }
    }
  }
}

**Comment by simplezhli** [comment]
看着没什么问题

**Comment by simplezhli** [comment]
完整的打印信息截个图，看看contentType是不是json

**Comment by wadewen** [comment]
![image](https://user-images.githubusercontent.com/19342903/66374169-f7bdd180-e9dc-11e9-8d01-25f9b9235aec.png)好像发现问题了，本来dio默认的请求头application/json; charset=utf-8分号后面有个空格，后台一直反requestbody is missing，就让我又加了个header

**Comment by simplezhli** [comment]
你看一下`BaseOptions`的`responseType`配置的是什么

**Comment by simplezhli** [comment]
json打印格式有误，说明返回类型不是String。我暂时能想到的是，`responseType` 必须为 `ResponseType.plain`。否则默认会解析为map，map在toString时会丢失双引号。

**Comment by wadewen** [comment]
我把BaseOptions的responseType注释了，确认了不是请求头的原因

**Comment by wadewen** [comment]
已解决，将dio_utils中_request方法做如下修改：
//      Map<String, dynamic> _map = Constant.isTest ? parseData(response.data.toString()) : await compute(parseData, response.data.toString());
      return BaseEntity.fromJson(response.data);

**Comment by simplezhli** [comment]
问题还是我上面提到的，`responseType`必须为 `ResponseType.plain`，如果没有配置默认是会解析json的。dio的使用文档还是要看看的。

**Comment by wadewen** [comment]
因为我需要的就是ResponseType.json
