### ISSUE TITLE
iOS暗黑模式下状态栏字体颜色问题。

### ISSUE THREAD

**Issue by sanrixue** [simplezhli/flutter_deer#59]
### 运行环境 ###

- [x] 电脑系统：：`mac`
- [x] 设备型号：：`iphoneX`
- [x] 设备系统版本： `ios 13.1.1`
- [x] Flutter 版本：`1.9.1+2`

### 具体问题描述 ###

iOS暗黑模式下状态栏字体颜色为白色。
设置 SystemUiOverlayStyle 没能起预想的作用。

**Comment by simplezhli** [comment]
状态栏背景是深色，字体颜色就设置成白色了

**Comment by simplezhli** [comment]
如果你要修改，系统的`AppBar`需要修改`brightness`属性，我自定义的`AppBa`r需要修改`overlayStyle`

**Comment by sanrixue** [comment]
![41570615391_ pic](https://user-images.githubusercontent.com/26269929/66472065-11374a00-eabf-11e9-83fc-3075629438b1.jpg)

**Comment by sanrixue** [comment]
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
  //黑色
  SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.dark);
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        backgroundColor: Colors.white,
        body: Container(),
      ),
    );
  }
}
我直接将项目修改为最简化的方式来展示这样的问题，在浅色下正常，在暗黑下依旧还是白色。

**Comment by sanrixue** [comment]
我同时也尝试了，在你自定义的appbar中强制将修改 SystemUiOverlayStyle _overlayStyle =SystemUiOverlayStyle.dark; 仍是不作用。

**Comment by simplezhli** [comment]
文字改为黑色应该设置SystemUiOverlayStyle.light，你不会写死成dark吧

**Comment by sanrixue** [comment]
一样SystemUiOverlayStyle 不论设置什么都是不起作用的。

**Comment by simplezhli** [comment]
了解，我晚上回去看看什么问题。

**Comment by sanrixue** [comment]
谢谢。

**Comment by simplezhli** [comment]
你可以先试试手机开启深色模式，在deer的设置里关闭夜间模式。看能否起作用，我记得这块是好的。

**Comment by sanrixue** [comment]
已经尝试

**Comment by simplezhli** [comment]
看来这是Flutter的适配问题，我在Flutter的issue中也找到了相关问题。https://github.com/flutter/flutter/issues/41067

**Comment by chenyanbin-dkhs** [comment]
@simplezhli 感谢你的这个项目，里面的技巧非常多，我也正尝试照着这个项目做一个公司内部的APP。
有个小疑问，我看了很久不太明白，就是在main.dart 的build里直接返回一个OKToast ? ，是为了实现Theme切换吗？

**Comment by blackox626** [comment]
```objc
- (void)setSystemChromeSystemUIOverlayStyle:(NSDictionary*)message {
  NSString* style = message[@"statusBarBrightness"];
  if (style == (id)[NSNull null])
    return;

  UIStatusBarStyle statusBarStyle;
  if ([style isEqualToString:@"Brightness.dark"])
    statusBarStyle = UIStatusBarStyleLightContent;
  else if ([style isEqualToString:@"Brightness.light"])
    statusBarStyle = UIStatusBarStyleDefault;
  else
    return;

  NSNumber* infoValue = [[NSBundle mainBundle]
      objectForInfoDictionaryKey:@"UIViewControllerBasedStatusBarAppearance"];
  Boolean delegateToViewController = (infoValue == nil || [infoValue boolValue]);

  if (delegateToViewController) {
    // This notification is respected by the iOS embedder
    [[NSNotificationCenter defaultCenter]
        postNotificationName:@(kOverlayStyleUpdateNotificationName)
                      object:nil
                    userInfo:@{@(kOverlayStyleUpdateNotificationKey) : @(statusBarStyle)}];
  } else {
    // Note: -[UIApplication setStatusBarStyle] is deprecated in iOS9
    // in favor of delegating to the view controller
    [[UIApplication sharedApplication] setStatusBarStyle:statusBarStyle];
  }
}
```

engine 源码中 可以看到 没有 UIStatusBarStyleDarkContent 

尝试 去掉 info.plist 中的 UIViewControllerBasedStatusBarAppearance 

然后 监听 通知 
```
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(appStatusBar:) name:@"io.flutter.plugin.platform.SystemChromeOverlayNotificationName" object:nil];

- (void)appStatusBar:(id)notification {
    if (@available(iOS 13.0, *)) {
        [UIApplication sharedApplication].statusBarStyle = UIStatusBarStyleDarkContent;
    }
}
```

**Comment by simplezhli** [comment]
@blackox626 感谢，我去试试。

**Comment by zinwalin** [comment]
这个问题解决了吗？

**Comment by simplezhli** [comment]
@zinwalin PR还没有合并进去。
![image](https://user-images.githubusercontent.com/12456431/71332914-009d5880-2573-11ea-8002-bca6b7845ed0.png)

**Comment by zinwalin** [comment]
手机开启深色模式，在deer的设置里关闭夜间模式。  看不见状态栏的字，因为状态栏的字体是白色的。

![image](https://user-images.githubusercontent.com/5416196/72029013-83d2e400-32bf-11ea-9b2d-c1eb6782e146.png)

**Comment by simplezhli** [comment]
@zinwalin 你的手机机型和系统版本是多少？

**Comment by zinwalin** [comment]
> @zinwalin 你的手机机型和系统版本是多少？

你好。  iOS 13, iPhone 6S, iPhone 11

**Comment by simplezhli** [comment]
我还以为是Android手机。。。这个问题，我暂时没有修复。所以这个issue没关的原因也是这个。如果有需要的可以看上面的链接。现在本地的解决方法也很多，比如最新的方案：
![6X)ZT 3TC{TMQGT{U_LC2ZG](https://user-images.githubusercontent.com/12456431/72032869-a539cd00-32cb-11ea-8a26-d1678389b1d7.png)

**Comment by zinwalin** [comment]
> 我还以为是Android手机。。。这个问题，我暂时没有修复。所以这个issue没关的原因也是这个。如果有需要的可以看上面的链接。现在本地的解决方法也很多，比如最新的方案：
> ![6X)ZT 3TC{TMQGT{U_LC2ZG](https://user-images.githubusercontent.com/12456431/72032869-a539cd00-32cb-11ea-8a26-d1678389b1d7.png)

感谢/

**Comment by simplezhli** [comment]
1.17.0 已修复
