### ISSUE TITLE
Unable to resolve dependency: 'xcodeproj (< 2.0, >= 1.5.7)' requires 'CFPropertyList (< 4.0, >= 2.3.3)' (Gem::UnsatisfiableDependencyError)

### ISSUE THREAD

**Issue by kingsofish** [simplezhli/flutter_deer#60]
### 运行环境 ###

- [x] 电脑系统：`macOS Mojave 10.14.6 (18G95)`
- [x] 设备型号：`iPhone X`
- [x] 设备系统版本： `iOS 12.2`
- [x] Flutter 版本：`1.10.7`

### 具体问题描述 ###
一开始我以为是cocoapod的版本问题，然后经过一系列的更新gem，更新rvm，更新ruby，更新cocoapods后问题还是存在，心塞。

目前
gem -v
gem版本2.7.7；

rvm -v
rvm版本1.29.9;

ruby -v
ruby版本2.3.7

可是rvm list
默认的ruby又是2.6.3

可是有的flutter项目是能跑起来的。不清楚哪里出了问题。。。
#### 问题截图  ####
![image](https://user-images.githubusercontent.com/19761833/66566023-8033a200-eb96-11e9-9936-9e0f5db2b322.png)

**Comment by kingsofish** [comment]
![image](https://user-images.githubusercontent.com/19761833/66621889-4905d500-ec18-11e9-9c12-81133a047315.png)

![image](https://user-images.githubusercontent.com/19761833/66622012-aa2da880-ec18-11e9-901e-296021424d85.png)

估计是cocoapods 的repo并没有AMapSearch指定的版本，导致cocoapod没办法更新AMapSearch到这个版本。然后.....一直装不上。估计pod repo update一下就行了，可是好鸡儿慢啊 我去

**Comment by kingsofish** [comment]
![image](https://user-images.githubusercontent.com/19761833/66623779-d7ca2000-ec1f-11e9-9ede-e0382e895695.png)
后面出现这种情况，用xcode打开，选择下证书和签名就行了。

处理完运行又出现这种问题。。。

![image](https://user-images.githubusercontent.com/19761833/66624067-24fac180-ec21-11e9-96dc-7f0d689c69c9.png)

查了一下，添加  
WidgetsFlutterBinding.ensureInitialized();
到main函数最上方


![image](https://user-images.githubusercontent.com/19761833/66624213-c3872280-ec21-11e9-90a1-62bf7de5f74b.png)

然后就能跑了。。。心好累一路磕磕撞撞。。终于能跑在iphone上了。安卓的木有试，估计没那么多坑吧

**Comment by simplezhli** [comment]
@kingsofish 感谢分享，我会将`WidgetsFlutterBinding.ensureInitialized()`补充上去。
