### ISSUE TITLE
点击tabbar到商品模块，报错

### ISSUE THREAD

**Issue by kingsofish** [simplezhli/flutter_deer#62]
### 运行环境 ###

电脑系统：macOS Mojave 10.14.6 (18G95)
设备型号：iPhone X 
设备系统版本： iOS 12.2
Flutter 版本：1.10.7

### 具体问题描述 ###
为什么连数据线调试，当点击tabbar到商品模块会报socket异常？手机画面一直卡在这个界面
![image](https://user-images.githubusercontent.com/19761833/66641364-322da580-ec4d-11e9-8fe1-e4c6b52f9904.png)

我试了一下安卓，在连数据线调试的情况下，安卓也会这样。

我试了下不连接数据线，直接打开Flutter Deer，点击tabbar到商品模块，是不会卡死的。不清楚是什么问题

#### 问题截图  ####
![image](https://user-images.githubusercontent.com/19761833/66640778-29889f80-ec4c-11e9-9773-ed3f48303bc6.png)

**Comment by simplezhli** [comment]
我在商品加载的图片链接中，故意写错了一个链接‘xxx’，这应该是图片加载报错的信息。没有使用过vsCode开发flutter，所以不清楚为什么异常信息会阻塞应用。

**Comment by kingsofish** [comment]
好的，这些报错有点坑
