### ISSUE TITLE
在vscode 允许不起来呢

### ISSUE THREAD

**Issue by codeAndylau** [simplezhli/flutter_deer#63]
Compiler message:
../../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_swiper-1.1.6/lib/src/swiper_pagination.dart:214:13: Error: Expected ',' before this.
            height: active ? activeSize : size,

**Comment by simplezhli** [comment]
@codeAndylau 请提供你的flutter 版本信息

**Comment by codeAndylau** [comment]
Flutter 1.9.8-pre.76 • channel revert-38861-use_frame_timings • https://github.com/flutter/flutter.git
Framework • revision 8e6f0e1b96 (6 weeks ago) • 2019-09-03 14:08:33 -0700
Engine • revision e7f9ef6aa0
Tools • Dart 2.5.0 (build 2.5.0-dev.4.0 36985859e4)

**Comment by simplezhli** [comment]
我无法定位到问题，建议你尝试1.9.1稳定版，看问题是否可以复现。
