### ISSUE TITLE
数据请求成功后如何更改StateType

### ISSUE THREAD

**Issue by wadewen** [simplezhli/flutter_deer#64]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Flutter 版本：如 `1.7.8`

### 具体问题描述 ###
数据请求成功后，页面还是显示的SkeletonList，没有刷新
 _buildBody() {
    return ChangeNotifierProvider<BaseListProvider<ChildListInfoEntity>>(
      builder: (_) => provider,
      child: Consumer<BaseListProvider<ChildListInfoEntity>>(
          builder: (_, provider, __) {

        if (provider.stateType == StateType.loading) {
          return SkeletonList(
            builder: (context, index) => ArticleSkeletonItem(),
          );
        }
        else if (provider.stateType == StateType.network) {
          return WidgetNotFound();
        }

        Log.d('StateType======='+provider.stateType.toString());

        return DeerListView(
          key: Key('order_search_list'),
          itemCount: provider.list.length,
          stateType: provider.stateType,
          onRefresh: _onRefresh,
          loadMore: _loadMore,
          itemExtent: 50.0,
          itemBuilder: (_, index) {
            return Container(
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
              alignment: Alignment.centerLeft,
              child: Text(provider.list[index].name),
            );
          },
        );
      }),
    );
  }

**Comment by simplezhli** [comment]
@wadewen 数据请求成功后，需要操作provider。详细的用法还是参看`order_search_page.dart`这个页面。
