### ISSUE TITLE
请问大佬是用什么工具或计算方式对设计稿的尺寸进行还原的

### ISSUE THREAD

**Issue by bigbirdhzp** [simplezhli/flutter_deer#66]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`iphone 6s`
- [x] 设备系统版本：如 `ios 13.1`
- [x] Flutter 版本：如 `1.9.1+hotfix.5`

### 具体问题描述 ###
请问大佬是用什么工具或计算方式对设计稿的尺寸进行还原的？
我尝试用flutter_screenutil这个插件，输入设计稿尺寸和组件尺寸，用iphone 6s进行测试。发现在设备上显示出来的组件尺寸和设计稿尺寸相差较大。
设计稿尺寸是750 X 1334.
iphone 6s的设备尺寸也是750 X 1334

**Comment by bigbirdhzp** [comment]
已经自己解决问题

**Comment by timmy-gzw** [comment]
方便问一下是怎么解决的吗? 想了解一下
