### ISSUE TITLE
项目跑不起来。

### ISSUE THREAD

**Issue by MuZiLee** [simplezhli/flutter_deer#67]
### 运行环境 ###

- [x] 电脑系统：如：`mac `
- [x] 设备型号：如：`华为nova4`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Flutter 版本：如 `v1.10.14`

#### 问题截图  ####
![image](https://user-images.githubusercontent.com/7467318/68556772-94f1a700-046e-11ea-8ed6-aadc602f9379.png)

**Comment by simplezhli** [comment]
@MuZiLee 问题应该是`NDK is missing a "platforms" directory`，不是缺失ndk的安装就是指定的ndk.dir不正确。
