### ISSUE TITLE
兼容性问题

### ISSUE THREAD

**Issue by ivantree** [simplezhli/flutter_deer#68]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`华为honor 20i`
- [x] 设备系统版本：如 `Android 9.1`
- [x] Flutter 版本：如 `1.9.1`

### 具体问题描述 ###
兼容性问题
#### 问题截图  ####
Because every version of flutter_driver from sdk depends on intl 0.16.0 and date_utils 0.1.0+2 depends on intl ^0.15.0, flutter_driver from sdk is incompatible with date_utils 0.1.0+2.
And because no versions of date_utils match >0.1.0+2 <0.2.0, flutter_driver from sdk is incompatible with date_utils ^0.1.0+2.
So, because buymiao depends on both date_utils ^0.1.0+2 and flutter_driver any from sdk, version solving failed.

**Comment by simplezhli** [comment]
@ivantree 你确定你是最新的代码吗？之前有过这个问题，所以date_utils这个库很早就去掉了。

**Comment by ivantree** [comment]
@simplezhli 确实，没有及时更新，多谢！
