### ISSUE TITLE
安装包下不了

### ISSUE THREAD

**Issue by Denny-coder** [simplezhli/flutter_deer#69]
提示：**你不能下载这个App。请确认你是这个应用的用户，请确认您登录的账号是正确的**

**Comment by simplezhli** [comment]
前一阵蒲公英有点问题，我重新设置了一下。你再试试，安装密码 111111。

**Comment by Denny-coder** [comment]
@simplezhli 可以了，感谢大佬回复

**Comment by simplezhli** [comment]
@Denny-coder 这问题，我还没注意到。。。感谢反馈！
