### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by daofeng2015** [simplezhli/flutter_deer#71]
### 运行环境 ###

- [x] 电脑系统：`Windows 10`
- [x] 设备型号：`雷电模拟器`
- [x] 设备系统版本： `Android 9.0`
- [x] Flutter 版本： `1.9.1`

### 具体问题描述 ###
拉的最新代码,直接运行flutter run提示这个
#### 问题截图  ####
![QQ截图20191130223326](https://user-images.githubusercontent.com/14891398/69901813-7a518480-13c1-11ea-99c8-093dc70309ab.png)

**Comment by simplezhli** [comment]
@daofeng2015 尝试将image_picker升至 0.6.1+9

**Comment by daofeng2015** [comment]
> @daofeng2015 尝试将image_picker升至 0.6.1+9

![QQ截图20191202152347](https://user-images.githubusercontent.com/14891398/69938279-d5958b00-1517-11ea-853a-689c214ef213.png)
image_picker: 0.6.2+1 升级到最新版还是一样报错

**Comment by simplezhli** [comment]
@daofeng2015 我没办法了，建议你重装Flutter sdk。。。

**Comment by daofeng2015** [comment]
> @daofeng2015 我没办法了，建议你重装Flutter sdk。。。确保使用1.9.1稳定版。

sdk重装也没用  最后我修改了classpath 'com.android.tools.build:gradle:3.4.2' 为3.5.2最新版就不报错了..神奇问题解决了...

**Comment by simplezhli** [comment]
@daofeng2015 厉害了👍
