### ISSUE TITLE
运行debug报错 

### ISSUE THREAD

**Issue by jacky-yanglei** [simplezhli/flutter_deer#72]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`

### 具体问题描述 ###

执行debug 

#### 问题截图  ####

![7GD~}HND4IX)G69FLOVFB52](https://user-images.githubusercontent.com/17645850/70415029-ab534880-1a96-11ea-8b7b-1fcc06d58500.png)

**Comment by simplezhli** [comment]
@jacky-yanglei 看异常是没有下载对应版本的kotlin插件，可能是网络原因下载不成功。多尝试几次，或者修改maven仓库地址
