### ISSUE TITLE
是否有multipart/form-data上传图片的dio封装可以分享一下

### ISSUE THREAD

**Issue by suddenhu** [simplezhli/flutter_deer#74]
是否有multipart/form-data上传图片的dio封装可以分享一下,我现在这块使用有点问题，还望指教一下

**Comment by simplezhli** [comment]
@suddenhu 代码中有图片上传的代码：https://github.com/simplezhli/flutter_deer/blob/b8c63a5bb01c9926589389399cd791c0c76257c8/lib/mvp/base_page_presenter.dart#L94，详细可以参考dio文档：https://github.com/flutterchina/dio/blob/master/README-ZH.md#多文件上传

**Comment by suddenhu** [comment]
可以接受裁剪压缩的文件格式么？
`Uint8List data = await cut(editorKey.currentState);
    List<int> result = await getCompressList(data);
    FormData param = FormData.fromMap({
      'files': [
        MultipartFile.fromBytes(result),
      ]
    });`
这样的方式

**Comment by simplezhli** [comment]
和裁剪压缩无关，只要保证最终是文件就行。至于使用`MultipartFile.fromBytes`的方式，没有尝试过。
