### ISSUE TITLE
The getter 'profile' was called on null.

### ISSUE THREAD

**Issue by ivantree** [simplezhli/flutter_deer#77]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Flutter 版本：如 `1.9.1`

### 具体问题描述 ###
从API提取数据时出错，请教
#### 问题截图  ####
![1576382075(1)](https://user-images.githubusercontent.com/9014680/70857890-ceb44280-1f31-11ea-8e03-5a87e77eaee4.png)

#### 异常日志 ####
════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
The getter 'profile' was called on null.
Receiver: null
Tried calling: profile
User-created ancestor of the error-causing widget was: 
![1576382265(1)](https://user-images.githubusercontent.com/9014680/70857896-294d9e80-1f32-11ea-9da1-16c8f0577819.png)

**Comment by simplezhli** [comment]
很明显，UserEntity中的UserProfile没有实例化。在你的数据没有获取到之前，这部分需要你自己处理。例如，判断profile为空时显示什么内容。

**Comment by simplezhli** [comment]
还要就是与本项目无关的内容不要提issue，本人精力也有限。。。
