### ISSUE TITLE
“商品”Tab页，商品删除异常

### ISSUE THREAD

**Issue by bigbirdhzp** [simplezhli/flutter_deer#78]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`OPPO Find-X`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Flutter 版本：如 `1.12.13+hotfix.5`

### 具体问题描述 ###
先感谢大佬分享这个项目。刚下的安装包，复现流程如下：
点击底部“商品”Tab，点击商品的右上省略号，点击删除商品的时候，并不是删除指定要删除的商品，而是从删除最底部的商品开始删除。
另外，删除商品之后，顶部标签“在售”隔壁的数字也没有更改

#### 问题截图  ####
![image](https://user-images.githubusercontent.com/22903159/70984258-1d5e0a00-20f5-11ea-9875-2c7e2f80a49a.png)

**Comment by simplezhli** [comment]
你观察的很仔细。不过因为这个项目没有具体相关的接口，所以数据都是写死的，所以会导致这类问题。 确实会产生误解，我后面修改一下，尽量接近真实操作效果。

**Comment by bigbirdhzp** [comment]
> 你观察的很仔细。不过因为这个项目没有具体相关的接口，所以数据都是写死的，所以会导致这类问题。 确实会产生误解，我后面修改一下，尽量接近真实操作效果。

我提出了issue之后也去看了代码，也看到数据是写死的😄
