### ISSUE TITLE
大佬是怎么适配屏幕的

### ISSUE THREAD

**Issue by 134355** [simplezhli/flutter_deer#79]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Flutter 版本：如 `1.9.1`

**Comment by simplezhli** [comment]
Flutter的单位默认和安卓所使用的dp比较像，具备一定的适配能力，已经满足大部分适配需求。要是对适配有较高要求的话，可以尝试[flutter_screenutil](https://github.com/OpenFlutter/flutter_screenutil)这个库。

**Comment by simplezhli** [comment]
其他的适配都是通用的，比如保持View的长宽比、View的长或宽占据屏幕的百分比之类的可以使用Flutter的AspectRatio和FractionallySizedBox。

**Comment by 134355** [comment]
好的，膜拜大佬发自我的华为手机-------- 原始邮件 --------发件人： 唯鹿 <notifications@github.com>日期： 2019年12月23日周一 21:58收件人： simplezhli/flutter_deer <flutter_deer@noreply.github.com>抄送： 134355 <13435512130@163.com>, Author <author@noreply.github.com>主    题： Re: [simplezhli/flutter_deer] 大佬是怎么适配屏幕的 (#79)Flutter的单位默认和安卓所使用的dp比较像，具备一定的适配能力，已经满足大部分适配需求。要是对适配有较高要求的话，可以尝试flutter_screenutil这个库。

**Comment by 134355** [comment]
感谢大佬指导发自我的华为手机-------- 原始邮件 --------发件人： 唯鹿 <notifications@github.com>日期： 2019年12月23日周一 22:06收件人： simplezhli/flutter_deer <flutter_deer@noreply.github.com>抄送： 134355 <13435512130@163.com>, Author <author@noreply.github.com>主    题： Re: [simplezhli/flutter_deer] 大佬是怎么适配屏幕的 (#79)其他的适配都是通用的，比如保持View的长宽比、View的长或宽占据屏幕的百分比之类的可以使用Flutter的AspectRatio和FractionallySizedBox。
