### ISSUE TITLE
硬件相关的处理

### ISSUE THREAD

**Issue by wuhuaqing** [simplezhli/flutter_deer#8]
请问flutter中调用Android 或者 ios 的硬件是怎样处理的呢，例如摄像头，传感器 等。

**Comment by simplezhli** [comment]
这类主要还是通过Flutter的MethodChannel和原生通信来调用原生来实现。你可以参考https://github.com/flutter/plugins/tree/master/packages/url_launcher  这种简单的插件来了解。
