### ISSUE TITLE
在别的页面怎么刷新shop_page的provider

### ISSUE THREAD

**Issue by newyearsoft** [simplezhli/flutter_deer#81]
假设provider.user?.avatarUrl 的头像在别的页面被更新了。回到shop_page头像怎么跟着变化呢？
要怎么重新刷新provider呢？

UserEntity _user;
UserEntity get user => _user;
在别的页面调用这个方法去更新Provider
onTap: () => Provider.of<UserProvider>(context).setUser(user),

提示错误
Another exception was thrown: Error: Could not find the correct Provider<UserProvider> above this AccountManagerPage Widget

**Comment by simplezhli** [comment]
其实这属于provider的用法。如果要在其他页面使用，需要这个provider存在于这两个页面的上层。所以你会看到很多provider的用法都放在了MyApp上。不过具体要根据实际情况使用，也别一味的放到最上层。
