### ISSUE TITLE
MyApp 和 home

### ISSUE THREAD

**Issue by liongkj** [simplezhli/flutter_deer#82]
### 具体问题描述 ###
想了解下myapp 和home page是怎么链接起来的？我想放一个provider让用户可以手动换语言。可是在myapp放的provider 在bottom navigation bar呼叫不了。

**Comment by simplezhli** [comment]
我的代码中有个类似功能，打开夜间模式。这个属于provider的使用，你可以参靠这个的做法。

**Comment by liongkj** [comment]
你好，我是参考了主题切换。我是成功setState了，可是bottom navigation bar没被rebuild。
这个是我的代码
![code](https://user-images.githubusercontent.com/20205301/71703470-9ce71b00-2e0f-11ea-973a-c1650bb790c5.png)
![code](https://user-images.githubusercontent.com/20205301/71703492-be480700-2e0f-11ea-9ea1-e300a9156671.png)

**Comment by simplezhli** [comment]
BottomNavigationBar在路由的push和pop时，都会rebuild的。

**Comment by simplezhli** [comment]
BottomNavigationBar部分的代码，你有没有处理文字的切换。

**Comment by liongkj** [comment]
![code](https://user-images.githubusercontent.com/20205301/71704119-5b586f00-2e13-11ea-8492-6cd03e45b05d.png)
有的，如果我手动切换系统语言，app语言是会跟着系统语言的。
我app的其他部分能rebuild，只是bottom navigation bar不怎么了解

**Comment by simplezhli** [comment]
了解了。你看代码中有个`_list == null`的判断，这个其实是我为了避免重复创建使用的。

**Comment by liongkj** [comment]
马上可以了！太感谢你了大神！
