### ISSUE TITLE
App启动时先显示白屏，然后再显示Flutter Deer图片

### ISSUE THREAD

**Issue by zinwalin** [simplezhli/flutter_deer#84]
### 运行环境 ###

- [x] 电脑系统：`macOS, Win10`
- [x] 设备型号：`小米MIX 2s, iPhone 6S, iPhone 11`
- [x] 设备系统版本：`Android 9.0, iOS 13`
- [x] Flutter 版本： `v1.12.13+hotfix.5`

### 具体问题描述 ###
正常情况应该是：  点击App后， 直接就显示SplashPage(也就是Flutter Deer图片）

参考此项目  https://github.com/Sky24n/flutter_wanandroid

#### 问题截图  ####
![image](https://user-images.githubusercontent.com/5416196/71789864-6e17b180-3068-11ea-8217-e3e1e044e282.png)

![image](https://user-images.githubusercontent.com/5416196/71789851-5d673b80-3068-11ea-97d0-e9056a5a1dfd.png)

**Comment by simplezhli** [comment]
这个只是没有在Android和iOS原生上去适配启动页，我只做了简单的深色模式的处理。

**Comment by simplezhli** [comment]
release模式下这个问题会好很多，并且原生与Flutter之间的过渡适配也是一个问题。所以没有处理这块。

**Comment by zinwalin** [comment]
> release模式下这个问题会好很多，并且原生与Flutter之间的过渡适配也是一个问题。所以没有处理这块。

换成Release模式编译， 跑起来确实问题消失了， 至少过渡更自然。

**Comment by zinwalin** [comment]
> 这个只是没有在Android和iOS原生上去适配启动页，我只做了简单的深色模式的处理。

阿里的flutter go处理得不错  https://github.com/alibaba/flutter-go

你有之方面适配的思路吗？   感觉启动页面和加载速度对用户体验影响很大。

**Comment by simplezhli** [comment]
flutter_wanandroid和flutter-go都是我早期学习Flutter时看过的项目，它们的适配方法很简单，就是使用一张图片替换原有的背景色。这种方法不牵扯过渡问题，但是在全面屏的手机上会拉伸图片，这个就是我说的一个适配问题。解决拉伸问题就是准备多套图片，同时Flutter也要相应的去处理。当然这种适用于启动页就是一张复杂的图片。

对于deer这个项目来说，启动页主要是一个logo加纯色背景，所以我只在原生的部分处理了背景色。当然也可以将logo放在原生处理，这里图片不会拉伸，但是会有过渡问题。要保证原生与Flutter的启动页切换时大小位置没有变化，这块确实会麻烦点。（如果logo位置是居中相对简单）

两种方法各有优劣，适合不同的场景。要完善各自的缺点都需要下点功夫。

**Comment by simplezhli** [comment]
理想情况是使用第二种方法，但是图片使用第一种方案的大图。这样图片没有拉伸，图片覆盖不到的地方使用背景色来填充。
