### ISSUE TITLE
项目不使用flutter_2d_amap,注释掉该插件报错,项目跑不起来

### ISSUE THREAD

**Issue by hgxin** [simplezhli/flutter_deer#85]
### 运行环境 ###

- [x] Flutter 版本：如 `1.9.1`

### 具体问题描述 ###
  # 高德2D地图插件 https://github.com/simplezhli/flutter_2d_amap
  #flutter_2d_amap:

#### 异常日志 ####
ע: D:\flutter\.pub-cache\hosted\pub.flutter-io.cn\url_launcher-5.2.3\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.javaʹ�û򸲸����ѹ�ʱ�� API��

ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣

ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��

ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣

F:\flutter demo\toutiao_flutter\android\app\src\main\java\com\weilu\deer\DeerPickerProvider.java:4: ����: �����androidx.core.content������

import androidx.core.content.FileProvider;

                            ^

F:\flutter demo\toutiao_flutter\android\app\src\main\java\com\weilu\deer\DeerPickerProvider.java:11: ����: �Ҳ�������

public class DeerPickerProvider extends FileProvider {

                                        ^

  ����: �� FileProvider

F:\flutter demo\toutiao_flutter\android\app\src\main\java\com\weilu\deer\FileProvider7.java:10: ����: �����androidx.core.content������

import androidx.core.content.FileProvider;

                            ^

F:\flutter demo\toutiao_flutter\android\app\src\main\java\com\weilu\deer\FileProvider7.java:30: ����: �Ҳ�������

        return FileProvider.getUriForFile(context, context.getPackageName() + ".Merchant", file);

               ^

  ����:   ��� FileProvider

  λ��: �� FileProvider7

4 ������
Running Gradle task 'assembleDebug'...                             48.6s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1

**Comment by simplezhli** [comment]
@hgxin 保证你的flutter sdk为1.12.13+hotfix.5，拉取最新代码再尝试。
