### ISSUE TITLE
token失效刷新  为什么无效

### ISSUE THREAD

**Issue by yangxiansheng123** [simplezhli/flutter_deer#87]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Flutter 版本：如 `1.9.1`

### 具体问题描述 ###
登录成功  返回 token及refreshToken  然后请求头 设置token  请求时返回401    

#### 问题截图  ####

这是token：
eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5cGYiLCJzY29wZXMiOlsiQ1VTVE9NRVJfVVNFUiJdLCJ1c2VySWQiOiJmYjZiNzNkMC0xY2FiLTExZWEtOTliZi1kMTMyMGI3MjhkMTIiLCJ1c2VyTmFtZSI6InlwZiIsImVuYWJsZWQiOnRydWUsImlzUHVibGljIjpmYWxzZSwicGVybWlzc2lvbnMiOlsiZGVwdCIsIkF1dG9GaXJlQWxhcm1fRGV2aWNlRGV0YWlsSW5mbyIsIkF1dG9GaXJlQWxhcm1fRGV2aWNlTWFuYWdlIiwicm9sZSIsIkF1dG9GaXJlQWxhcm1fRGV2aWNlTWFuYWdlX2RlbGV0ZSIsIkF1dG9GaXJlQWxhcm1fQXV0b0FsYXJtTWFuYWdlX2VkaXQiLCJBdXRvRmlyZUFsYXJtX1RlbGVtZXRyeURhdGFWaXN1YWxfZWRpdCIsIkF1dG9GaXJlQWxhcm1fQXV0b0FsYXJtTWFuYWdlX3ZpZXciLCJ1c2VyIiwiQXV0b0ZpcmVBbGFybV9EZXZpY2VNYW5hZ2VfdmlldyIsIkF1dG9GaXJlQWxhcm1fQXV0b0FsYXJtTWFuYWdlIiwic3lzdGVtIiwiQXV0b0ZpcmVBbGFybSIsIkF1dG9GaXJlQWxhcm1fRGV2aWNlTWFuYWdlX2VkaXQiLCJBdXRvRmlyZUFsYXJtX1RlbGVtZXRyeURhdGFWaXN1YWxfdmlldyIsIkF1dG9GaXJlQWxhcm1fVGVsZW1ldHJ5RGF0YVZpc3VhbCJdLCJ0ZW5hbnRJZCI6ImNhMmFhMmMwLWRlYTYtMTFlOS1iM2JlLTRiMzgxMmIwZTQzMCIsImlzcyI6InFpZ3VhbmciLCJpYXQiOjE1Nzg5ODA4MTMsImV4cCI6MTU3ODk4OTgxM30.ZNSHhLeo56bYai_qTbL8zP4qHutZLH2f45jlFgSSjIA30DpdYeByXDkZzAnwhqxCrZtmvQ4rJWFpjNzJSk9JWQ

I/flutter (29632): DEER-LOG   e   RequestUrl: http://192.168.8.76:8080/api/http://192.168.8.76:8080/api/alarm2/get_message
I/flutter (29632): DEER-LOG   e   RequestMethod: GET
I/flutter (29632): DEER-LOG   e   RequestHeaders:{content-type: application/json; charset=utf-8, authorization: BearereyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ5cGYiLCJzY29wZXMiOlsiQ1VTVE9NRVJfVVNFUiJdLCJ1c2VySWQiOiJmYjZiNzNkMC0xY2FiLTExZWEtOTliZi1kMTMyMGI3MjhkMTIiLCJ1c2VyTmFtZSI6InlwZiIsImVuYWJsZWQiOnRydWUsImlzUHVibGljIjpmYWxzZSwicGVybWlzc2lvbnMiOlsiZGVwdCIsIkF1dG9GaXJlQWxhcm1fRGV2aWNlRGV0YWlsSW5mbyIsIkF1dG9GaXJlQWxhcm1fRGV2aWNlTWFuYWdlIiwicm9sZSIsIkF1dG9GaXJlQWxhcm1fRGV2aWNlTWFuYWdlX2RlbGV0ZSIsIkF1dG9GaXJlQWxhcm1fQXV0b0FsYXJtTWFuYWdlX2VkaXQiLCJBdXR
I/flutter (29632): DEER-LOG   e   vRmlyZUFsYXJtX1RlbGVtZXRyeURhdGFWaXN1YWxfZWRpdCIsIkF1dG9GaXJlQWxhcm1fQXV0b0FsYXJtTWFuYWdlX3ZpZXciLCJ1c2VyIiwiQXV0b0ZpcmVBbGFybV9EZXZpY2VNYW5hZ2VfdmlldyIsIkF1dG9GaXJlQWxhcm1fQXV0b0FsYXJtTWFuYWdlIiwic3lzdGVtIiwiQXV0b0ZpcmVBbGFybSIsIkF1dG9GaXJlQWxhcm1fRGV2aWNlTWFuYWdlX2VkaXQiLCJBdXRvRmlyZUFsYXJtX1RlbGVtZXRyeURhdGFWaXN1YWxfdmlldyIsIkF1dG9GaXJlQWxhcm1fVGVsZW1ldHJ5RGF0YVZpc3VhbCJdLCJ0ZW5hbnRJZCI6ImNhMmFhMmMwLWRlYTYtMTFlOS1iM2JlLTRiMzgxMmIwZTQzMCIsImlzcyI6InFpZ3VhbmciLCJpYXQiOjE1Nzg5ODA4MTMsImV4cCI6MTU3ODk4OTgxM30
I/flutter (29632): DEER-LOG   e   .ZNSHhLeo56bYai_qTbL8zP4qHutZLH2f45jlFgSSjIA30DpdYeByXDkZzAnwhqxCrZtmvQ4rJWFpjNzJSk9JWQ}
I/flutter (29632): DEER-LOG   e   RequestContentType: application/json; charset=utf-8
I/flutter (29632): DEER-LOG   e   RequestData: {pageNo: 1, pageSize: 10, keyword: }
I/flutter (29632): DEER-LOG   e   ResponseCode: 401
I/flutter (29632): DEER-LOG   e   ----------End: 81 毫秒----------
I/flutter (29632): DEER-LOG   e   接口请求异常： code: 401, mag: Authentication Failed. Username or Password not valid.

**Comment by simplezhli** [comment]
你可以根据异常信息与后端沟通，传参方式请查阅dio文档。此问题与本项目无关，已关闭。

**Comment by yangxiansheng123** [comment]
这个接口Java写的可以访问并在Android 原生写的接口都时没问题的，大佬你确定你这个拦截器写的没问题？？你测试过么？？

**Comment by simplezhli** [comment]
首先我的项目中就在使用，我可以保证没有问题。其次传参规则需要根据具体的接口要做调整的，你直接套用的我拦截器我不保证有效。

**Comment by simplezhli** [comment]
![image](https://user-images.githubusercontent.com/12456431/72319158-6ba4ff80-36d9-11ea-926a-f02e88f674c5.png)

比如这个前缀是你们要求的吗？

**Comment by yangxiansheng123** [comment]
你好    DioUtils.instance.asyncRequestNetwork(
        Method.get, "http://192.168.8.76:8080/api/alarm2/get_message",
        queryParameters: {
          "pageNo": "1",
          "pageSize": "10",
          "keyword": "",
        },);  我这样传参有什么问题么？？上面你说的那个Bearer前缀 时要传的

**Comment by yangxiansheng123** [comment]
DioUtils.instance
        .asyncRequestNetwork(Method.post, API.BASE_URL + "auth/login", params: {
      "username": account,
      "password": pwd,
      "tenantId": "000000",
      "type": "account",
    }, onSuccess: (LoginEntityEntity login) {
      _savePersonInfo(login);
    }, onError: (int code, String err) {
      log("code==============" + "" + err);
    });这样请求 是可以拿到  token和  refreshToken   但是后面调用接口时 请求头添加token就会出现  401问题  ，大佬  会是什么问题造成的？？？

**Comment by simplezhli** [comment]
你们添加token的规则是什么，异常信息来看是token错误

**Comment by yangxiansheng123** [comment]
token失效  用refreshToken刷新 重新获取token

**Comment by simplezhli** [comment]
我指的是传token的方式

**Comment by yangxiansheng123** [comment]
String accessToken = SpUtil.getString(Constant.accessToken);
    if (accessToken.isNotEmpty) {
      options.headers['Authorization'] = '$accessToken';
    }

    return super.onRequest(options);
  }

token 头部统一添加  这个在Android  原生是通的 看了你的项目后  按着你的这个调接口 就出现这样问题了

**Comment by simplezhli** [comment]
这里并没有你说的“Bearer”前缀，还有你一开始发的Log信息中，Get请求参数并没有传入`queryParameters`中，倒是传入了`params`。

**Comment by yangxiansheng123** [comment]
我的失误   加入Bearer 还是401   传queryParameters  及params  还是401

**Comment by simplezhli** [comment]
你还是给我Android部分的传token的代码吧，这样下去我根本找不出问题。

**Comment by yangxiansheng123** [comment]
Interceptor tokenInterceptor = new Interceptor() {  //全局拦截器，往请求头部添加 token 字段，实现了全局添加 token
            @Override
            public okhttp3.Response intercept(Chain chain) throws IOException {
                Request originalRequest = chain.request();//获取原始请求
                Request.Builder requestBuilder = originalRequest.newBuilder() //建立新的请求
                        .addHeader("Accept", "application/json")
                        .addHeader("Content-Type", "application/json;charset=utf-8")
//                        .removeHeader("User-Agent")
//                        .addHeader("User-Agent",BaseUtils.getUserAgent())
                        .method(originalRequest.method(), originalRequest.body());
                Logger.d(originalRequest.toString());
                Request tokenRequest = null; //带有token的请求
                if (TextUtils.isEmpty(SPUtil.getString(SPUtil.SP_TOKEN_TAG))) {
                    return chain.proceed(requestBuilder.build());
                }

                tokenRequest = requestBuilder
                        .header("X-Authorization", "Bearer " + SPUtil.getString(SPUtil.SP_TOKEN_TAG))  //添加token
                        .build();
                return chain.proceed(tokenRequest);
            }
        };


        //拦截返回体  判断token是否过期.过期重写拉取新的token
        Interceptor tokenRespInterceptor = new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Request request = chain.request();
                Response response = chain.proceed(request);
                if (isTokenExpired(response)) {
                    Logger.d("RetrofitHelper_", "自动刷新Token,然后重新请求数据");
                    //同步请求方式，获取最新的Token
                    if (getNewToken()) {
                        //使用新的Token，创建新的请求
                        Request newRequest = chain.request()
                                .newBuilder()
                                .header("token", SPUtil.getString(SPUtil.SP_TOKEN_TAG))
                                .build();
                        //重新请求
                        return chain.proceed(newRequest);
                    }
                }
                return response.newBuilder().body(ResponseBody.create(MediaType.parse("UTF-8"), body)).build();
            }
        };

**Comment by yangxiansheng123** [comment]
谢谢  大佬   options.headers['X-Authorization'] = 'Bearer $accessToken';  好了

**Comment by simplezhli** [comment]
是啊，你的Android代码中用的是`X-Authorization`，包括刷新token的部分添加了`header("token", SPUtil.getString(SPUtil.SP_TOKEN_TAG))`。这部分你要自己修改的。

**Comment by yangxiansheng123** [comment]
谢谢 大佬了  ['X-Authorization']  这个没注意啊

**Comment by simplezhli** [comment]
看在我帮助你的份上，记得给我投票，哈哈！

**Comment by yangxiansheng123** [comment]
早已投了 杠杠的

**Comment by simplezhli** [comment]
![B0F1EAD1673715AACBB63CF58A196895](https://user-images.githubusercontent.com/12456431/72321796-c5102d00-36df-11ea-892f-e3deaf575173.gif)

**Comment by yangxiansheng123** [comment]
你这一串着字符  是啥？？打不开
