### ISSUE TITLE
Flutter app， 点击按钮或Tab时， 会有水波纹， 怎么去除？

### ISSUE THREAD

**Issue by zinwalin** [simplezhli/flutter_deer#88]
### 运行环境 ###

- [x] 电脑系统：`macOS, Win10`
- [x] 设备型号：`小米MIX 2s, iPhone 6S, iPhone 11`
- [x] 设备系统版本：`Android 9.0, iOS 13`
- [x] Flutter 版本： `v1.12.13+hotfix.5`

**Comment by simplezhli** [comment]
Tab的处理方法deer的代码中有两处，你自己去寻找。按钮的可以去看`highlightColor`、`splashColor`属性。

这类与本项目无关的问题我会直接关闭，希望自己多多思考和查找。
