### ISSUE TITLE
项目一运行sp初始化报错，找了好久没找到原因,大佬帮忙瞅瞅，谢谢！

### ISSUE THREAD

**Issue by userhjp** [simplezhli/flutter_deer#89]
![image](https://user-images.githubusercontent.com/31978565/72662686-ded5ab00-3a24-11ea-9dd0-26d39b6f315e.png)
![image](https://user-images.githubusercontent.com/31978565/72662700-12b0d080-3a25-11ea-8bef-52116d72ab80.png)
![image](https://user-images.githubusercontent.com/31978565/72662736-9b2f7100-3a25-11ea-85db-269e479b8c18.png)
// 上面好像图片出不来

await SpUtil.getInstance(); 项目运行启动执行这句代码初始化sp的时候报错；

E/flutter ( 9949): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
E/flutter ( 9949): #0      SpUtil._init (package:flutterapp/utils/shared_preferences.dart:19:12)
E/flutter ( 9949): <asynchronous suspension>
E/flutter ( 9949): #1      SpUtil.getInstance (package:flutterapp/utils/shared_preferences.dart:25:23)
E/flutter ( 9949): #2      _SplashPageState.initState.<anonymous closure> (package:flutterapp/home/splash_page.dart:34:20)
E/flutter ( 9949): #3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
E/flutter ( 9949): #4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1049:9)
E/flutter ( 9949): #5      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:850:7)
E/flutter ( 9949): #6      _rootRun (dart:async/zone.dart:1122:38)
E/flutter ( 9949): #7      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 9949): #8      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 9949): #9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter ( 9949): #10     _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 9949): #11     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 9949): #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
E/flutter ( 9949): #13     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 9949): #14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
E/flutter ( 9949): #15     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
E/flutter ( 9949): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by simplezhli** [comment]
@userhjp ？？解决了吗？

**Comment by ivantree** [comment]
@userhjp 同样的问题，怎么解决的？求助

**Comment by simplezhli** [comment]
@ivantree 如果是`MissingPluginException`问题，使用命令`flutter pub get`确保相关依赖库拉取成功。

**Comment by ivantree** [comment]
不知道问题出在哪里 @simplezhli 


![Uploading {35422396-4887-47B7-B1F7-B5F09D4D73B9}_20200203204536.jpg…]()
![Uploading {A8595B52-6F38-4E0C-8642-AF1C9C92EDDC}_20200203205138.jpg…]()
![Uploading {D56A07D6-A9C4-4265-8AB4-0CB48B7CA4BE}_20200203204950.jpg…]()
![Uploading {EB8BDB1B-FEE0-46CA-9761-E844A4E6BD74}_20200203205508.jpg…]()
![Uploading EF787F69-B75B-4fa5-9FBA-7845B6F27EAD.png…]()

**Comment by ivantree** [comment]
不知道问题出在哪里，谢谢！ @simplezhli 
![01](https://user-images.githubusercontent.com/9014680/73655236-77785600-46c8-11ea-9738-9909b968449d.jpg)
![02](https://user-images.githubusercontent.com/9014680/73655241-7b0bdd00-46c8-11ea-954c-4d0aaa92717d.jpg)
![{D56A07D6-A9C4-4265-8AB4-0CB48B7CA4BE}_20200203204950](https://user-images.githubusercontent.com/9014680/73655249-8232eb00-46c8-11ea-8456-62e6032e70ef.jpg)
![{A8595B52-6F38-4E0C-8642-AF1C9C92EDDC}_20200203205138](https://user-images.githubusercontent.com/9014680/73655274-9545bb00-46c8-11ea-966e-c06951881c94.jpg)
![{D56A07D6-A9C4-4265-8AB4-0CB48B7CA4BE}_20200203204950](https://user-images.githubusercontent.com/9014680/73655279-9aa30580-46c8-11ea-8dde-2dd49e054938.jpg)
![EF787F69-B75B-4fa5-9FBA-7845B6F27EAD](https://user-images.githubusercontent.com/9014680/73655285-9ecf2300-46c8-11ea-8b4a-a99091e7c845.png)

**Comment by userhjp** [comment]
上次出现问题，莫名其妙好了，真是莫名其妙就正常了，我回想了下好像没做什么特别的操作，然后就在今天，我更新Flutter version 1.14.2-pre.51 到 Flutter 1.14.7-pre.83  这个问题又出现了，现在我还是一脸懵逼，但是我发现一个问题 无论什么时候，打包时候shared_preferences都会报一个错误：
C:\Users\user\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\shared_preferences-0.5.6+1\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: ����: [deprecati
on] FlutterPluginBinding�е�getFlutterEngine()�ѹ�ʱ
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());

不知道是否是这个问题引起的，最近工作也开始忙了，只能先搁置了，纠结

**Comment by userhjp** [comment]
> @userhjp同样的问题，怎么解决的？求助

上次莫名其妙好了，这次又出现了，我也是一脸懵逼，没想到还有人跟我遇到同样的问题，我还以为就是我一个人环境问题呢0.0

**Comment by ivantree** [comment]
问题在于修改了Android里面的源码引起的，我回滚了Android里main下的文件就好了

**Comment by simplezhli** [comment]
怕是初始化的顺序问题，我这边无法复现这个问题，你尝试一下在main方法中添加`WidgetsFlutterBinding.ensureInitialized();`

<img width="634" alt="image" src="https://user-images.githubusercontent.com/12456431/73706429-5dc02880-4733-11ea-9f07-f39d76f2e69a.png">

**Comment by ivantree** [comment]
回滚 fluter SDK v1.12.13+hotfix.5 同样可以解决问题

**Comment by simplezhli** [comment]
@userhjp @ivantree 看来与升级Android项目有关。https://github.com/flutter/flutter/issues/44171

**Comment by userhjp** [comment]
问题解决了，需要在 android\app\src\main\java\com\weilu\deer\MainActivity.java 文件添加一行代码，因为默认项目创建时候，MainActivity是用Kotlin语言编写的，其中在 configureFlutterEngine 方法中 有一句代码
`GeneratedPluginRegistrant.registerWith(flutterEngine);`
flutter_deer将该文件替换为了java语言，可能是方便用java自己写插件，但是不知道为什么在flutter_deer中却没有写上这句代码，更奇特的是为什么在某些情况是正常的，原谅我菜，不太懂原生开发 - -，现在我将这句代码加上后项目就能正常运行了，虽然项目在第一次编译的时候还是会出现错误`C:\Users\user\AppData\Roaming\Pub\Cache\hosted\pub.flutter-io.cn\shared_preferences-0.5.6+1\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: ����: [deprecati
on] FlutterPluginBinding�е�getFlutterEngine()�ѹ�ʱ
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());`
这个错误自项目运行以来一直都有。

这是修改后的MainActivity.java：

`package com.example.flutter_app;

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugins.GeneratedPluginRegistrant; // 引用

public class MainActivity extends FlutterActivity {
  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    flutterEngine.getPlugins().add(new InstallAPKPlugin(this));
    GeneratedPluginRegistrant.registerWith(flutterEngine); // 这句
  }
}
`

Flutter版本信息：
`
Flutter 1.14.7-pre.83 • channel master • https://github.com/flutter/flutter.git
Framework • revision e10df3c1a6 (3 days ago) • 2020-02-01 11:23:01 +0800
Engine • revision e625e174c5
Tools • Dart 2.8.0 (build 2.8.0-dev.6.0 5ae5aff640)
`

**Comment by simplezhli** [comment]
@userhjp 你提到的`GeneratedPluginRegistrant.registerWith(flutterEngine)`这句代码已经在`FlutterActivity`的`onCreate`中调用过了，不需要重复添加，多次调用会造成权限授权影响。至于kotlin文件的问题，因为项目创建比较早，当时默认创建Flutter项目还没有kotlin支持，但这个并不影响这个问题。

现在还是怀疑初始化的顺序有问题，可能在调用sp时，channel还没有创建。我之前提供的方法有没有效果？？如果实在不行，尝试使用`flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());`代替`GeneratedPluginRegistrant.registerWith(flutterEngine)`进行二次初始化。

还有就是你的Flutter版本很新，希望可以使用稳定版测试，好排除版本差异的影响。希望给予反馈，我好跟进这个问题。

**Comment by userhjp** [comment]
![image](https://user-images.githubusercontent.com/31978565/73722091-ab9f5580-4760-11ea-9232-168240581cc7.png)
![image](https://user-images.githubusercontent.com/31978565/73722883-8ca1c300-4762-11ea-8f12-ae8e18f809f3.png)

我只在你的 MyApp 类中找到重写onCreate方法，MyApp继承FlutterApplication 并重写onCreate 调用 super.onCreate(); 并没有再做其他操作， 意思是在这步已经进行初始化完成了？

你之前说的 在main方法中调用 WidgetsFlutterBinding.ensureInitialized();我试过，实际上并没有效果；

现在我按照你说的方式用`flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());`进行初始化也是可以的，这证明只是sp一个插件初始化失败了，其他插件初始化是正常的，可能真是初始化顺序原因？这顺序现在好像也没有主动去控制它在什么时候初始化啊，有点迷。不知道你项目有没有存在 flutter clean后重新flutter run 会提示一些错误问题，一般都是些不建议使用某某插件错误，唯独SharedPreferences 在报错误 
`setupChannel(binding.getFlutterEngine() .getDartExecutor(), binding.getApplicationContext());`
binding.getFlutterEngine() 这句代码编译期间报错，一直存在，我在想这个问题是插件的问题还是我项目环境的问题，我尝试创建一个新项目，单独引入shared_preferences的情况下编译期间也会出现。

**Comment by simplezhli** [comment]
`onCreate`是`FlutterActivity `的，这部分要看它的源码。怀疑执行顺序原因是因为只有shared_preferences插件在应用启动时马上调用了（splash_page中），其他的插件还没有调用所以排出了。

我试过flutter clean后重新run，没有这个问题。如果你说的是下图中的警告，那完全不用去关心，只是插件中用到了过时的方法导致的。

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/12456431/73726090-b4e0f000-4769-11ea-8942-00b0f1715717.png">

**Comment by userhjp** [comment]
sp报错跟你这个一样，那应该是过时警告了，只是我这边中文乱码了折腾了一阵没折腾回中文就没管了，但是至于sp为什么要单独二次初始化这问题我有时间把flutter更新到稳定版再试试，有结果了再反馈

**Comment by userhjp** [comment]
> `onCreate`是`FlutterActivity `的，这部分要看它的源码。怀疑执行顺序原因是因为只有shared_preferences插件在应用启动时马上调用了（splash_page中），其他的插件还没有调用所以排出了。
> 
> 我试过flutter clean后重新run，没有这个问题。如果你说的是下图中的警告，那完全不用去关心，只是插件中用到了过时的方法导致的。
> 
> <img alt="image" width="1199" src="https://user-images.githubusercontent.com/12456431/73726090-b4e0f000-4769-11ea-8942-00b0f1715717.png">

sp报错跟你这个一样，那应该是过时警告了，只是我这边中文乱码了折腾了一阵没折腾回中文就没管了，但是至于sp为什么要单独二次初始化这问题我有时间把flutter更新到稳定版再试试，有结果了再反馈

**Comment by simplezhli** [comment]
@userhjp 好的好的

**Comment by userhjp** [comment]
> @userhjp好的好的

我尝试将Flutter版本切换到 beta版本 Flutter 1.13.6 • channel beta之后，项目运行是正常的，sp不需要再次重复初始化一次，这个应该是Flutter的bug吧，看下次版本更新后还会不会重现

**Comment by simplezhli** [comment]
@userhjp 感谢反馈，那我暂时就关闭这个问题了。

**Comment by mrchenmo** [comment]
升级到1.17之后也遇到这个问题，sp报错，shared_preferences 0.5.7+2官方文档提示Testing时需要加
SharedPreferences.setMockInitialValues (Map<String, dynamic> values);这句话，是不是SpUtil封装的时候需要区分环境啊。

**Comment by mrchenmo** [comment]
![image](https://user-images.githubusercontent.com/18020929/82281797-d2f2f900-99c4-11ea-9904-7565481ec4ff.png)

**Comment by mrchenmo** [comment]
但是SpUtil 没有暴露Shard_preferences

**Comment by mrchenmo** [comment]
需要另外引入shared_preferences: ^0.5.7+2，然后在main中添加SharedPreferences.setMockInitialValues({}); // set initial values here if desired
这句话就不会报错了，应该是测试环境的问题，打成Release包不知会不会报错
