### ISSUE TITLE
是否有打算引用flutter core里的search delegate？

### ISSUE THREAD

**Issue by liongkj** [simplezhli/flutter_deer#90]
### 具体问题描述 ###
如题

**Comment by simplezhli** [comment]
没有。因为`SearchDelegate`提供的UI样式不符合设计图要求，使用的话需要拷贝源码修改。所以还不如完全自定义SearchBar去实现。

**Comment by liongkj** [comment]
那如果你现在的order_search需要build suggestion你有什么建议吗？我不是很明白这页mvp的操作 From: 唯鹿Sent: Saturday, February 1, 2020 16:43To: simplezhli/flutter_deerCc: KJ; AuthorSubject: Re: [simplezhli/flutter_deer] 是否有打算引用flutter core里的search delegate？ (#90) 没有。因为SearchDelegate提供的UI样式不符合设计图要求，使用的话需要拷贝源码修改。所以还不如完全自定义SearchBar去实现。—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by simplezhli** [comment]
这个页面就是通过搜索关键字查询信息，并将查询结果展示在当前页面。`buildSuggestions`就是默认展示的搜索页，可以放一些搜索的推荐关键词，或是一个空页面。而搜素结果放到`buildResults `中。

**Comment by liongkj** [comment]
不好意思我没说清楚我的问题， 我是问如果用你现在这种设计该如何加入suggestion？

**Comment by simplezhli** [comment]
suggestion 其实只是一种状态，我们可以默认展示它。当点击搜索时可以展示搜索结果，当返回时（或是搜索内容清空时）则继续展示suggestion。

现在常见的搜索设计都是搜索页与搜索结果页分离，所以实现相对更加简单。
