### ISSUE TITLE
页面rebuild问题

### ISSUE THREAD

**Issue by angelozhou** [simplezhli/flutter_deer#91]
页面之间跳转，前一个页面会一直被rebuild(我在每一个页面的build下面打印print(页面名))，如果一直这样rebuild，那provider的状态管理就没什么用了，也不用notifyListeners了， 我试过注释掉所有的notifyListeners，数据一样会被跟新到页面上

**Comment by simplezhli** [comment]
@angelozhou 这个问题其实一直存在，不仅仅是路由的跳转，软键盘的弹出也会导致rebuild。但是这种触发属于被动触发。如果在当前页面进行状态管理，使用provider这类框架仍是最佳选择。

相对来说路由跳转的影响比较大，会导致整个栈的页面进行rebuild，有一定的性能问题。这个问题最近也有在优化，完整信息可以跟踪flutter issue 11655。

**Comment by simplezhli** [comment]
补充一下，路由优化部分已经合并 https://github.com/flutter/flutter/issues/45797

**Comment by simplezhli** [comment]
1.17.0已优化路由跳转产生的build问题

**Comment by FLZC** [comment]
> 1.17.0已优化路由跳转产生的build问题

您好，1.17.0现在修复这个问题了吗，但是1.17.0添加插件需要vpn？

**Comment by simplezhli** [comment]
@FLZC vpn？

**Comment by FLZC** [comment]
> @FLZC vpn？

Flutter 1.17.0 • channel stable  版本，push和pop还是会重新build所有的界面

**Comment by simplezhli** [comment]
我的测试结果是只会再多触发一次build。而之前的表现是没次push pop都会。如果你对这个优化有疑问，可以去flutter项目提issue，毕竟如果真的如你所说没有效果，我也做不了什么。

**Comment by AcodeWang** [comment]
@simplezhli 
您好，我有个类似的问题，不知道是不是flutter route导致的。

https://stackoverflow.com/questions/62638403/how-to-reuse-the-same-layout-screen-without-creating-a-new-widget-tree-branch#comment110773775_62638403

请问关于组件重用，是否还有其他的优化方法？

**Comment by simplezhli** [comment]
@AcodeWang 这其实是设计页面结构的问题。如果你想复用Scallfold的AppBar，替换body，同时使用路由。可以考虑body根部再加一个MaterialApp，你的Screen直接放在这个MaterialApp下。
