### ISSUE TITLE
flutter 更新到 version 1.14.6后 Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

### ISSUE THREAD

**Issue by angelozhou** [simplezhli/flutter_deer#92]
flutter 更新到 version 1.14.6后 Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)，
如果用 SharedPreferences.setMockInitialValues(<String, dynamic>{});的话，每次重启数据都会被重置到空，不用这个就出错。。。

**Comment by simplezhli** [comment]
这个问题前几天有人反馈过，是新版本原因。具体见https://github.com/simplezhli/flutter_deer/issues/89 。推荐使用最新的稳定版本，其他过新的开发版本带来的问题无法预估。

**Comment by simplezhli** [comment]
请确保已经详细阅读了readme和查找了已有的issue，避免提出重复的问题。
