### ISSUE TITLE
是否能解释下怎么order list的rebuild机制？

### ISSUE THREAD

**Issue by liongkj** [simplezhli/flutter_deer#93]
我现在是有两个provider，一个Listing Provider，一个location Provider。
Location 负责管理用户所选择的地区
ListingProvider需要根据用户所选择的地区而选择 呼叫一个API得到那个地区所有的资料。
可是当我换了location，他和listing provider也不会别触发，我用着proxychangenotifier来设置这个。

希望你可以帮帮我
![image](https://user-images.githubusercontent.com/20205301/74307771-5affac00-4da1-11ea-9d7e-e971d47fb080.png)

Listingprovider
![image](https://user-images.githubusercontent.com/20205301/74307944-d6f9f400-4da1-11ea-933b-baf0abbd57e5.png)

Place List gist
[https://gist.github.com/liongkj/69d0809d0e8ffe6a44e8446638a5de13](PlaceList.dart)

Overview page截图
![overviewpagepng](https://user-images.githubusercontent.com/20205301/74307196-c0529d80-4d9f-11ea-99b7-e0caa3713cb7.png)

**Comment by simplezhli** [comment]
抱歉，我手头工作还有很多。无法当下回答你具体应该怎么做。

**Comment by simplezhli** [comment]
先抛开provider的proxy。providerA的改变要触发providerB，那就是监听providerA(`providerA.addListener()`)，在监听方法中操作providerB。具体到proxy用法，你可以对照这个小例子（https://github.com/kaboc/flutter_provider_examples/blob/e4c841658ea7880c71b079dbe4b71f2e990aed03/lib/pages/proxy_provider.dart ）来看具体哪里用法出了问题。

**Comment by liongkj** [comment]
谢谢你给的例子，完全搞明白了。现在可以了！
