### ISSUE TITLE
地图界面不加载地址list

### ISSUE THREAD

**Issue by HuasirX** [simplezhli/flutter_deer#94]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米8`
- [x] 设备系统版本：如 `Android 10`
- [x] Flutter 版本：如 `1.12.13+hotfix.5`

### 具体问题描述 ###
大佬你好，我单独使用了地址选择的页面，但是进入后地图打开但是不加载地址的list，请问一下是需要配置什么吗

**Comment by simplezhli** [comment]
是在其他应用上使用了吗？如果是的话，就是没有配置对应的appkey。具体配置见地图插件的[markdown](https://github.com/simplezhli/flutter_2d_amapl)
