### ISSUE TITLE
期待更新到最新版

### ISSUE THREAD

**Issue by william-xue** [simplezhli/flutter_deer#96]
![51583068358_ pic_hd](https://user-images.githubusercontent.com/20151622/75626586-91438500-5c03-11ea-9833-603633be1b4a.jpg)

**Comment by simplezhli** [comment]
稳定版它不香吗？😄

**Comment by william-xue** [comment]
这个插件目前不支持 你也没办法  我回退下吧

**Comment by simplezhli** [comment]
@william-xue fluro: ^1.6.1 支持到1.16.0以下
