### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by zhengyipei** [simplezhli/flutter_deer#97]
你好作者，你的项目的无法下载和克隆

**Comment by simplezhli** [comment]
@zhengyipei github确实会慢一点，我也没有办法。

**Comment by simplezhli** [comment]
@zhengyipei 分享一个我刚看到的小技巧，希望可以帮到你。
![CSDN_1583868028019](https://user-images.githubusercontent.com/12456431/76369857-f750aa80-636f-11ea-9248-abe98c055fe1.jpg)
