### ISSUE TITLE
pod install失败怎么办?

### ISSUE THREAD

**Issue by gclsoft** [simplezhli/flutter_deer#98]
### 运行环境 ###

- [x] 电脑系统：如：`mac`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 10`
- [x] Flutter 版本：如 `1.12.13+hotfix.8`

#### 异常日志 ####
bogon:ios apple$ pod install
/Users/apple/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-1.3.1/lib/cocoapods/executable.rb:89: warning: Insecure world writable dir /Users/apple/.rvm/gems/ruby-2.0.0-p353/bin in PATH, mode 040777

[!] Invalid `Podfile` file: no implicit conversion of nil into String.

 #  from /Users/apple/flutter_deer/ios/Podfile:38
 #  -------------------------------------------
 #  
 >    copied_flutter_dir = File.join(__dir__, 'Flutter')
 #    copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
 #  -------------------------------------------

**Comment by simplezhli** [comment]
@gclsoft 尝试重新安装ruby和CocoaPods 或替换为`copied_flutter_dir = File.join('.', 'Flutter')`，推荐前者。
